import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export interface IntegrationsBillingCheckoutPostRequest {
	/** The base URL for the redirect after checkout. */
	baseURL: string;
	/** The Price ID for checkout. */
	priceID: string;
	/** Enables a 14-day trial for the account. */
	enableTrial?: boolean;
}
export const IntegrationsBillingCheckoutPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		baseURL: S.String,
		priceID: S.String,
		enableTrial: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/billing/checkout", code: 200 })),
).annotate({
	identifier: "IntegrationsBillingCheckoutPostRequest",
}) as any as S.Schema<IntegrationsBillingCheckoutPostRequest>;

export interface CheckoutResponse {
	/** The unique identifier for the checkout session. */
	session_id: string;
	/** URL to redirect the user to the checkout session. */
	url: string;
}
export const CheckoutResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		session_id: S.String,
		url: S.String,
	}),
).annotate({ identifier: "CheckoutResponse" }) as any as S.Schema<CheckoutResponse>;

export type IntegrationsBillingCheckoutPostError = BadRequest | NetbirdOpError;
/** Create checkout session */
export const integrationsBillingCheckoutPost: API.OperationMethod<
	IntegrationsBillingCheckoutPostRequest,
	CheckoutResponse,
	IntegrationsBillingCheckoutPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsBillingCheckoutPostRequest,
	output: CheckoutResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
