import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsEdrHuntressDeleteRequest {}
export const IntegrationsEdrHuntressDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/edr/huntress", code: 200 })),
).annotate({
	identifier: "IntegrationsEdrHuntressDeleteRequest",
}) as any as S.Schema<IntegrationsEdrHuntressDeleteRequest>;

export type IntegrationsEdrHuntressDeleteResponse = unknown;
export const IntegrationsEdrHuntressDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsEdrHuntressDeleteResponse",
}) as any as S.Schema<IntegrationsEdrHuntressDeleteResponse>;

export interface IntegrationsEdrHuntressGetRequest {}
export const IntegrationsEdrHuntressGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/edr/huntress", code: 200 })),
).annotate({ identifier: "IntegrationsEdrHuntressGetRequest" }) as any as S.Schema<IntegrationsEdrHuntressGetRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupIssued = "api" | "integration" | "jwt";
export const GroupIssued = /*@__PURE__*/ S.String;

export interface PeerMinimum {
	/** Peer ID */
	id: string;
	/** Peer's hostname */
	name: string;
}
export const PeerMinimum = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
	}),
).annotate({ identifier: "PeerMinimum" }) as any as S.Schema<PeerMinimum>;

/** List of peers object */
export type GroupPeersList = ReadonlyArray<PeerMinimum>;
export const GroupPeersList = /*@__PURE__*/ S.Array(PeerMinimum) as any as S.Schema<GroupPeersList>;

export interface Resource {
	/** ID of the resource */
	id: string;
	/** Type of the resource */
	type: unknown;
}
export const Resource = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: S.Unknown,
	}),
).annotate({ identifier: "Resource" }) as any as S.Schema<Resource>;

export type GroupResourcesList = ReadonlyArray<Resource>;
export const GroupResourcesList = /*@__PURE__*/ S.Array(Resource) as any as S.Schema<GroupResourcesList>;

export interface Group {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupIssued;
	/** List of peers object */
	peers: GroupPeersList | null;
	resources: GroupResourcesList | null;
}
export const Group = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupIssued),
		peers: S.NullOr(GroupPeersList),
		resources: S.NullOr(GroupResourcesList),
	}),
).annotate({ identifier: "Group" }) as any as S.Schema<Group>;

/** List of groups */
export type EDRHuntressResponseGroupsList = ReadonlyArray<Group>;
export const EDRHuntressResponseGroupsList = /*@__PURE__*/ S.Array(
	Group,
) as any as S.Schema<EDRHuntressResponseGroupsList>;

/** Attribute conditions to match when approving agents */
export interface HuntressMatchAttributes {
	/** Policy status of Defender AV for Managed Antivirus. */
	defender_policy_status?: string;
	/** Status of Defender AV Managed Antivirus. */
	defender_status?: string;
	/** Sub-status of Defender AV Managed Antivirus. */
	defender_substatus?: string;
	/** Status of agent firewall. Can be one of Disabled, Enabled, Pending Isolation, Isolated, Pending Release. */
	firewall_status?: string;
}
export const HuntressMatchAttributes = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		defender_policy_status: S.optional(S.String),
		defender_status: S.optional(S.String),
		defender_substatus: S.optional(S.String),
		firewall_status: S.optional(S.String),
	}),
).annotate({ identifier: "HuntressMatchAttributes" }) as any as S.Schema<HuntressMatchAttributes>;

/** Represents a Huntress EDR integration configuration */
export interface EDRHuntressResponse {
	/** The unique numeric identifier for the integration. */
	id: number;
	/** The identifier of the account this integration belongs to. */
	account_id: string;
	/** Timestamp of when the integration was last synced. */
	last_synced_at: string;
	/** The user id that created the integration */
	created_by: string;
	/** Timestamp of when the integration was created. */
	created_at: string;
	/** Timestamp of when the integration was last updated. */
	updated_at: string;
	/** List of groups */
	groups: EDRHuntressResponseGroupsList;
	/** The devices last sync requirement interval in hours. */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled: boolean;
	match_attributes: HuntressMatchAttributes;
}
export const EDRHuntressResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number,
		account_id: S.String,
		last_synced_at: S.String,
		created_by: S.String,
		created_at: S.String,
		updated_at: S.String,
		groups: EDRHuntressResponseGroupsList,
		last_synced_interval: S.Number,
		enabled: S.Boolean,
		match_attributes: HuntressMatchAttributes,
	}),
).annotate({ identifier: "EDRHuntressResponse" }) as any as S.Schema<EDRHuntressResponse>;

/** The Groups this integrations applies to */
export type IntegrationsEdrHuntressPostRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrHuntressPostRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrHuntressPostRequestGroupsList>;

export interface IntegrationsEdrHuntressPostRequest {
	/** Huntress API key */
	api_key: string | Redacted.Redacted<string>;
	/** Huntress API secret */
	api_secret: string | Redacted.Redacted<string>;
	/** The Groups this integrations applies to */
	groups: IntegrationsEdrHuntressPostRequestGroupsList;
	/** The devices last sync requirement interval in hours. Minimum value is 24 hours */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
	match_attributes: HuntressMatchAttributes;
}
export const IntegrationsEdrHuntressPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		api_key: S.String.pipe(T.SensitiveValue({})),
		api_secret: S.String.pipe(T.SensitiveValue({})),
		groups: IntegrationsEdrHuntressPostRequestGroupsList,
		last_synced_interval: S.Number,
		enabled: S.optional(S.Boolean),
		match_attributes: HuntressMatchAttributes,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/edr/huntress", code: 200 })),
).annotate({ identifier: "IntegrationsEdrHuntressPostRequest" }) as any as S.Schema<IntegrationsEdrHuntressPostRequest>;

/** The Groups this integrations applies to */
export type IntegrationsEdrHuntressPutRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrHuntressPutRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrHuntressPutRequestGroupsList>;

export interface IntegrationsEdrHuntressPutRequest {
	/** Huntress API key */
	api_key: string | Redacted.Redacted<string>;
	/** Huntress API secret */
	api_secret: string | Redacted.Redacted<string>;
	/** The Groups this integrations applies to */
	groups: IntegrationsEdrHuntressPutRequestGroupsList;
	/** The devices last sync requirement interval in hours. Minimum value is 24 hours */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
	match_attributes: HuntressMatchAttributes;
}
export const IntegrationsEdrHuntressPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		api_key: S.String.pipe(T.SensitiveValue({})),
		api_secret: S.String.pipe(T.SensitiveValue({})),
		groups: IntegrationsEdrHuntressPutRequestGroupsList,
		last_synced_interval: S.Number,
		enabled: S.optional(S.Boolean),
		match_attributes: HuntressMatchAttributes,
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/edr/huntress", code: 200 })),
).annotate({ identifier: "IntegrationsEdrHuntressPutRequest" }) as any as S.Schema<IntegrationsEdrHuntressPutRequest>;

export type IntegrationsEdrHuntressDeleteError = BadRequest | NotFound | NetbirdOpError;
/** Delete EDR Huntress Integration Deletes an EDR Huntress Integration by its ID. */
export const integrationsEdrHuntressDelete: API.OperationMethod<
	IntegrationsEdrHuntressDeleteRequest,
	IntegrationsEdrHuntressDeleteResponse,
	IntegrationsEdrHuntressDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrHuntressDeleteRequest,
	output: IntegrationsEdrHuntressDeleteResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrHuntressGetError = BadRequest | NotFound | NetbirdOpError;
/** Get EDR Huntress Integration Retrieves a specific EDR Huntress integration by its ID. */
export const integrationsEdrHuntressGet: API.OperationMethod<
	IntegrationsEdrHuntressGetRequest,
	EDRHuntressResponse,
	IntegrationsEdrHuntressGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrHuntressGetRequest,
	output: EDRHuntressResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrHuntressPostError = BadRequest | NetbirdOpError;
/** Create EDR Huntress Integration Creates a new EDR Huntress integration */
export const integrationsEdrHuntressPost: API.OperationMethod<
	IntegrationsEdrHuntressPostRequest,
	EDRHuntressResponse,
	IntegrationsEdrHuntressPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrHuntressPostRequest,
	output: EDRHuntressResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrHuntressPutError = BadRequest | NotFound | NetbirdOpError;
/** Update EDR Huntress Integration Updates an existing EDR Huntress Integration. */
export const integrationsEdrHuntressPut: API.OperationMethod<
	IntegrationsEdrHuntressPutRequest,
	EDRHuntressResponse,
	IntegrationsEdrHuntressPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrHuntressPutRequest,
	output: EDRHuntressResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
