import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsEdrFalconDeleteRequest {}
export const IntegrationsEdrFalconDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/edr/falcon", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFalconDeleteRequest" }) as any as S.Schema<IntegrationsEdrFalconDeleteRequest>;

export interface IntegrationsEdrFalconDeleteResponse {}
export const IntegrationsEdrFalconDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IntegrationsEdrFalconDeleteResponse",
}) as any as S.Schema<IntegrationsEdrFalconDeleteResponse>;

export interface IntegrationsEdrFalconGetRequest {}
export const IntegrationsEdrFalconGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/edr/falcon", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFalconGetRequest" }) as any as S.Schema<IntegrationsEdrFalconGetRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupIssued = "api" | "integration" | "jwt";
export const GroupIssued = /*@__PURE__*/ S.String;

export interface PeerMinimum {
	/** Peer ID */
	id: string;
	/** Peer's hostname */
	name: string;
}
export const PeerMinimum = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
	}),
).annotate({ identifier: "PeerMinimum" }) as any as S.Schema<PeerMinimum>;

/** List of peers object */
export type GroupPeersList = ReadonlyArray<PeerMinimum>;
export const GroupPeersList = /*@__PURE__*/ S.Array(PeerMinimum) as any as S.Schema<GroupPeersList>;

export interface Resource {
	/** ID of the resource */
	id: string;
	/** Type of the resource */
	type: unknown;
}
export const Resource = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: S.Unknown,
	}),
).annotate({ identifier: "Resource" }) as any as S.Schema<Resource>;

export type GroupResourcesList = ReadonlyArray<Resource>;
export const GroupResourcesList = /*@__PURE__*/ S.Array(Resource) as any as S.Schema<GroupResourcesList>;

export interface Group {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupIssued;
	/** List of peers object */
	peers: GroupPeersList | null;
	resources: GroupResourcesList | null;
}
export const Group = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupIssued),
		peers: S.NullOr(GroupPeersList),
		resources: S.NullOr(GroupResourcesList),
	}),
).annotate({ identifier: "Group" }) as any as S.Schema<Group>;

/** List of groups */
export type EDRFalconResponseGroupsList = ReadonlyArray<Group>;
export const EDRFalconResponseGroupsList = /*@__PURE__*/ S.Array(Group) as any as S.Schema<EDRFalconResponseGroupsList>;

/** Represents a Falcon EDR integration */
export interface EDRFalconResponse {
	/** The unique numeric identifier for the integration. */
	id: number;
	/** The identifier of the account this integration belongs to. */
	account_id: string;
	/** Timestamp of when the integration was last synced. */
	last_synced_at: string;
	/** The user id that created the integration */
	created_by: string;
	/** Timestamp of when the integration was created. */
	created_at: string;
	/** Timestamp of when the integration was last updated. */
	updated_at: string;
	/** CrowdStrike cloud identifier */
	cloud_id: string;
	/** List of groups */
	groups: EDRFalconResponseGroupsList;
	/** The minimum Zero Trust Assessment score required for agent approval (0-100) */
	zta_score_threshold: number;
	/** Indicates whether the integration is enabled */
	enabled: boolean;
}
export const EDRFalconResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number,
		account_id: S.String,
		last_synced_at: S.String,
		created_by: S.String,
		created_at: S.String,
		updated_at: S.String,
		cloud_id: S.String,
		groups: EDRFalconResponseGroupsList,
		zta_score_threshold: S.Number,
		enabled: S.Boolean,
	}),
).annotate({ identifier: "EDRFalconResponse" }) as any as S.Schema<EDRFalconResponse>;

/** The Groups this integration applies to */
export type IntegrationsEdrFalconPostRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrFalconPostRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrFalconPostRequestGroupsList>;

export interface IntegrationsEdrFalconPostRequest {
	/** CrowdStrike API client ID */
	client_id: string;
	/** CrowdStrike API client secret */
	secret: string | Redacted.Redacted<string>;
	/** CrowdStrike cloud identifier (e.g., "us-1", "us-2", "eu-1") */
	cloud_id: string;
	/** The Groups this integration applies to */
	groups: IntegrationsEdrFalconPostRequestGroupsList;
	/** The minimum Zero Trust Assessment score required for agent approval (0-100) */
	zta_score_threshold: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
}
export const IntegrationsEdrFalconPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		client_id: S.String,
		secret: S.String.pipe(T.SensitiveValue({})),
		cloud_id: S.String,
		groups: IntegrationsEdrFalconPostRequestGroupsList,
		zta_score_threshold: S.Number,
		enabled: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/edr/falcon", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFalconPostRequest" }) as any as S.Schema<IntegrationsEdrFalconPostRequest>;

/** The Groups this integration applies to */
export type IntegrationsEdrFalconPutRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrFalconPutRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrFalconPutRequestGroupsList>;

export interface IntegrationsEdrFalconPutRequest {
	/** CrowdStrike API client ID */
	client_id: string;
	/** CrowdStrike API client secret */
	secret: string | Redacted.Redacted<string>;
	/** CrowdStrike cloud identifier (e.g., "us-1", "us-2", "eu-1") */
	cloud_id: string;
	/** The Groups this integration applies to */
	groups: IntegrationsEdrFalconPutRequestGroupsList;
	/** The minimum Zero Trust Assessment score required for agent approval (0-100) */
	zta_score_threshold: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
}
export const IntegrationsEdrFalconPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		client_id: S.String,
		secret: S.String.pipe(T.SensitiveValue({})),
		cloud_id: S.String,
		groups: IntegrationsEdrFalconPutRequestGroupsList,
		zta_score_threshold: S.Number,
		enabled: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/edr/falcon", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFalconPutRequest" }) as any as S.Schema<IntegrationsEdrFalconPutRequest>;

export type IntegrationsEdrFalconDeleteError = BadRequest | NotFound | NetbirdOpError;
/** Delete EDR Falcon Integration Deletes an existing EDR Falcon Integration by its ID. */
export const integrationsEdrFalconDelete: API.OperationMethod<
	IntegrationsEdrFalconDeleteRequest,
	IntegrationsEdrFalconDeleteResponse,
	IntegrationsEdrFalconDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFalconDeleteRequest,
	output: IntegrationsEdrFalconDeleteResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrFalconGetError = BadRequest | NotFound | NetbirdOpError;
/** Get EDR Falcon Integration Retrieves a specific EDR Falcon integration by its ID. */
export const integrationsEdrFalconGet: API.OperationMethod<
	IntegrationsEdrFalconGetRequest,
	EDRFalconResponse,
	IntegrationsEdrFalconGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFalconGetRequest,
	output: EDRFalconResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrFalconPostError = BadRequest | NetbirdOpError;
/** Create EDR Falcon Integration Creates a new EDR Falcon integration */
export const integrationsEdrFalconPost: API.OperationMethod<
	IntegrationsEdrFalconPostRequest,
	EDRFalconResponse,
	IntegrationsEdrFalconPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFalconPostRequest,
	output: EDRFalconResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrFalconPutError = BadRequest | NotFound | NetbirdOpError;
/** Update EDR Falcon Integration Updates an existing EDR Falcon Integration. */
export const integrationsEdrFalconPut: API.OperationMethod<
	IntegrationsEdrFalconPutRequest,
	EDRFalconResponse,
	IntegrationsEdrFalconPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFalconPutRequest,
	output: EDRFalconResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
