import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export interface EventsAuditGetRequest {}
export const EventsAuditGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/events/audit", code: 200 })),
).annotate({ identifier: "EventsAuditGetRequest" }) as any as S.Schema<EventsAuditGetRequest>;

/** The string code of the activity that occurred during the event */
export type EventActivityCode =
	| "peer.user.add"
	| "peer.setupkey.add"
	| "user.join"
	| "user.invite"
	| "account.create"
	| "account.delete"
	| "user.peer.delete"
	| "rule.add"
	| "rule.update"
	| "rule.delete"
	| "policy.add"
	| "policy.update"
	| "policy.delete"
	| "setupkey.add"
	| "setupkey.update"
	| "setupkey.revoke"
	| "setupkey.overuse"
	| "setupkey.delete"
	| "group.add"
	| "group.update"
	| "group.delete"
	| "peer.group.add"
	| "peer.group.delete"
	| "user.group.add"
	| "user.group.delete"
	| "user.role.update"
	| "setupkey.group.add"
	| "setupkey.group.delete"
	| "dns.setting.disabled.management.group.add"
	| "dns.setting.disabled.management.group.delete"
	| "route.add"
	| "route.delete"
	| "route.update"
	| "peer.ssh.enable"
	| "peer.ssh.disable"
	| "peer.rename"
	| "peer.login.expiration.enable"
	| "peer.login.expiration.disable"
	| "nameserver.group.add"
	| "nameserver.group.delete"
	| "nameserver.group.update"
	| "account.setting.peer.login.expiration.update"
	| "account.setting.peer.login.expiration.enable"
	| "account.setting.peer.login.expiration.disable"
	| "personal.access.token.create"
	| "personal.access.token.delete"
	| "service.user.create"
	| "service.user.delete"
	| "user.block"
	| "user.unblock"
	| "user.delete"
	| "user.peer.login"
	| "peer.login.expire"
	| "dashboard.login"
	| "integration.create"
	| "integration.update"
	| "integration.delete"
	| "account.setting.peer.approval.enable"
	| "account.setting.peer.approval.disable"
	| "peer.approve"
	| "peer.approval.revoke"
	| "transferred.owner.role"
	| "posture.check.create"
	| "posture.check.update"
	| "posture.check.delete"
	| "peer.inactivity.expiration.enable"
	| "peer.inactivity.expiration.disable"
	| "account.peer.inactivity.expiration.enable"
	| "account.peer.inactivity.expiration.disable"
	| "account.peer.inactivity.expiration.update"
	| "account.setting.group.propagation.enable"
	| "account.setting.group.propagation.disable"
	| "account.setting.routing.peer.dns.resolution.enable"
	| "account.setting.routing.peer.dns.resolution.disable"
	| "network.create"
	| "network.update"
	| "network.delete"
	| "network.resource.create"
	| "network.resource.update"
	| "network.resource.delete"
	| "network.router.create"
	| "network.router.update"
	| "network.router.delete"
	| "resource.group.add"
	| "resource.group.delete"
	| "account.dns.domain.update"
	| "account.setting.lazy.connection.enable"
	| "account.setting.lazy.connection.disable"
	| "account.network.range.update"
	| "peer.ip.update"
	| "user.approve"
	| "user.reject"
	| "user.create"
	| "account.settings.auto.version.update"
	| "identityprovider.create"
	| "identityprovider.update"
	| "identityprovider.delete"
	| "dns.zone.create"
	| "dns.zone.update"
	| "dns.zone.delete"
	| "dns.zone.record.create"
	| "dns.zone.record.update"
	| "dns.zone.record.delete"
	| "peer.job.create"
	| "user.password.change"
	| "user.invite.link.create"
	| "user.invite.link.accept"
	| "user.invite.link.regenerate"
	| "user.invite.link.delete"
	| "service.create"
	| "service.update"
	| "service.delete";
export const EventActivityCode = /*@__PURE__*/ S.String;

/** The metadata of the event */
export type EventMetaMap = { [key: string]: string };
export const EventMetaMap = /*@__PURE__*/ S.Record(S.String, S.String) as any as S.Schema<EventMetaMap>;

export interface Event {
	/** Event unique identifier */
	id: string;
	/** The date and time when the event occurred */
	timestamp: string;
	/** The activity that occurred during the event */
	activity: string;
	/** The string code of the activity that occurred during the event */
	activity_code: EventActivityCode;
	/** The ID of the initiator of the event. E.g., an ID of a user that triggered the event. */
	initiator_id: string;
	/** The name of the initiator of the event. */
	initiator_name: string;
	/** The e-mail address of the initiator of the event. E.g., an e-mail of a user that triggered the event. */
	initiator_email: string;
	/** The ID of the target of the event. E.g., an ID of the peer that a user removed. */
	target_id: string;
	/** The metadata of the event */
	meta: EventMetaMap;
}
export const Event = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		timestamp: S.String,
		activity: S.String,
		activity_code: EventActivityCode,
		initiator_id: S.String,
		initiator_name: S.String,
		initiator_email: S.String,
		target_id: S.String,
		meta: EventMetaMap,
	}),
).annotate({ identifier: "Event" }) as any as S.Schema<Event>;

export type EventsAuditGetResponseBodyList = ReadonlyArray<Event>;
export const EventsAuditGetResponseBodyList = /*@__PURE__*/ S.Array(
	Event,
) as any as S.Schema<EventsAuditGetResponseBodyList>;

export type EventsAuditGetResponse = EventsAuditGetResponseBodyList;
export const EventsAuditGetResponse = /*@__PURE__*/ S.suspend(() =>
	EventsAuditGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "EventsAuditGetResponse" }) as any as S.Schema<EventsAuditGetResponse>;

export type EventsNetworkTrafficGetRequestType = "TYPE_UNKNOWN" | "TYPE_START" | "TYPE_END" | "TYPE_DROP";
export const EventsNetworkTrafficGetRequestType = /*@__PURE__*/ S.String;

export type EventsNetworkTrafficGetRequestConnectionType = "P2P" | "ROUTED";
export const EventsNetworkTrafficGetRequestConnectionType = /*@__PURE__*/ S.String;

export type EventsNetworkTrafficGetRequestDirection = "INGRESS" | "EGRESS" | "DIRECTION_UNKNOWN";
export const EventsNetworkTrafficGetRequestDirection = /*@__PURE__*/ S.String;

export interface EventsNetworkTrafficGetRequest {
	/** Page number */
	page?: number;
	/** Number of items per page */
	page_size?: number;
	/** Filter by user ID */
	user_id?: string;
	/** Filter by reporter ID */
	reporter_id?: string;
	/** Filter by source endpoint ID */
	source_id?: string;
	/** Filter by destination endpoint ID */
	destination_id?: string;
	/** Filter by protocol */
	protocol?: number;
	/** Filter by event type */
	type?: EventsNetworkTrafficGetRequestType;
	/** Filter by connection type */
	connection_type?: EventsNetworkTrafficGetRequestConnectionType;
	/** Filter by direction */
	direction?: EventsNetworkTrafficGetRequestDirection;
	/** Case-insensitive partial match on user email, source/destination names, and source/destination addresses */
	search?: string;
	/** Start date for filtering events (ISO 8601 format, e.g., 2024-01-01T00:00:00Z). */
	start_date?: string;
	/** End date for filtering events (ISO 8601 format, e.g., 2024-01-31T23:59:59Z). */
	end_date?: string;
}
export const EventsNetworkTrafficGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		page: S.optional(S.Number.pipe(T.Query())),
		page_size: S.optional(S.Number.pipe(T.Query())),
		user_id: S.optional(S.String.pipe(T.Query())),
		reporter_id: S.optional(S.String.pipe(T.Query())),
		source_id: S.optional(S.String.pipe(T.Query())),
		destination_id: S.optional(S.String.pipe(T.Query())),
		protocol: S.optional(S.Number.pipe(T.Query())),
		type: S.optional(EventsNetworkTrafficGetRequestType.pipe(T.Query())),
		connection_type: S.optional(EventsNetworkTrafficGetRequestConnectionType.pipe(T.Query())),
		direction: S.optional(EventsNetworkTrafficGetRequestDirection.pipe(T.Query())),
		search: S.optional(S.String.pipe(T.Query())),
		start_date: S.optional(S.String.pipe(T.Query())),
		end_date: S.optional(S.String.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/events/network-traffic", code: 200 })),
).annotate({ identifier: "EventsNetworkTrafficGetRequest" }) as any as S.Schema<EventsNetworkTrafficGetRequest>;

export interface NetworkTrafficLocation {
	/** Name of the city (if known). */
	city_name: string;
	/** ISO country code (if known). */
	country_code: string;
}
export const NetworkTrafficLocation = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		city_name: S.String,
		country_code: S.String,
	}),
).annotate({ identifier: "NetworkTrafficLocation" }) as any as S.Schema<NetworkTrafficLocation>;

export interface NetworkTrafficEndpoint {
	/** ID of this endpoint (e.g., peer ID or resource ID). */
	id: string;
	/** Type of the endpoint object (e.g., UNKNOWN, PEER, HOST_RESOURCE). */
	type: string;
	/** Name is the name of the endpoint object (e.g., a peer name). */
	name: string;
	geo_location: NetworkTrafficLocation;
	/** Operating system of the peer, if applicable. */
	os: string | null;
	/** IP address (and possibly port) in string form. */
	address: string;
	/** DNS label/name if available. */
	dns_label: string | null;
}
export const NetworkTrafficEndpoint = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: S.String,
		name: S.String,
		geo_location: NetworkTrafficLocation,
		os: S.NullOr(S.String),
		address: S.String,
		dns_label: S.NullOr(S.String),
	}),
).annotate({ identifier: "NetworkTrafficEndpoint" }) as any as S.Schema<NetworkTrafficEndpoint>;

export interface NetworkTrafficUser {
	/** UserID is the ID of the user that initiated the event (can be empty as not every event is user-initiated). */
	id: string;
	/** Email of the user who initiated the event (if any). */
	email: string;
	/** Name of the user who initiated the event (if any). */
	name: string;
}
export const NetworkTrafficUser = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		email: S.String,
		name: S.String,
	}),
).annotate({ identifier: "NetworkTrafficUser" }) as any as S.Schema<NetworkTrafficUser>;

export interface NetworkTrafficPolicy {
	/** ID of the policy that allowed this event. */
	id: string;
	/** Name of the policy that allowed this event. */
	name: string;
}
export const NetworkTrafficPolicy = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
	}),
).annotate({ identifier: "NetworkTrafficPolicy" }) as any as S.Schema<NetworkTrafficPolicy>;

export interface NetworkTrafficICMP {
	/** ICMP type (if applicable). */
	type: number;
	/** ICMP code (if applicable). */
	code: number;
}
export const NetworkTrafficICMP = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		type: S.Number,
		code: S.Number,
	}),
).annotate({ identifier: "NetworkTrafficICMP" }) as any as S.Schema<NetworkTrafficICMP>;

export interface NetworkTrafficSubEvent {
	/** Type of the event (e.g., TYPE_UNKNOWN, TYPE_START, TYPE_END, TYPE_DROP). */
	type: string;
	/** Timestamp of the event as sent by the peer. */
	timestamp: string;
}
export const NetworkTrafficSubEvent = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		type: S.String,
		timestamp: S.String,
	}),
).annotate({ identifier: "NetworkTrafficSubEvent" }) as any as S.Schema<NetworkTrafficSubEvent>;

/** List of events that are correlated to this flow (e.g., start, end). */
export type NetworkTrafficEventEventsList = ReadonlyArray<NetworkTrafficSubEvent>;
export const NetworkTrafficEventEventsList = /*@__PURE__*/ S.Array(
	NetworkTrafficSubEvent,
) as any as S.Schema<NetworkTrafficEventEventsList>;

export interface NetworkTrafficEvent {
	/** FlowID is the ID of the connection flow. Not unique because it can be the same for multiple events (e.g., start and end of the connection). */
	flow_id: string;
	/** ID of the reporter of the event (e.g., the peer that reported the event). */
	reporter_id: string;
	source: NetworkTrafficEndpoint;
	destination: NetworkTrafficEndpoint;
	user: NetworkTrafficUser;
	policy: NetworkTrafficPolicy;
	icmp: NetworkTrafficICMP;
	/** Protocol is the protocol of the traffic (e.g. 1 = ICMP, 6 = TCP, 17 = UDP, etc.). */
	protocol: number;
	/** Direction of the traffic (e.g. DIRECTION_UNKNOWN, INGRESS, EGRESS). */
	direction: string;
	/** Number of bytes received. */
	rx_bytes: number;
	/** Number of packets received. */
	rx_packets: number;
	/** Number of bytes transmitted. */
	tx_bytes: number;
	/** Number of packets transmitted. */
	tx_packets: number;
	/** Number of start events. */
	num_of_starts: number;
	/** Number of end events. */
	num_of_ends: number;
	/** Number of drop events. */
	num_of_drops: number;
	/** Timestamp of the start of the aggregation window. */
	window_start: string;
	/** Timestamp of the end of the aggregation window. */
	window_end: string;
	/** List of events that are correlated to this flow (e.g., start, end). */
	events: NetworkTrafficEventEventsList;
}
export const NetworkTrafficEvent = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		flow_id: S.String,
		reporter_id: S.String,
		source: NetworkTrafficEndpoint,
		destination: NetworkTrafficEndpoint,
		user: NetworkTrafficUser,
		policy: NetworkTrafficPolicy,
		icmp: NetworkTrafficICMP,
		protocol: S.Number,
		direction: S.String,
		rx_bytes: S.Number,
		rx_packets: S.Number,
		tx_bytes: S.Number,
		tx_packets: S.Number,
		num_of_starts: S.Number,
		num_of_ends: S.Number,
		num_of_drops: S.Number,
		window_start: S.String,
		window_end: S.String,
		events: NetworkTrafficEventEventsList,
	}),
).annotate({ identifier: "NetworkTrafficEvent" }) as any as S.Schema<NetworkTrafficEvent>;

/** List of network traffic events */
export type NetworkTrafficEventsResponseDataList = ReadonlyArray<NetworkTrafficEvent>;
export const NetworkTrafficEventsResponseDataList = /*@__PURE__*/ S.Array(
	NetworkTrafficEvent,
) as any as S.Schema<NetworkTrafficEventsResponseDataList>;

export interface NetworkTrafficEventsResponse {
	/** List of network traffic events */
	data: NetworkTrafficEventsResponseDataList;
	/** Current page number */
	page: number;
	/** Number of items per page */
	page_size: number;
	/** Total number of event records available */
	total_records: number;
	/** Total number of pages available */
	total_pages: number;
}
export const NetworkTrafficEventsResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		data: NetworkTrafficEventsResponseDataList,
		page: S.Number,
		page_size: S.Number,
		total_records: S.Number,
		total_pages: S.Number,
	}),
).annotate({ identifier: "NetworkTrafficEventsResponse" }) as any as S.Schema<NetworkTrafficEventsResponse>;

export type EventsProxyGetRequestSortBy =
	| "timestamp"
	| "url"
	| "host"
	| "path"
	| "method"
	| "status_code"
	| "duration"
	| "source_ip"
	| "user_id"
	| "auth_method"
	| "reason";
export const EventsProxyGetRequestSortBy = /*@__PURE__*/ S.String;

export type EventsProxyGetRequestSortOrder = "asc" | "desc";
export const EventsProxyGetRequestSortOrder = /*@__PURE__*/ S.String;

export type EventsProxyGetRequestMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
export const EventsProxyGetRequestMethod = /*@__PURE__*/ S.String;

export type EventsProxyGetRequestStatus = "success" | "failed";
export const EventsProxyGetRequestStatus = /*@__PURE__*/ S.String;

export interface EventsProxyGetRequest {
	/** Page number for pagination (1-indexed) */
	page?: number;
	/** Number of items per page (max 100) */
	page_size?: number;
	/** Field to sort by (url sorts by host then path) */
	sort_by?: EventsProxyGetRequestSortBy;
	/** Sort order (ascending or descending) */
	sort_order?: EventsProxyGetRequestSortOrder;
	/** General search across request ID, host, path, source IP, user email, and user name */
	search?: string;
	/** Filter by source IP address */
	source_ip?: string;
	/** Filter by host header */
	host?: string;
	/** Filter by request path (supports partial matching) */
	path?: string;
	/** Filter by authenticated user ID */
	user_id?: string;
	/** Filter by user email (partial matching) */
	user_email?: string;
	/** Filter by user name (partial matching) */
	user_name?: string;
	/** Filter by HTTP method */
	method?: EventsProxyGetRequestMethod;
	/** Filter by status (success = 2xx/3xx, failed = 1xx/4xx/5xx) */
	status?: EventsProxyGetRequestStatus;
	/** Filter by HTTP status code */
	status_code?: number;
	/** Filter by timestamp >= start_date (RFC3339 format) */
	start_date?: string;
	/** Filter by timestamp <= end_date (RFC3339 format) */
	end_date?: string;
}
export const EventsProxyGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		page: S.optional(S.Number.pipe(T.Query())),
		page_size: S.optional(S.Number.pipe(T.Query())),
		sort_by: S.optional(EventsProxyGetRequestSortBy.pipe(T.Query())),
		sort_order: S.optional(EventsProxyGetRequestSortOrder.pipe(T.Query())),
		search: S.optional(S.String.pipe(T.Query())),
		source_ip: S.optional(S.String.pipe(T.Query())),
		host: S.optional(S.String.pipe(T.Query())),
		path: S.optional(S.String.pipe(T.Query())),
		user_id: S.optional(S.String.pipe(T.Query())),
		user_email: S.optional(S.String.pipe(T.Query())),
		user_name: S.optional(S.String.pipe(T.Query())),
		method: S.optional(EventsProxyGetRequestMethod.pipe(T.Query())),
		status: S.optional(EventsProxyGetRequestStatus.pipe(T.Query())),
		status_code: S.optional(S.Number.pipe(T.Query())),
		start_date: S.optional(S.String.pipe(T.Query())),
		end_date: S.optional(S.String.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/events/proxy", code: 200 })),
).annotate({ identifier: "EventsProxyGetRequest" }) as any as S.Schema<EventsProxyGetRequest>;

/** Extra context about the request (e.g. crowdsec_verdict) */
export type ProxyAccessLogMetadataMap = { [key: string]: string };
export const ProxyAccessLogMetadataMap = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<ProxyAccessLogMetadataMap>;

export interface ProxyAccessLog {
	/** Unique identifier for the access log entry */
	id: string;
	/** ID of the service that handled the request */
	service_id: string;
	/** Timestamp when the request was made */
	timestamp: string;
	/** HTTP method of the request */
	method: string;
	/** Host header of the request */
	host: string;
	/** Path of the request */
	path: string;
	/** Duration of the request in milliseconds */
	duration_ms: number;
	/** HTTP status code returned */
	status_code: number;
	/** Source IP address of the request */
	source_ip?: string;
	/** Reason for the request result (e.g., authentication failure) */
	reason?: string;
	/** ID of the authenticated user, if applicable */
	user_id?: string;
	/** Authentication method used (e.g., password, pin, oidc) */
	auth_method_used?: string;
	/** Country code from geolocation */
	country_code?: string;
	/** City name from geolocation */
	city_name?: string;
	/** First-level administrative subdivision ISO code (e.g. state/province) */
	subdivision_code?: string;
	/** Bytes uploaded (request body size) */
	bytes_upload: number;
	/** Bytes downloaded (response body size) */
	bytes_download: number;
	/** Protocol type: http, tcp, or udp */
	protocol?: string;
	/** Extra context about the request (e.g. crowdsec_verdict) */
	metadata?: ProxyAccessLogMetadataMap;
}
export const ProxyAccessLog = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		service_id: S.String,
		timestamp: S.String,
		method: S.String,
		host: S.String,
		path: S.String,
		duration_ms: S.Number,
		status_code: S.Number,
		source_ip: S.optional(S.String),
		reason: S.optional(S.String),
		user_id: S.optional(S.String),
		auth_method_used: S.optional(S.String),
		country_code: S.optional(S.String),
		city_name: S.optional(S.String),
		subdivision_code: S.optional(S.String),
		bytes_upload: S.Number,
		bytes_download: S.Number,
		protocol: S.optional(S.String),
		metadata: S.optional(ProxyAccessLogMetadataMap),
	}),
).annotate({ identifier: "ProxyAccessLog" }) as any as S.Schema<ProxyAccessLog>;

/** List of proxy access log entries */
export type ProxyAccessLogsResponseDataList = ReadonlyArray<ProxyAccessLog>;
export const ProxyAccessLogsResponseDataList = /*@__PURE__*/ S.Array(
	ProxyAccessLog,
) as any as S.Schema<ProxyAccessLogsResponseDataList>;

export interface ProxyAccessLogsResponse {
	/** List of proxy access log entries */
	data: ProxyAccessLogsResponseDataList;
	/** Current page number */
	page: number;
	/** Number of items per page */
	page_size: number;
	/** Total number of log records available */
	total_records: number;
	/** Total number of pages available */
	total_pages: number;
}
export const ProxyAccessLogsResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		data: ProxyAccessLogsResponseDataList,
		page: S.Number,
		page_size: S.Number,
		total_records: S.Number,
		total_pages: S.Number,
	}),
).annotate({ identifier: "ProxyAccessLogsResponse" }) as any as S.Schema<ProxyAccessLogsResponse>;

export type EventsAuditGetError = BadRequest | Forbidden | NetbirdOpError;
/** List all Audit Events Returns a list of all audit events */
export const eventsAuditGet: API.OperationMethod<
	EventsAuditGetRequest,
	EventsAuditGetResponse,
	EventsAuditGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: EventsAuditGetRequest,
	output: EventsAuditGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type EventsNetworkTrafficGetError = BadRequest | Forbidden | NetbirdOpError;
/** List all Traffic Events Returns a list of all network traffic events */
export const eventsNetworkTrafficGet: API.OperationMethod<
	EventsNetworkTrafficGetRequest,
	NetworkTrafficEventsResponse,
	EventsNetworkTrafficGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: EventsNetworkTrafficGetRequest,
	output: NetworkTrafficEventsResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type EventsProxyGetError = Forbidden | NetbirdOpError;
/** List all Reverse Proxy Access Logs Returns a paginated list of all reverse proxy access log entries */
export const eventsProxyGet: API.OperationMethod<
	EventsProxyGetRequest,
	ProxyAccessLogsResponse,
	EventsProxyGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: EventsProxyGetRequest,
	output: ProxyAccessLogsResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
