import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export interface InstanceGetRequest {}
export const InstanceGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/instance", code: 200 })),
).annotate({ identifier: "InstanceGetRequest" }) as any as S.Schema<InstanceGetRequest>;

/** Instance status information */
export interface InstanceStatus {
	/** Indicates whether the instance requires initial setup */
	setup_required: boolean;
}
export const InstanceStatus = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		setup_required: S.Boolean,
	}),
).annotate({ identifier: "InstanceStatus" }) as any as S.Schema<InstanceStatus>;

export interface InstanceVersionGetRequest {}
export const InstanceVersionGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/instance/version", code: 200 })),
).annotate({ identifier: "InstanceVersionGetRequest" }) as any as S.Schema<InstanceVersionGetRequest>;

/** Version information for NetBird components */
export interface InstanceVersionInfo {
	/** The current running version of the management server */
	management_current_version: string;
	/** The latest available version of the dashboard (from GitHub releases) */
	dashboard_available_version?: string;
	/** The latest available version of the management server (from GitHub releases) */
	management_available_version?: string;
	/** Indicates if a newer management version is available */
	management_update_available: boolean;
}
export const InstanceVersionInfo = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		management_current_version: S.String,
		dashboard_available_version: S.optional(S.String),
		management_available_version: S.optional(S.String),
		management_update_available: S.Boolean,
	}),
).annotate({ identifier: "InstanceVersionInfo" }) as any as S.Schema<InstanceVersionInfo>;

export interface SetupPostRequest {
	/** Email address for the admin user */
	email: string;
	/** Password for the admin user (minimum 8 characters) */
	password: string | Redacted.Redacted<string>;
	/** Display name for the admin user (defaults to email if not provided) */
	name: string;
	/** If true and the server has setup-time PAT issuance enabled (NB_SETUP_PAT_ENABLED=true), create a Personal Access Token for the new owner user and return it in the response. Ignored when the server feature is disabled. */
	create_pat?: boolean;
	/** Expiration of the Personal Access Token in days. Applies only when create_pat is true and the server feature is enabled. Defaults to 1 day when omitted. */
	pat_expire_in?: number;
}
export const SetupPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		email: S.String,
		password: S.String.pipe(T.SensitiveValue({})),
		name: S.String,
		create_pat: S.optional(S.Boolean),
		pat_expire_in: S.optional(S.Number),
	}).pipe(T.Http({ method: "POST", uri: "/api/setup", code: 200 })),
).annotate({ identifier: "SetupPostRequest" }) as any as S.Schema<SetupPostRequest>;

/** Response after successful instance setup */
export interface SetupResponse {
	/** The ID of the created user */
	user_id: string;
	/** Email address of the created user */
	email: string;
	/** Plain text Personal Access Token created during setup. Present only when create_pat was requested and the NB_SETUP_PAT_ENABLED feature was enabled on the server. */
	personal_access_token?: string;
}
export const SetupResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		user_id: S.String,
		email: S.String,
		personal_access_token: S.optional(S.String),
	}),
).annotate({ identifier: "SetupResponse" }) as any as S.Schema<SetupResponse>;

export type InstanceGetError = NetbirdOpError;
/** Get Instance Status Returns the instance status including whether initial setup is required. This endpoint does not require authentication. */
export const instanceGet: API.OperationMethod<InstanceGetRequest, InstanceStatus, InstanceGetError, NetbirdOpContext> =
	/*@__PURE__*/ API.make(() => ({
		input: InstanceGetRequest,
		output: InstanceStatus,
		errors: [UnknownNetbirdError],
		protocol: NetbirdProtocol,
		retry: Retry.Retry,
	}));

export type InstanceVersionGetError = Forbidden | NetbirdOpError;
/** Get Version Info Returns version information for NetBird components including the current management server version and latest available versions from GitHub. */
export const instanceVersionGet: API.OperationMethod<
	InstanceVersionGetRequest,
	InstanceVersionInfo,
	InstanceVersionGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: InstanceVersionGetRequest,
	output: InstanceVersionInfo,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type SetupPostError = BadRequest | NetbirdOpError;
/** Setup Instance Creates the initial admin user for the instance. This endpoint does not require authentication but only works when setup is required (no accounts exist and embedded IDP is enabled). When the management server is started with `NB_SETUP_PAT_ENABLED=true` and the request includes `create_pat: true`, the endpoint also provisions the NetBird account for the new owner user and returns the plain text Personal Access Token in `personal_access_token`. The optional `pat_expire_in` value applies only when `create_pat` is true and defaults to 1 day when omitted. If a post-user step fails, setup-created resources are rolled back when safe; if account cleanup fails, the owner user is left in place to avoid leaving an account without its admin user. */
export const setupPost: API.OperationMethod<SetupPostRequest, SetupResponse, SetupPostError, NetbirdOpContext> =
	/*@__PURE__*/ API.make(() => ({
		input: SetupPostRequest,
		output: SetupResponse,
		errors: [BadRequest, UnknownNetbirdError],
		protocol: NetbirdProtocol,
		retry: Retry.Retry,
	}));
