import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export interface PeersPeerIdJobsGetRequest {
	/** The unique identifier of a peer */
	peerId: string;
}
export const PeersPeerIdJobsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/peers/{peerId}/jobs", code: 200 })),
).annotate({ identifier: "PeersPeerIdJobsGetRequest" }) as any as S.Schema<PeersPeerIdJobsGetRequest>;

export type JobResponseStatus = "pending" | "succeeded" | "failed";
export const JobResponseStatus = /*@__PURE__*/ S.String;

/** Identifies the type of workload the job will execute. Currently only `"bundle"` is supported. */
export type WorkloadType = "bundle";
export const WorkloadType = /*@__PURE__*/ S.String;

/** These parameters control what gets included in the bundle and how it is processed. */
export interface BundleParameters {
	/** Whether to generate a bundle for the given timeframe. */
	bundle_for: boolean;
	/** Time period in minutes for which to generate the bundle. */
	bundle_for_time: number;
	/** Maximum number of log files to include in the bundle. */
	log_file_count: number;
	/** Whether sensitive data should be anonymized in the bundle. */
	anonymize: boolean;
}
export const BundleParameters = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		bundle_for: S.Boolean,
		bundle_for_time: S.Number,
		log_file_count: S.Number,
		anonymize: S.Boolean,
	}),
).annotate({ identifier: "BundleParameters" }) as any as S.Schema<BundleParameters>;

export interface BundleResult {
	upload_key?: string | null;
}
export const BundleResult = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		upload_key: S.optional(S.NullOr(S.String)),
	}),
).annotate({ identifier: "BundleResult" }) as any as S.Schema<BundleResult>;

export interface BundleWorkloadResponse {
	type: WorkloadType;
	parameters: BundleParameters;
	result: BundleResult;
}
export const BundleWorkloadResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		type: WorkloadType,
		parameters: BundleParameters,
		result: BundleResult,
	}),
).annotate({ identifier: "BundleWorkloadResponse" }) as any as S.Schema<BundleWorkloadResponse>;

export interface JobResponse {
	id: string;
	created_at: string;
	completed_at?: string | null;
	triggered_by: string;
	status: JobResponseStatus;
	failed_reason?: string | null;
	workload: BundleWorkloadResponse;
}
export const JobResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		created_at: S.String,
		completed_at: S.optional(S.NullOr(S.String)),
		triggered_by: S.String,
		status: JobResponseStatus,
		failed_reason: S.optional(S.NullOr(S.String)),
		workload: BundleWorkloadResponse,
	}),
).annotate({ identifier: "JobResponse" }) as any as S.Schema<JobResponse>;

export type PeersPeerIdJobsGetResponseBodyList = ReadonlyArray<JobResponse>;
export const PeersPeerIdJobsGetResponseBodyList = /*@__PURE__*/ S.Array(
	JobResponse,
) as any as S.Schema<PeersPeerIdJobsGetResponseBodyList>;

export type PeersPeerIdJobsGetResponse = PeersPeerIdJobsGetResponseBodyList;
export const PeersPeerIdJobsGetResponse = /*@__PURE__*/ S.suspend(() =>
	PeersPeerIdJobsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "PeersPeerIdJobsGetResponse" }) as any as S.Schema<PeersPeerIdJobsGetResponse>;

export interface PeersPeerIdJobsJobIdGetRequest {
	/** The unique identifier of a peer */
	peerId: string;
	/** The unique identifier of a job */
	jobId: string;
}
export const PeersPeerIdJobsJobIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		jobId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/peers/{peerId}/jobs/{jobId}", code: 200 })),
).annotate({ identifier: "PeersPeerIdJobsJobIdGetRequest" }) as any as S.Schema<PeersPeerIdJobsJobIdGetRequest>;

export interface BundleWorkloadRequest {
	type: WorkloadType;
	parameters: BundleParameters;
}
export const BundleWorkloadRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		type: WorkloadType,
		parameters: BundleParameters,
	}),
).annotate({ identifier: "BundleWorkloadRequest" }) as any as S.Schema<BundleWorkloadRequest>;

export interface PeersPeerIdJobsPostRequest {
	/** The unique identifier of a peer */
	peerId: string;
	workload: BundleWorkloadRequest;
}
export const PeersPeerIdJobsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		workload: BundleWorkloadRequest,
	}).pipe(T.Http({ method: "POST", uri: "/api/peers/{peerId}/jobs", code: 200 })),
).annotate({ identifier: "PeersPeerIdJobsPostRequest" }) as any as S.Schema<PeersPeerIdJobsPostRequest>;

export type PeersPeerIdJobsGetError = BadRequest | Forbidden | NetbirdOpError;
/** List Jobs Retrieve all jobs for a given peer */
export const peersPeerIdJobsGet: API.OperationMethod<
	PeersPeerIdJobsGetRequest,
	PeersPeerIdJobsGetResponse,
	PeersPeerIdJobsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdJobsGetRequest,
	output: PeersPeerIdJobsGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdJobsJobIdGetError = BadRequest | Forbidden | NetbirdOpError;
/** Get Job Retrieve details of a specific job */
export const peersPeerIdJobsJobIdGet: API.OperationMethod<
	PeersPeerIdJobsJobIdGetRequest,
	JobResponse,
	PeersPeerIdJobsJobIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdJobsJobIdGetRequest,
	output: JobResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdJobsPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create Job Create a new job for a given peer */
export const peersPeerIdJobsPost: API.OperationMethod<
	PeersPeerIdJobsPostRequest,
	JobResponse,
	PeersPeerIdJobsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdJobsPostRequest,
	output: JobResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
