import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsMspTenantsGetRequest {}
export const IntegrationsMspTenantsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/msp/tenants", code: 200 })),
).annotate({ identifier: "IntegrationsMspTenantsGetRequest" }) as any as S.Schema<IntegrationsMspTenantsGetRequest>;

export interface TenantGroupResponse {
	/** The Group ID */
	id: string;
	/** The Role name */
	role: string;
}
export const TenantGroupResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		role: S.String,
	}),
).annotate({ identifier: "TenantGroupResponse" }) as any as S.Schema<TenantGroupResponse>;

/** MSP users Groups that can access the Tenant and Roles to assume */
export type TenantResponseGroupsList = ReadonlyArray<TenantGroupResponse>;
export const TenantResponseGroupsList = /*@__PURE__*/ S.Array(
	TenantGroupResponse,
) as any as S.Schema<TenantResponseGroupsList>;

/** The status of the tenant */
export type TenantResponseStatus = "existing" | "invited" | "pending" | "active";
export const TenantResponseStatus = /*@__PURE__*/ S.String;

export interface TenantResponse {
	/** The updated MSP tenant account ID */
	id: string;
	/** The name for the MSP tenant */
	name: string;
	/** The tenant account domain */
	domain: string;
	/** MSP users Groups that can access the Tenant and Roles to assume */
	groups: TenantResponseGroupsList;
	/** The date and time when the tenant was activated. */
	activated_at?: string;
	/** The DNS challenge to set in a TXT record */
	dns_challenge: string;
	/** The date and time when the tenant was created. */
	created_at: string;
	/** The date and time when the tenant was last updated. */
	updated_at: string;
	/** The date and time when the existing tenant was invited. */
	invited_at?: string;
	/** The status of the tenant */
	status: TenantResponseStatus;
}
export const TenantResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		domain: S.String,
		groups: TenantResponseGroupsList,
		activated_at: S.optional(S.String),
		dns_challenge: S.String,
		created_at: S.String,
		updated_at: S.String,
		invited_at: S.optional(S.String),
		status: TenantResponseStatus,
	}),
).annotate({ identifier: "TenantResponse" }) as any as S.Schema<TenantResponse>;

export type GetTenantsResponse = ReadonlyArray<TenantResponse>;
export const GetTenantsResponse = /*@__PURE__*/ S.Array(TenantResponse) as any as S.Schema<GetTenantsResponse>;

export type IntegrationsMspTenantsGetResponse = GetTenantsResponse;
export const IntegrationsMspTenantsGetResponse = /*@__PURE__*/ S.suspend(() =>
	GetTenantsResponse.pipe(T.RawResponseRoot()),
).annotate({ identifier: "IntegrationsMspTenantsGetResponse" }) as any as S.Schema<IntegrationsMspTenantsGetResponse>;

export interface IntegrationsMspTenantsIdDnsPostRequest {
	/** The unique identifier of a tenant account */
	id: string;
}
export const IntegrationsMspTenantsIdDnsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/msp/tenants/{id}/dns", code: 200 })),
).annotate({
	identifier: "IntegrationsMspTenantsIdDnsPostRequest",
}) as any as S.Schema<IntegrationsMspTenantsIdDnsPostRequest>;

export interface IntegrationsMspTenantsIdDnsPostResponse {}
export const IntegrationsMspTenantsIdDnsPostResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IntegrationsMspTenantsIdDnsPostResponse",
}) as any as S.Schema<IntegrationsMspTenantsIdDnsPostResponse>;

export interface IntegrationsMspTenantsIdInvitePostRequest {
	/** The unique identifier of an existing tenant account */
	id: string;
}
export const IntegrationsMspTenantsIdInvitePostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/msp/tenants/{id}/invite", code: 200 })),
).annotate({
	identifier: "IntegrationsMspTenantsIdInvitePostRequest",
}) as any as S.Schema<IntegrationsMspTenantsIdInvitePostRequest>;

/** Accept or decline the invitation. */
export type IntegrationsMspTenantsIdInvitePutRequestValue = "accept" | "decline";
export const IntegrationsMspTenantsIdInvitePutRequestValue = /*@__PURE__*/ S.String;

export interface IntegrationsMspTenantsIdInvitePutRequest {
	/** The unique identifier of an existing tenant account */
	id: string;
	/** Accept or decline the invitation. */
	value: IntegrationsMspTenantsIdInvitePutRequestValue;
}
export const IntegrationsMspTenantsIdInvitePutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
		value: IntegrationsMspTenantsIdInvitePutRequestValue,
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/msp/tenants/{id}/invite", code: 200 })),
).annotate({
	identifier: "IntegrationsMspTenantsIdInvitePutRequest",
}) as any as S.Schema<IntegrationsMspTenantsIdInvitePutRequest>;

export interface IntegrationsMspTenantsIdInvitePutResponse {}
export const IntegrationsMspTenantsIdInvitePutResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IntegrationsMspTenantsIdInvitePutResponse",
}) as any as S.Schema<IntegrationsMspTenantsIdInvitePutResponse>;

/** MSP users Groups that can access the Tenant and Roles to assume */
export type IntegrationsMspTenantsIdPutRequestGroupsList = ReadonlyArray<TenantGroupResponse>;
export const IntegrationsMspTenantsIdPutRequestGroupsList = /*@__PURE__*/ S.Array(
	TenantGroupResponse,
) as any as S.Schema<IntegrationsMspTenantsIdPutRequestGroupsList>;

export interface IntegrationsMspTenantsIdPutRequest {
	/** The unique identifier of a tenant account */
	id: string;
	/** The name for the MSP tenant */
	name: string;
	/** MSP users Groups that can access the Tenant and Roles to assume */
	groups: IntegrationsMspTenantsIdPutRequestGroupsList;
}
export const IntegrationsMspTenantsIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
		name: S.String,
		groups: IntegrationsMspTenantsIdPutRequestGroupsList,
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/msp/tenants/{id}", code: 200 })),
).annotate({ identifier: "IntegrationsMspTenantsIdPutRequest" }) as any as S.Schema<IntegrationsMspTenantsIdPutRequest>;

export interface IntegrationsMspTenantsIdSubscriptionPostRequest {
	/** The unique identifier of a tenant account */
	id: string;
	/** The Price ID to change the subscription to. */
	priceID: string;
}
export const IntegrationsMspTenantsIdSubscriptionPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
		priceID: S.String,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/msp/tenants/{id}/subscription", code: 200 })),
).annotate({
	identifier: "IntegrationsMspTenantsIdSubscriptionPostRequest",
}) as any as S.Schema<IntegrationsMspTenantsIdSubscriptionPostRequest>;

export interface IntegrationsMspTenantsIdSubscriptionPostResponse {}
export const IntegrationsMspTenantsIdSubscriptionPostResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IntegrationsMspTenantsIdSubscriptionPostResponse",
}) as any as S.Schema<IntegrationsMspTenantsIdSubscriptionPostResponse>;

export interface IntegrationsMspTenantsIdUnlinkPostRequest {
	/** The unique identifier of a tenant account */
	id: string;
	/** The new owners user ID. */
	owner: string;
}
export const IntegrationsMspTenantsIdUnlinkPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
		owner: S.String,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/msp/tenants/{id}/unlink", code: 200 })),
).annotate({
	identifier: "IntegrationsMspTenantsIdUnlinkPostRequest",
}) as any as S.Schema<IntegrationsMspTenantsIdUnlinkPostRequest>;

export interface IntegrationsMspTenantsIdUnlinkPostResponse {}
export const IntegrationsMspTenantsIdUnlinkPostResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IntegrationsMspTenantsIdUnlinkPostResponse",
}) as any as S.Schema<IntegrationsMspTenantsIdUnlinkPostResponse>;

/** MSP users Groups that can access the Tenant and Roles to assume */
export type IntegrationsMspTenantsPostRequestGroupsList = ReadonlyArray<TenantGroupResponse>;
export const IntegrationsMspTenantsPostRequestGroupsList = /*@__PURE__*/ S.Array(
	TenantGroupResponse,
) as any as S.Schema<IntegrationsMspTenantsPostRequestGroupsList>;

export interface IntegrationsMspTenantsPostRequest {
	/** The name for the MSP tenant */
	name: string;
	/** The name for the MSP tenant */
	domain: string;
	/** MSP users Groups that can access the Tenant and Roles to assume */
	groups: IntegrationsMspTenantsPostRequestGroupsList;
}
export const IntegrationsMspTenantsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		domain: S.String,
		groups: IntegrationsMspTenantsPostRequestGroupsList,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/msp/tenants", code: 200 })),
).annotate({ identifier: "IntegrationsMspTenantsPostRequest" }) as any as S.Schema<IntegrationsMspTenantsPostRequest>;

export type IntegrationsMspTenantsGetError = BadRequest | Forbidden | NetbirdOpError;
/** Get MSP tenants */
export const integrationsMspTenantsGet: API.OperationMethod<
	IntegrationsMspTenantsGetRequest,
	IntegrationsMspTenantsGetResponse,
	IntegrationsMspTenantsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsGetRequest,
	output: IntegrationsMspTenantsGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsIdDnsPostError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Verify a tenant domain DNS challenge */
export const integrationsMspTenantsIdDnsPost: API.OperationMethod<
	IntegrationsMspTenantsIdDnsPostRequest,
	IntegrationsMspTenantsIdDnsPostResponse,
	IntegrationsMspTenantsIdDnsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsIdDnsPostRequest,
	output: IntegrationsMspTenantsIdDnsPostResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsIdInvitePostError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Invite existing account as a Tenant to the MSP account */
export const integrationsMspTenantsIdInvitePost: API.OperationMethod<
	IntegrationsMspTenantsIdInvitePostRequest,
	TenantResponse,
	IntegrationsMspTenantsIdInvitePostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsIdInvitePostRequest,
	output: TenantResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsIdInvitePutError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Response by the invited Tenant account owner */
export const integrationsMspTenantsIdInvitePut: API.OperationMethod<
	IntegrationsMspTenantsIdInvitePutRequest,
	IntegrationsMspTenantsIdInvitePutResponse,
	IntegrationsMspTenantsIdInvitePutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsIdInvitePutRequest,
	output: IntegrationsMspTenantsIdInvitePutResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsIdPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update MSP tenant */
export const integrationsMspTenantsIdPut: API.OperationMethod<
	IntegrationsMspTenantsIdPutRequest,
	TenantResponse,
	IntegrationsMspTenantsIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsIdPutRequest,
	output: TenantResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsIdSubscriptionPostError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Create subscription for Tenant */
export const integrationsMspTenantsIdSubscriptionPost: API.OperationMethod<
	IntegrationsMspTenantsIdSubscriptionPostRequest,
	IntegrationsMspTenantsIdSubscriptionPostResponse,
	IntegrationsMspTenantsIdSubscriptionPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsIdSubscriptionPostRequest,
	output: IntegrationsMspTenantsIdSubscriptionPostResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsIdUnlinkPostError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Unlink a tenant */
export const integrationsMspTenantsIdUnlinkPost: API.OperationMethod<
	IntegrationsMspTenantsIdUnlinkPostRequest,
	IntegrationsMspTenantsIdUnlinkPostResponse,
	IntegrationsMspTenantsIdUnlinkPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsIdUnlinkPostRequest,
	output: IntegrationsMspTenantsIdUnlinkPostResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsMspTenantsPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create MSP tenant */
export const integrationsMspTenantsPost: API.OperationMethod<
	IntegrationsMspTenantsPostRequest,
	TenantResponse,
	IntegrationsMspTenantsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsMspTenantsPostRequest,
	output: TenantResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
