import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsNotificationsChannelsChannelIdDeleteRequest {
	/** The unique identifier of the notification channel. */
	channelId: string;
}
export const IntegrationsNotificationsChannelsChannelIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		channelId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/notifications/channels/{channelId}", code: 200 })),
).annotate({
	identifier: "IntegrationsNotificationsChannelsChannelIdDeleteRequest",
}) as any as S.Schema<IntegrationsNotificationsChannelsChannelIdDeleteRequest>;

export type IntegrationsNotificationsChannelsChannelIdDeleteResponse = unknown;
export const IntegrationsNotificationsChannelsChannelIdDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsNotificationsChannelsChannelIdDeleteResponse",
}) as any as S.Schema<IntegrationsNotificationsChannelsChannelIdDeleteResponse>;

export interface IntegrationsNotificationsChannelsChannelIdGetRequest {
	/** The unique identifier of the notification channel. */
	channelId: string;
}
export const IntegrationsNotificationsChannelsChannelIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		channelId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/notifications/channels/{channelId}", code: 200 })),
).annotate({
	identifier: "IntegrationsNotificationsChannelsChannelIdGetRequest",
}) as any as S.Schema<IntegrationsNotificationsChannelsChannelIdGetRequest>;

/** The type of notification channel. */
export type NotificationChannelType = "email" | "webhook";
export const NotificationChannelType = /*@__PURE__*/ S.String;

/** List of email addresses to send notifications to. */
export type EmailTargetEmailsList = ReadonlyArray<string>;
export const EmailTargetEmailsList = /*@__PURE__*/ S.Array(S.String) as any as S.Schema<EmailTargetEmailsList>;

/** Target configuration for email notification channels. */
export interface EmailTarget {
	/** List of email addresses to send notifications to. */
	emails: EmailTargetEmailsList;
}
export const EmailTarget = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		emails: EmailTargetEmailsList,
	}),
).annotate({ identifier: "EmailTarget" }) as any as S.Schema<EmailTarget>;

/** Custom HTTP headers sent with each webhook request. Values are write-only; in GET responses all values are masked. */
export type WebhookTargetHeadersMap = { [key: string]: string };
export const WebhookTargetHeadersMap = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<WebhookTargetHeadersMap>;

/** Target configuration for webhook notification channels. */
export interface WebhookTarget {
	/** The webhook endpoint URL to send notifications to. */
	url: string;
	/** Custom HTTP headers sent with each webhook request. Values are write-only; in GET responses all values are masked. */
	headers?: WebhookTargetHeadersMap;
}
export const WebhookTarget = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		url: S.String,
		headers: S.optional(WebhookTargetHeadersMap),
	}),
).annotate({ identifier: "WebhookTarget" }) as any as S.Schema<WebhookTarget>;

/** Channel-specific target configuration. The shape depends on the `type` field: - `email`: an `EmailTarget` object - `webhook`: a `WebhookTarget` object */
export type NotificationChannelResponseTarget = EmailTarget | WebhookTarget;
export const NotificationChannelResponseTarget =
	/*@__PURE__*/ S.Unknown as any as S.Schema<NotificationChannelResponseTarget>;

/** List of activity event type codes this channel subscribes to. */
export type NotificationChannelResponseEventTypesList = ReadonlyArray<string>;
export const NotificationChannelResponseEventTypesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<NotificationChannelResponseEventTypesList>;

/** A notification channel configuration. */
export interface NotificationChannelResponse {
	/** Unique identifier of the notification channel. */
	id: string;
	type: NotificationChannelType;
	/** Channel-specific target configuration. The shape depends on the `type` field: - `email`: an `EmailTarget` object - `webhook`: a `WebhookTarget` object */
	target?: NotificationChannelResponseTarget;
	/** List of activity event type codes this channel subscribes to. */
	event_types: NotificationChannelResponseEventTypesList;
	/** Whether this notification channel is active. */
	enabled: boolean;
}
export const NotificationChannelResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: NotificationChannelType,
		target: S.optional(NotificationChannelResponseTarget),
		event_types: NotificationChannelResponseEventTypesList,
		enabled: S.Boolean,
	}),
).annotate({ identifier: "NotificationChannelResponse" }) as any as S.Schema<NotificationChannelResponse>;

/** Channel-specific target configuration. The shape depends on the `type` field: - `email`: requires an `EmailTarget` object - `webhook`: requires a `WebhookTarget` object */
export type IntegrationsNotificationsChannelsChannelIdPutRequestTarget = EmailTarget | WebhookTarget;
export const IntegrationsNotificationsChannelsChannelIdPutRequestTarget =
	/*@__PURE__*/ S.Unknown as any as S.Schema<IntegrationsNotificationsChannelsChannelIdPutRequestTarget>;

/** List of activity event type codes this channel subscribes to. */
export type IntegrationsNotificationsChannelsChannelIdPutRequestEventTypesList = ReadonlyArray<string>;
export const IntegrationsNotificationsChannelsChannelIdPutRequestEventTypesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsNotificationsChannelsChannelIdPutRequestEventTypesList>;

export interface IntegrationsNotificationsChannelsChannelIdPutRequest {
	/** The unique identifier of the notification channel. */
	channelId: string;
	type: NotificationChannelType;
	/** Channel-specific target configuration. The shape depends on the `type` field: - `email`: requires an `EmailTarget` object - `webhook`: requires a `WebhookTarget` object */
	target?: IntegrationsNotificationsChannelsChannelIdPutRequestTarget;
	/** List of activity event type codes this channel subscribes to. */
	event_types: IntegrationsNotificationsChannelsChannelIdPutRequestEventTypesList;
	/** Whether this notification channel is active. */
	enabled: boolean;
}
export const IntegrationsNotificationsChannelsChannelIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		channelId: S.String.pipe(T.Label()),
		type: NotificationChannelType,
		target: S.optional(IntegrationsNotificationsChannelsChannelIdPutRequestTarget),
		event_types: IntegrationsNotificationsChannelsChannelIdPutRequestEventTypesList,
		enabled: S.Boolean,
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/notifications/channels/{channelId}", code: 200 })),
).annotate({
	identifier: "IntegrationsNotificationsChannelsChannelIdPutRequest",
}) as any as S.Schema<IntegrationsNotificationsChannelsChannelIdPutRequest>;

export interface IntegrationsNotificationsChannelsGetRequest {}
export const IntegrationsNotificationsChannelsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/notifications/channels", code: 200 })),
).annotate({
	identifier: "IntegrationsNotificationsChannelsGetRequest",
}) as any as S.Schema<IntegrationsNotificationsChannelsGetRequest>;

export type IntegrationsNotificationsChannelsGetResponseBodyList = ReadonlyArray<NotificationChannelResponse>;
export const IntegrationsNotificationsChannelsGetResponseBodyList = /*@__PURE__*/ S.Array(
	NotificationChannelResponse,
) as any as S.Schema<IntegrationsNotificationsChannelsGetResponseBodyList>;

export type IntegrationsNotificationsChannelsGetResponse = IntegrationsNotificationsChannelsGetResponseBodyList;
export const IntegrationsNotificationsChannelsGetResponse = /*@__PURE__*/ S.suspend(() =>
	IntegrationsNotificationsChannelsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsNotificationsChannelsGetResponse",
}) as any as S.Schema<IntegrationsNotificationsChannelsGetResponse>;

/** Channel-specific target configuration. The shape depends on the `type` field: - `email`: requires an `EmailTarget` object - `webhook`: requires a `WebhookTarget` object */
export type IntegrationsNotificationsChannelsPostRequestTarget = EmailTarget | WebhookTarget;
export const IntegrationsNotificationsChannelsPostRequestTarget =
	/*@__PURE__*/ S.Unknown as any as S.Schema<IntegrationsNotificationsChannelsPostRequestTarget>;

/** List of activity event type codes this channel subscribes to. */
export type IntegrationsNotificationsChannelsPostRequestEventTypesList = ReadonlyArray<string>;
export const IntegrationsNotificationsChannelsPostRequestEventTypesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsNotificationsChannelsPostRequestEventTypesList>;

export interface IntegrationsNotificationsChannelsPostRequest {
	type: NotificationChannelType;
	/** Channel-specific target configuration. The shape depends on the `type` field: - `email`: requires an `EmailTarget` object - `webhook`: requires a `WebhookTarget` object */
	target?: IntegrationsNotificationsChannelsPostRequestTarget;
	/** List of activity event type codes this channel subscribes to. */
	event_types: IntegrationsNotificationsChannelsPostRequestEventTypesList;
	/** Whether this notification channel is active. */
	enabled: boolean;
}
export const IntegrationsNotificationsChannelsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		type: NotificationChannelType,
		target: S.optional(IntegrationsNotificationsChannelsPostRequestTarget),
		event_types: IntegrationsNotificationsChannelsPostRequestEventTypesList,
		enabled: S.Boolean,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/notifications/channels", code: 200 })),
).annotate({
	identifier: "IntegrationsNotificationsChannelsPostRequest",
}) as any as S.Schema<IntegrationsNotificationsChannelsPostRequest>;

export interface IntegrationsNotificationsTypesGetRequest {}
export const IntegrationsNotificationsTypesGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/notifications/types", code: 200 })),
).annotate({
	identifier: "IntegrationsNotificationsTypesGetRequest",
}) as any as S.Schema<IntegrationsNotificationsTypesGetRequest>;

/** A map of event type codes to their human-readable descriptions. */
export type NotificationTypeEntry = { [key: string]: string };
export const NotificationTypeEntry = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<NotificationTypeEntry>;

export type IntegrationsNotificationsTypesGetResponse = NotificationTypeEntry;
export const IntegrationsNotificationsTypesGetResponse = /*@__PURE__*/ S.suspend(() =>
	NotificationTypeEntry.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsNotificationsTypesGetResponse",
}) as any as S.Schema<IntegrationsNotificationsTypesGetResponse>;

export type IntegrationsNotificationsChannelsChannelIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete Notification Channel Deletes a notification channel by its ID. */
export const integrationsNotificationsChannelsChannelIdDelete: API.OperationMethod<
	IntegrationsNotificationsChannelsChannelIdDeleteRequest,
	IntegrationsNotificationsChannelsChannelIdDeleteResponse,
	IntegrationsNotificationsChannelsChannelIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsNotificationsChannelsChannelIdDeleteRequest,
	output: IntegrationsNotificationsChannelsChannelIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsNotificationsChannelsChannelIdGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Get Notification Channel Retrieves a specific notification channel by its ID. */
export const integrationsNotificationsChannelsChannelIdGet: API.OperationMethod<
	IntegrationsNotificationsChannelsChannelIdGetRequest,
	NotificationChannelResponse,
	IntegrationsNotificationsChannelsChannelIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsNotificationsChannelsChannelIdGetRequest,
	output: NotificationChannelResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsNotificationsChannelsChannelIdPutError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Update Notification Channel Updates an existing notification channel. */
export const integrationsNotificationsChannelsChannelIdPut: API.OperationMethod<
	IntegrationsNotificationsChannelsChannelIdPutRequest,
	NotificationChannelResponse,
	IntegrationsNotificationsChannelsChannelIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsNotificationsChannelsChannelIdPutRequest,
	output: NotificationChannelResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsNotificationsChannelsGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** List Notification Channels Retrieves all notification channels configured for the authenticated account. */
export const integrationsNotificationsChannelsGet: API.OperationMethod<
	IntegrationsNotificationsChannelsGetRequest,
	IntegrationsNotificationsChannelsGetResponse,
	IntegrationsNotificationsChannelsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsNotificationsChannelsGetRequest,
	output: IntegrationsNotificationsChannelsGetResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsNotificationsChannelsPostError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Create Notification Channel Creates a new notification channel for the authenticated account. Supported channel types are `email` and `webhook`. */
export const integrationsNotificationsChannelsPost: API.OperationMethod<
	IntegrationsNotificationsChannelsPostRequest,
	NotificationChannelResponse,
	IntegrationsNotificationsChannelsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsNotificationsChannelsPostRequest,
	output: NotificationChannelResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsNotificationsTypesGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** List Notification Event Types Returns a map of all supported activity event type codes to their human-readable descriptions. Use these codes when configuring `event_types` on notification channels. */
export const integrationsNotificationsTypesGet: API.OperationMethod<
	IntegrationsNotificationsTypesGetRequest,
	IntegrationsNotificationsTypesGetResponse,
	IntegrationsNotificationsTypesGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsNotificationsTypesGetRequest,
	output: IntegrationsNotificationsTypesGetResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
