import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface ReverseProxiesProxyTokensGetRequest {}
export const ReverseProxiesProxyTokensGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/reverse-proxies/proxy-tokens", code: 200 })),
).annotate({
	identifier: "ReverseProxiesProxyTokensGetRequest",
}) as any as S.Schema<ReverseProxiesProxyTokensGetRequest>;

export interface ProxyToken {
	id: string;
	name: string;
	expires_at?: string;
	created_at: string;
	last_used?: string;
	revoked: boolean;
}
export const ProxyToken = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		expires_at: S.optional(S.String),
		created_at: S.String,
		last_used: S.optional(S.String),
		revoked: S.Boolean,
	}),
).annotate({ identifier: "ProxyToken" }) as any as S.Schema<ProxyToken>;

export type ReverseProxiesProxyTokensGetResponseBodyList = ReadonlyArray<ProxyToken>;
export const ReverseProxiesProxyTokensGetResponseBodyList = /*@__PURE__*/ S.Array(
	ProxyToken,
) as any as S.Schema<ReverseProxiesProxyTokensGetResponseBodyList>;

export type ReverseProxiesProxyTokensGetResponse = ReverseProxiesProxyTokensGetResponseBodyList;
export const ReverseProxiesProxyTokensGetResponse = /*@__PURE__*/ S.suspend(() =>
	ReverseProxiesProxyTokensGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "ReverseProxiesProxyTokensGetResponse",
}) as any as S.Schema<ReverseProxiesProxyTokensGetResponse>;

export interface ReverseProxiesProxyTokensPostRequest {
	/** Human-readable token name */
	name: string;
	/** Token expiration in seconds (0 = never expires) */
	expires_in?: number;
}
export const ReverseProxiesProxyTokensPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		expires_in: S.optional(S.Number),
	}).pipe(T.Http({ method: "POST", uri: "/api/reverse-proxies/proxy-tokens", code: 200 })),
).annotate({
	identifier: "ReverseProxiesProxyTokensPostRequest",
}) as any as S.Schema<ReverseProxiesProxyTokensPostRequest>;

export interface ReverseProxiesProxyTokensPostResponse {
	id: string;
	name: string;
	expires_at?: string;
	created_at: string;
	last_used?: string;
	revoked: boolean;
	/** The plain text token (shown only once) */
	plain_token: string;
}
export const ReverseProxiesProxyTokensPostResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		expires_at: S.optional(S.String),
		created_at: S.String,
		last_used: S.optional(S.String),
		revoked: S.Boolean,
		plain_token: S.String,
	}),
).annotate({
	identifier: "ReverseProxiesProxyTokensPostResponse",
}) as any as S.Schema<ReverseProxiesProxyTokensPostResponse>;

export interface ReverseProxiesProxyTokensTokenIdDeleteRequest {
	/** The unique identifier of the proxy token */
	tokenId: string;
}
export const ReverseProxiesProxyTokensTokenIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		tokenId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/reverse-proxies/proxy-tokens/{tokenId}", code: 200 })),
).annotate({
	identifier: "ReverseProxiesProxyTokensTokenIdDeleteRequest",
}) as any as S.Schema<ReverseProxiesProxyTokensTokenIdDeleteRequest>;

export interface ReverseProxiesProxyTokensTokenIdDeleteResponse {}
export const ReverseProxiesProxyTokensTokenIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "ReverseProxiesProxyTokensTokenIdDeleteResponse",
}) as any as S.Schema<ReverseProxiesProxyTokensTokenIdDeleteResponse>;

export type ReverseProxiesProxyTokensGetError = Forbidden | NetbirdOpError;
/** List Proxy Tokens Returns all proxy access tokens for the account */
export const reverseProxiesProxyTokensGet: API.OperationMethod<
	ReverseProxiesProxyTokensGetRequest,
	ReverseProxiesProxyTokensGetResponse,
	ReverseProxiesProxyTokensGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesProxyTokensGetRequest,
	output: ReverseProxiesProxyTokensGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesProxyTokensPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create a Proxy Token Generate an account-scoped proxy access token for self-hosted proxy registration */
export const reverseProxiesProxyTokensPost: API.OperationMethod<
	ReverseProxiesProxyTokensPostRequest,
	ReverseProxiesProxyTokensPostResponse,
	ReverseProxiesProxyTokensPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesProxyTokensPostRequest,
	output: ReverseProxiesProxyTokensPostResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesProxyTokensTokenIdDeleteError = Forbidden | NotFound | NetbirdOpError;
/** Revoke a Proxy Token Revoke an account-scoped proxy access token */
export const reverseProxiesProxyTokensTokenIdDelete: API.OperationMethod<
	ReverseProxiesProxyTokensTokenIdDeleteRequest,
	ReverseProxiesProxyTokensTokenIdDeleteResponse,
	ReverseProxiesProxyTokensTokenIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesProxyTokensTokenIdDeleteRequest,
	output: ReverseProxiesProxyTokensTokenIdDeleteResponse,
	errors: [Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
