import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Conflict
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withConflictError),
		[{ status: 409 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface ReverseProxiesClustersClusterAddressDeleteRequest {
	/** The address of the proxy cluster */
	clusterAddress: string;
}
export const ReverseProxiesClustersClusterAddressDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		clusterAddress: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/reverse-proxies/clusters/{clusterAddress}", code: 200 })),
).annotate({
	identifier: "ReverseProxiesClustersClusterAddressDeleteRequest",
}) as any as S.Schema<ReverseProxiesClustersClusterAddressDeleteRequest>;

export interface ReverseProxiesClustersClusterAddressDeleteResponse {}
export const ReverseProxiesClustersClusterAddressDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "ReverseProxiesClustersClusterAddressDeleteResponse",
}) as any as S.Schema<ReverseProxiesClustersClusterAddressDeleteResponse>;

export interface ReverseProxiesClustersGetRequest {}
export const ReverseProxiesClustersGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/reverse-proxies/clusters", code: 200 })),
).annotate({ identifier: "ReverseProxiesClustersGetRequest" }) as any as S.Schema<ReverseProxiesClustersGetRequest>;

/** Source of the proxy cluster. `account` clusters are owned and operated by the account (BYOP); `shared` clusters are operated by NetBird and shared across accounts. */
export type ProxyClusterType = "account" | "shared";
export const ProxyClusterType = /*@__PURE__*/ S.String;

/** A proxy cluster represents a group of proxy nodes serving the same address */
export interface ProxyCluster {
	/** Unique identifier of a proxy in this cluster */
	id: string;
	/** Cluster address used for CNAME targets */
	address: string;
	type: ProxyClusterType;
	/** Whether at least one proxy in the cluster has heartbeated within the active window */
	online: boolean;
	/** Number of proxy nodes currently connected (heartbeat within the active window) */
	connected_proxies: number;
	/** Whether the cluster supports binding arbitrary TCP/UDP ports */
	supports_custom_ports?: boolean;
	/** Whether services on this cluster must include a subdomain label */
	require_subdomain?: boolean;
	/** Whether all active proxies in the cluster have CrowdSec configured */
	supports_crowdsec?: boolean;
	/** True when at least one connected proxy in this cluster is running embedded in a netbird client (`netbird proxy`) and serving over a WireGuard tunnel. Lets the dashboard distinguish per-peer / private clusters from centralised ones. */
	private?: boolean;
}
export const ProxyCluster = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		address: S.String,
		type: ProxyClusterType,
		online: S.Boolean,
		connected_proxies: S.Number,
		supports_custom_ports: S.optional(S.Boolean),
		require_subdomain: S.optional(S.Boolean),
		supports_crowdsec: S.optional(S.Boolean),
		private: S.optional(S.Boolean),
	}),
).annotate({ identifier: "ProxyCluster" }) as any as S.Schema<ProxyCluster>;

export type ReverseProxiesClustersGetResponseBodyList = ReadonlyArray<ProxyCluster>;
export const ReverseProxiesClustersGetResponseBodyList = /*@__PURE__*/ S.Array(
	ProxyCluster,
) as any as S.Schema<ReverseProxiesClustersGetResponseBodyList>;

export type ReverseProxiesClustersGetResponse = ReverseProxiesClustersGetResponseBodyList;
export const ReverseProxiesClustersGetResponse = /*@__PURE__*/ S.suspend(() =>
	ReverseProxiesClustersGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "ReverseProxiesClustersGetResponse" }) as any as S.Schema<ReverseProxiesClustersGetResponse>;

export interface ReverseProxiesDomainsDomainIdDeleteRequest {
	/** The custom domain ID */
	domainId: string;
}
export const ReverseProxiesDomainsDomainIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		domainId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/reverse-proxies/domains/{domainId}", code: 200 })),
).annotate({
	identifier: "ReverseProxiesDomainsDomainIdDeleteRequest",
}) as any as S.Schema<ReverseProxiesDomainsDomainIdDeleteRequest>;

export interface ReverseProxiesDomainsDomainIdDeleteResponse {}
export const ReverseProxiesDomainsDomainIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "ReverseProxiesDomainsDomainIdDeleteResponse",
}) as any as S.Schema<ReverseProxiesDomainsDomainIdDeleteResponse>;

export interface ReverseProxiesDomainsDomainIdValidateGetRequest {
	/** The custom domain ID */
	domainId: string;
}
export const ReverseProxiesDomainsDomainIdValidateGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		domainId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/reverse-proxies/domains/{domainId}/validate", code: 200 })),
).annotate({
	identifier: "ReverseProxiesDomainsDomainIdValidateGetRequest",
}) as any as S.Schema<ReverseProxiesDomainsDomainIdValidateGetRequest>;

export interface ReverseProxiesDomainsDomainIdValidateGetResponse {}
export const ReverseProxiesDomainsDomainIdValidateGetResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "ReverseProxiesDomainsDomainIdValidateGetResponse",
}) as any as S.Schema<ReverseProxiesDomainsDomainIdValidateGetResponse>;

export interface ReverseProxiesDomainsGetRequest {}
export const ReverseProxiesDomainsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/reverse-proxies/domains", code: 200 })),
).annotate({ identifier: "ReverseProxiesDomainsGetRequest" }) as any as S.Schema<ReverseProxiesDomainsGetRequest>;

/** Type of Reverse Proxy Domain */
export type ReverseProxyDomainType = "free" | "custom";
export const ReverseProxyDomainType = /*@__PURE__*/ S.String;

export interface ReverseProxyDomain {
	/** Domain ID */
	id: string;
	/** Domain name */
	domain: string;
	/** Whether the domain has been validated */
	validated: boolean;
	type: ReverseProxyDomainType;
	/** The proxy cluster this domain is validated against (only for custom domains) */
	target_cluster?: string;
	/** Whether the cluster supports binding arbitrary TCP/UDP ports */
	supports_custom_ports?: boolean;
	/** Whether a subdomain label is required in front of this domain. When true, the domain cannot be used bare. */
	require_subdomain?: boolean;
	/** Whether the proxy cluster has CrowdSec configured */
	supports_crowdsec?: boolean;
	/** Whether the proxy cluster supports private (NetBird-only) services. True when at least one connected proxy in the cluster runs embedded in a netbird client. */
	supports_private?: boolean;
}
export const ReverseProxyDomain = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		domain: S.String,
		validated: S.Boolean,
		type: ReverseProxyDomainType,
		target_cluster: S.optional(S.String),
		supports_custom_ports: S.optional(S.Boolean),
		require_subdomain: S.optional(S.Boolean),
		supports_crowdsec: S.optional(S.Boolean),
		supports_private: S.optional(S.Boolean),
	}),
).annotate({ identifier: "ReverseProxyDomain" }) as any as S.Schema<ReverseProxyDomain>;

export type ReverseProxiesDomainsGetResponseBodyList = ReadonlyArray<ReverseProxyDomain>;
export const ReverseProxiesDomainsGetResponseBodyList = /*@__PURE__*/ S.Array(
	ReverseProxyDomain,
) as any as S.Schema<ReverseProxiesDomainsGetResponseBodyList>;

export type ReverseProxiesDomainsGetResponse = ReverseProxiesDomainsGetResponseBodyList;
export const ReverseProxiesDomainsGetResponse = /*@__PURE__*/ S.suspend(() =>
	ReverseProxiesDomainsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "ReverseProxiesDomainsGetResponse" }) as any as S.Schema<ReverseProxiesDomainsGetResponse>;

export interface ReverseProxiesDomainsPostRequest {
	/** Domain name */
	domain: string;
	/** The proxy cluster this domain should be validated against */
	target_cluster: string;
}
export const ReverseProxiesDomainsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		domain: S.String,
		target_cluster: S.String,
	}).pipe(T.Http({ method: "POST", uri: "/api/reverse-proxies/domains", code: 200 })),
).annotate({ identifier: "ReverseProxiesDomainsPostRequest" }) as any as S.Schema<ReverseProxiesDomainsPostRequest>;

/** Service mode. "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough. */
export type ServiceMode = "http" | "tcp" | "udp" | "tls";
export const ServiceMode = /*@__PURE__*/ S.String;

/** Target type */
export type ServiceTargetTargetType = "peer" | "host" | "domain" | "subnet" | "cluster";
export const ServiceTargetTargetType = /*@__PURE__*/ S.String;

/** Protocol to use when connecting to the backend */
export type ServiceTargetProtocol = "http" | "https" | "tcp" | "udp";
export const ServiceTargetProtocol = /*@__PURE__*/ S.String;

/** Controls how the request path is rewritten before forwarding to the backend. Default strips the matched prefix. "preserve" keeps the full original request path. */
export type ServiceTargetOptionsPathRewrite = "preserve";
export const ServiceTargetOptionsPathRewrite = /*@__PURE__*/ S.String;

/** Extra headers sent to the backend. Hop-by-hop and proxy-managed headers (Host, Connection, Transfer-Encoding, etc.) are rejected. */
export type ServiceTargetOptionsCustomHeadersMap = { [key: string]: string };
export const ServiceTargetOptionsCustomHeadersMap = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<ServiceTargetOptionsCustomHeadersMap>;

export interface ServiceTargetOptions {
	/** Skip TLS certificate verification for this backend */
	skip_tls_verify?: boolean;
	/** Per-target response timeout as a Go duration string (e.g. "30s", "2m") */
	request_timeout?: string;
	/** Controls how the request path is rewritten before forwarding to the backend. Default strips the matched prefix. "preserve" keeps the full original request path. */
	path_rewrite?: ServiceTargetOptionsPathRewrite;
	/** Extra headers sent to the backend. Hop-by-hop and proxy-managed headers (Host, Connection, Transfer-Encoding, etc.) are rejected. */
	custom_headers?: ServiceTargetOptionsCustomHeadersMap;
	/** Send PROXY Protocol v2 header to this backend (TCP/TLS only) */
	proxy_protocol?: boolean;
	/** Idle timeout before a UDP session is reaped, as a Go duration string (e.g. "30s", "2m"). */
	session_idle_timeout?: string;
	/** When true, the proxy dials this target via the host's network stack instead of through its embedded NetBird client. Use for upstreams reachable without WireGuard (public APIs, LAN services, localhost sidecars). */
	direct_upstream?: boolean;
}
export const ServiceTargetOptions = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		skip_tls_verify: S.optional(S.Boolean),
		request_timeout: S.optional(S.String),
		path_rewrite: S.optional(ServiceTargetOptionsPathRewrite),
		custom_headers: S.optional(ServiceTargetOptionsCustomHeadersMap),
		proxy_protocol: S.optional(S.Boolean),
		session_idle_timeout: S.optional(S.String),
		direct_upstream: S.optional(S.Boolean),
	}),
).annotate({ identifier: "ServiceTargetOptions" }) as any as S.Schema<ServiceTargetOptions>;

export interface ServiceTarget {
	/** Target ID */
	target_id: string;
	/** Target type */
	target_type: ServiceTargetTargetType;
	/** URL path prefix for this target (HTTP only) */
	path?: string;
	/** Protocol to use when connecting to the backend */
	protocol: ServiceTargetProtocol;
	/** Backend ip or domain for this target */
	host?: string;
	/** Backend port for this target */
	port: number;
	/** Whether this target is enabled */
	enabled: boolean;
	options?: ServiceTargetOptions;
}
export const ServiceTarget = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		target_id: S.String,
		target_type: ServiceTargetTargetType,
		path: S.optional(S.String),
		protocol: ServiceTargetProtocol,
		host: S.optional(S.String),
		port: S.Number,
		enabled: S.Boolean,
		options: S.optional(ServiceTargetOptions),
	}),
).annotate({ identifier: "ServiceTarget" }) as any as S.Schema<ServiceTarget>;

/** List of target backends for this service */
export type ServiceTargetsList = ReadonlyArray<ServiceTarget>;
export const ServiceTargetsList = /*@__PURE__*/ S.Array(ServiceTarget) as any as S.Schema<ServiceTargetsList>;

export interface PasswordAuthConfig {
	/** Whether password auth is enabled */
	enabled: boolean;
	/** Auth password */
	password: string | Redacted.Redacted<string>;
}
export const PasswordAuthConfig = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		password: S.String.pipe(T.SensitiveValue({})),
	}),
).annotate({ identifier: "PasswordAuthConfig" }) as any as S.Schema<PasswordAuthConfig>;

export interface PINAuthConfig {
	/** Whether PIN auth is enabled */
	enabled: boolean;
	/** PIN value */
	pin: string;
}
export const PINAuthConfig = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		pin: S.String,
	}),
).annotate({ identifier: "PINAuthConfig" }) as any as S.Schema<PINAuthConfig>;

/** List of group IDs that can use bearer auth */
export type BearerAuthConfigDistributionGroupsList = ReadonlyArray<string>;
export const BearerAuthConfigDistributionGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<BearerAuthConfigDistributionGroupsList>;

export interface BearerAuthConfig {
	/** Whether bearer auth is enabled */
	enabled: boolean;
	/** List of group IDs that can use bearer auth */
	distribution_groups?: BearerAuthConfigDistributionGroupsList | null;
}
export const BearerAuthConfig = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		distribution_groups: S.optional(S.NullOr(BearerAuthConfigDistributionGroupsList)),
	}),
).annotate({ identifier: "BearerAuthConfig" }) as any as S.Schema<BearerAuthConfig>;

export interface LinkAuthConfig {
	/** Whether link auth is enabled */
	enabled: boolean;
}
export const LinkAuthConfig = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
	}),
).annotate({ identifier: "LinkAuthConfig" }) as any as S.Schema<LinkAuthConfig>;

/** Static header-value authentication. The proxy checks that the named header matches the configured value. */
export interface HeaderAuthConfig {
	/** Whether header auth is enabled */
	enabled: boolean;
	/** HTTP header name to check (e.g. "Authorization", "X-API-Key") */
	header: string;
	/** Expected header value. For Basic auth use "Basic base64(user:pass)". For Bearer use "Bearer token". Cleared in responses. */
	value: string;
}
export const HeaderAuthConfig = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		header: S.String,
		value: S.String,
	}),
).annotate({ identifier: "HeaderAuthConfig" }) as any as S.Schema<HeaderAuthConfig>;

export type ServiceAuthConfigHeaderAuthsList = ReadonlyArray<HeaderAuthConfig>;
export const ServiceAuthConfigHeaderAuthsList = /*@__PURE__*/ S.Array(
	HeaderAuthConfig,
) as any as S.Schema<ServiceAuthConfigHeaderAuthsList>;

export interface ServiceAuthConfig {
	password_auth?: PasswordAuthConfig;
	pin_auth?: PINAuthConfig;
	bearer_auth?: BearerAuthConfig;
	link_auth?: LinkAuthConfig;
	header_auths?: ServiceAuthConfigHeaderAuthsList;
}
export const ServiceAuthConfig = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		password_auth: S.optional(PasswordAuthConfig),
		pin_auth: S.optional(PINAuthConfig),
		bearer_auth: S.optional(BearerAuthConfig),
		link_auth: S.optional(LinkAuthConfig),
		header_auths: S.optional(ServiceAuthConfigHeaderAuthsList),
	}),
).annotate({ identifier: "ServiceAuthConfig" }) as any as S.Schema<ServiceAuthConfig>;

/** CIDR allowlist. If non-empty, only IPs matching these CIDRs are allowed. */
export type AccessRestrictionsAllowedCidrsList = ReadonlyArray<string>;
export const AccessRestrictionsAllowedCidrsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AccessRestrictionsAllowedCidrsList>;

/** CIDR blocklist. Connections from these CIDRs are rejected. Evaluated after allowed_cidrs. */
export type AccessRestrictionsBlockedCidrsList = ReadonlyArray<string>;
export const AccessRestrictionsBlockedCidrsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AccessRestrictionsBlockedCidrsList>;

/** ISO 3166-1 alpha-2 country codes to allow. If non-empty, only these countries are permitted. */
export type AccessRestrictionsAllowedCountriesList = ReadonlyArray<string>;
export const AccessRestrictionsAllowedCountriesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AccessRestrictionsAllowedCountriesList>;

/** ISO 3166-1 alpha-2 country codes to block. */
export type AccessRestrictionsBlockedCountriesList = ReadonlyArray<string>;
export const AccessRestrictionsBlockedCountriesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AccessRestrictionsBlockedCountriesList>;

/** CrowdSec IP reputation mode. Only available when the proxy cluster supports CrowdSec. */
export type AccessRestrictionsCrowdsecMode = "off" | "enforce" | "observe";
export const AccessRestrictionsCrowdsecMode = /*@__PURE__*/ S.String;

/** Connection-level access restrictions based on IP address or geography. Applies to both HTTP and L4 services. */
export interface AccessRestrictions {
	/** CIDR allowlist. If non-empty, only IPs matching these CIDRs are allowed. */
	allowed_cidrs?: AccessRestrictionsAllowedCidrsList;
	/** CIDR blocklist. Connections from these CIDRs are rejected. Evaluated after allowed_cidrs. */
	blocked_cidrs?: AccessRestrictionsBlockedCidrsList;
	/** ISO 3166-1 alpha-2 country codes to allow. If non-empty, only these countries are permitted. */
	allowed_countries?: AccessRestrictionsAllowedCountriesList;
	/** ISO 3166-1 alpha-2 country codes to block. */
	blocked_countries?: AccessRestrictionsBlockedCountriesList;
	/** CrowdSec IP reputation mode. Only available when the proxy cluster supports CrowdSec. */
	crowdsec_mode?: AccessRestrictionsCrowdsecMode;
}
export const AccessRestrictions = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		allowed_cidrs: S.optional(AccessRestrictionsAllowedCidrsList),
		blocked_cidrs: S.optional(AccessRestrictionsBlockedCidrsList),
		allowed_countries: S.optional(AccessRestrictionsAllowedCountriesList),
		blocked_countries: S.optional(AccessRestrictionsBlockedCountriesList),
		crowdsec_mode: S.optional(AccessRestrictionsCrowdsecMode),
	}),
).annotate({ identifier: "AccessRestrictions" }) as any as S.Schema<AccessRestrictions>;

/** Current status of the service */
export type ServiceMetaStatus =
	| "pending"
	| "active"
	| "tunnel_not_created"
	| "certificate_pending"
	| "certificate_failed"
	| "error";
export const ServiceMetaStatus = /*@__PURE__*/ S.String;

export interface ServiceMeta {
	/** Timestamp when the service was created */
	created_at: string;
	/** Timestamp when the certificate was issued (empty if not yet issued) */
	certificate_issued_at?: string;
	/** Current status of the service */
	status: ServiceMetaStatus;
}
export const ServiceMeta = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		created_at: S.String,
		certificate_issued_at: S.optional(S.String),
		status: ServiceMetaStatus,
	}),
).annotate({ identifier: "ServiceMeta" }) as any as S.Schema<ServiceMeta>;

/** NetBird group IDs whose peers may reach this private service over the tunnel. Required when private=true; ignored otherwise. Mutually exclusive with bearer auth (SSO). */
export type ServiceAccessGroupsList = ReadonlyArray<string>;
export const ServiceAccessGroupsList = /*@__PURE__*/ S.Array(S.String) as any as S.Schema<ServiceAccessGroupsList>;

export interface Service {
	/** Service ID */
	id: string;
	/** Service name */
	name: string;
	/** Domain for the service */
	domain: string;
	/** Service mode. "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough. */
	mode?: ServiceMode;
	/** Port the proxy listens on (L4/TLS only) */
	listen_port?: number;
	/** Whether the listen port was auto-assigned */
	port_auto_assigned?: boolean;
	/** The proxy cluster handling this service (derived from domain) */
	proxy_cluster?: string;
	/** List of target backends for this service */
	targets: ServiceTargetsList;
	/** Whether the service is enabled */
	enabled: boolean;
	/** Whether the service has been terminated. Terminated services cannot be updated. Services that violate the Terms of Service will be terminated. */
	terminated?: boolean;
	/** When true, the original client Host header is passed through to the backend instead of being rewritten to the backend's address */
	pass_host_header?: boolean;
	/** When true, Location headers in backend responses are rewritten to replace the backend address with the public-facing domain */
	rewrite_redirects?: boolean;
	auth: ServiceAuthConfig;
	access_restrictions?: AccessRestrictions;
	meta: ServiceMeta;
	/** When true, the service is NetBird-only — its target points at a proxy cluster, inbound peers authenticate via their WireGuard tunnel identity (no OIDC), and an ACL policy is auto-generated from access_groups to the cluster's proxy-peer group. Requires mode=http. */
	private?: boolean;
	/** NetBird group IDs whose peers may reach this private service over the tunnel. Required when private=true; ignored otherwise. Mutually exclusive with bearer auth (SSO). */
	access_groups?: ServiceAccessGroupsList;
}
export const Service = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		domain: S.String,
		mode: S.optional(ServiceMode),
		listen_port: S.optional(S.Number),
		port_auto_assigned: S.optional(S.Boolean),
		proxy_cluster: S.optional(S.String),
		targets: ServiceTargetsList,
		enabled: S.Boolean,
		terminated: S.optional(S.Boolean),
		pass_host_header: S.optional(S.Boolean),
		rewrite_redirects: S.optional(S.Boolean),
		auth: ServiceAuthConfig,
		access_restrictions: S.optional(AccessRestrictions),
		meta: ServiceMeta,
		private: S.optional(S.Boolean),
		access_groups: S.optional(ServiceAccessGroupsList),
	}),
).annotate({ identifier: "Service" }) as any as S.Schema<Service>;

export interface ReverseProxiesServicesGetRequest {}
export const ReverseProxiesServicesGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/reverse-proxies/services", code: 200 })),
).annotate({ identifier: "ReverseProxiesServicesGetRequest" }) as any as S.Schema<ReverseProxiesServicesGetRequest>;

export type ReverseProxiesServicesGetResponseBodyList = ReadonlyArray<Service>;
export const ReverseProxiesServicesGetResponseBodyList = /*@__PURE__*/ S.Array(
	Service,
) as any as S.Schema<ReverseProxiesServicesGetResponseBodyList>;

export type ReverseProxiesServicesGetResponse = ReverseProxiesServicesGetResponseBodyList;
export const ReverseProxiesServicesGetResponse = /*@__PURE__*/ S.suspend(() =>
	ReverseProxiesServicesGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "ReverseProxiesServicesGetResponse" }) as any as S.Schema<ReverseProxiesServicesGetResponse>;

/** Service mode. "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough. */
export type ReverseProxiesServicesPostRequestMode = "http" | "tcp" | "udp" | "tls";
export const ReverseProxiesServicesPostRequestMode = /*@__PURE__*/ S.String;

/** List of target backends for this service */
export type ReverseProxiesServicesPostRequestTargetsList = ReadonlyArray<ServiceTarget>;
export const ReverseProxiesServicesPostRequestTargetsList = /*@__PURE__*/ S.Array(
	ServiceTarget,
) as any as S.Schema<ReverseProxiesServicesPostRequestTargetsList>;

/** NetBird group IDs whose peers may reach this private service over the tunnel. Required when private=true; ignored otherwise. Mutually exclusive with bearer auth (SSO). */
export type ReverseProxiesServicesPostRequestAccessGroupsList = ReadonlyArray<string>;
export const ReverseProxiesServicesPostRequestAccessGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<ReverseProxiesServicesPostRequestAccessGroupsList>;

export interface ReverseProxiesServicesPostRequest {
	/** Service name */
	name: string;
	/** Domain for the service */
	domain: string;
	/** Service mode. "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough. */
	mode?: ReverseProxiesServicesPostRequestMode;
	/** Port the proxy listens on (L4/TLS only). Set to 0 for auto-assignment. */
	listen_port?: number;
	/** List of target backends for this service */
	targets?: ReverseProxiesServicesPostRequestTargetsList;
	/** Whether the service is enabled */
	enabled: boolean;
	/** When true, the original client Host header is passed through to the backend instead of being rewritten to the backend's address */
	pass_host_header?: boolean;
	/** When true, Location headers in backend responses are rewritten to replace the backend address with the public-facing domain */
	rewrite_redirects?: boolean;
	auth?: ServiceAuthConfig;
	access_restrictions?: AccessRestrictions;
	/** When true, the service is NetBird-only — its target points at a proxy cluster, inbound peers authenticate via their WireGuard tunnel identity (no OIDC), and an ACL policy is auto-generated from access_groups to the cluster's proxy-peer group. Requires mode=http. */
	private?: boolean;
	/** NetBird group IDs whose peers may reach this private service over the tunnel. Required when private=true; ignored otherwise. Mutually exclusive with bearer auth (SSO). */
	access_groups?: ReverseProxiesServicesPostRequestAccessGroupsList;
}
export const ReverseProxiesServicesPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		domain: S.String,
		mode: S.optional(ReverseProxiesServicesPostRequestMode),
		listen_port: S.optional(S.Number),
		targets: S.optional(ReverseProxiesServicesPostRequestTargetsList),
		enabled: S.Boolean,
		pass_host_header: S.optional(S.Boolean),
		rewrite_redirects: S.optional(S.Boolean),
		auth: S.optional(ServiceAuthConfig),
		access_restrictions: S.optional(AccessRestrictions),
		private: S.optional(S.Boolean),
		access_groups: S.optional(ReverseProxiesServicesPostRequestAccessGroupsList),
	}).pipe(T.Http({ method: "POST", uri: "/api/reverse-proxies/services", code: 200 })),
).annotate({ identifier: "ReverseProxiesServicesPostRequest" }) as any as S.Schema<ReverseProxiesServicesPostRequest>;

export interface ReverseProxiesServicesServiceIdDeleteRequest {
	/** The unique identifier of a service */
	serviceId: string;
}
export const ReverseProxiesServicesServiceIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		serviceId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/reverse-proxies/services/{serviceId}", code: 200 })),
).annotate({
	identifier: "ReverseProxiesServicesServiceIdDeleteRequest",
}) as any as S.Schema<ReverseProxiesServicesServiceIdDeleteRequest>;

export interface ReverseProxiesServicesServiceIdDeleteResponse {}
export const ReverseProxiesServicesServiceIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "ReverseProxiesServicesServiceIdDeleteResponse",
}) as any as S.Schema<ReverseProxiesServicesServiceIdDeleteResponse>;

export interface ReverseProxiesServicesServiceIdGetRequest {
	/** The unique identifier of a service */
	serviceId: string;
}
export const ReverseProxiesServicesServiceIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		serviceId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/reverse-proxies/services/{serviceId}", code: 200 })),
).annotate({
	identifier: "ReverseProxiesServicesServiceIdGetRequest",
}) as any as S.Schema<ReverseProxiesServicesServiceIdGetRequest>;

/** Service mode. "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough. */
export type ReverseProxiesServicesServiceIdPutRequestMode = "http" | "tcp" | "udp" | "tls";
export const ReverseProxiesServicesServiceIdPutRequestMode = /*@__PURE__*/ S.String;

/** List of target backends for this service */
export type ReverseProxiesServicesServiceIdPutRequestTargetsList = ReadonlyArray<ServiceTarget>;
export const ReverseProxiesServicesServiceIdPutRequestTargetsList = /*@__PURE__*/ S.Array(
	ServiceTarget,
) as any as S.Schema<ReverseProxiesServicesServiceIdPutRequestTargetsList>;

/** NetBird group IDs whose peers may reach this private service over the tunnel. Required when private=true; ignored otherwise. Mutually exclusive with bearer auth (SSO). */
export type ReverseProxiesServicesServiceIdPutRequestAccessGroupsList = ReadonlyArray<string>;
export const ReverseProxiesServicesServiceIdPutRequestAccessGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<ReverseProxiesServicesServiceIdPutRequestAccessGroupsList>;

export interface ReverseProxiesServicesServiceIdPutRequest {
	/** The unique identifier of a service */
	serviceId: string;
	/** Service name */
	name: string;
	/** Domain for the service */
	domain: string;
	/** Service mode. "http" for L7 reverse proxy, "tcp"/"udp"/"tls" for L4 passthrough. */
	mode?: ReverseProxiesServicesServiceIdPutRequestMode;
	/** Port the proxy listens on (L4/TLS only). Set to 0 for auto-assignment. */
	listen_port?: number;
	/** List of target backends for this service */
	targets?: ReverseProxiesServicesServiceIdPutRequestTargetsList;
	/** Whether the service is enabled */
	enabled: boolean;
	/** When true, the original client Host header is passed through to the backend instead of being rewritten to the backend's address */
	pass_host_header?: boolean;
	/** When true, Location headers in backend responses are rewritten to replace the backend address with the public-facing domain */
	rewrite_redirects?: boolean;
	auth?: ServiceAuthConfig;
	access_restrictions?: AccessRestrictions;
	/** When true, the service is NetBird-only — its target points at a proxy cluster, inbound peers authenticate via their WireGuard tunnel identity (no OIDC), and an ACL policy is auto-generated from access_groups to the cluster's proxy-peer group. Requires mode=http. */
	private?: boolean;
	/** NetBird group IDs whose peers may reach this private service over the tunnel. Required when private=true; ignored otherwise. Mutually exclusive with bearer auth (SSO). */
	access_groups?: ReverseProxiesServicesServiceIdPutRequestAccessGroupsList;
}
export const ReverseProxiesServicesServiceIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		serviceId: S.String.pipe(T.Label()),
		name: S.String,
		domain: S.String,
		mode: S.optional(ReverseProxiesServicesServiceIdPutRequestMode),
		listen_port: S.optional(S.Number),
		targets: S.optional(ReverseProxiesServicesServiceIdPutRequestTargetsList),
		enabled: S.Boolean,
		pass_host_header: S.optional(S.Boolean),
		rewrite_redirects: S.optional(S.Boolean),
		auth: S.optional(ServiceAuthConfig),
		access_restrictions: S.optional(AccessRestrictions),
		private: S.optional(S.Boolean),
		access_groups: S.optional(ReverseProxiesServicesServiceIdPutRequestAccessGroupsList),
	}).pipe(T.Http({ method: "PUT", uri: "/api/reverse-proxies/services/{serviceId}", code: 200 })),
).annotate({
	identifier: "ReverseProxiesServicesServiceIdPutRequest",
}) as any as S.Schema<ReverseProxiesServicesServiceIdPutRequest>;

export type ReverseProxiesClustersClusterAddressDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete a self-hosted proxy cluster Removes all self-hosted (BYOP) proxy registrations for the given cluster address owned by the account. */
export const reverseProxiesClustersClusterAddressDelete: API.OperationMethod<
	ReverseProxiesClustersClusterAddressDeleteRequest,
	ReverseProxiesClustersClusterAddressDeleteResponse,
	ReverseProxiesClustersClusterAddressDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesClustersClusterAddressDeleteRequest,
	output: ReverseProxiesClustersClusterAddressDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesClustersGetError = Forbidden | NetbirdOpError;
/** List available proxy clusters Returns a list of available proxy clusters with their connection status */
export const reverseProxiesClustersGet: API.OperationMethod<
	ReverseProxiesClustersGetRequest,
	ReverseProxiesClustersGetResponse,
	ReverseProxiesClustersGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesClustersGetRequest,
	output: ReverseProxiesClustersGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesDomainsDomainIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete a Custom domain Delete an existing service custom domain */
export const reverseProxiesDomainsDomainIdDelete: API.OperationMethod<
	ReverseProxiesDomainsDomainIdDeleteRequest,
	ReverseProxiesDomainsDomainIdDeleteResponse,
	ReverseProxiesDomainsDomainIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesDomainsDomainIdDeleteRequest,
	output: ReverseProxiesDomainsDomainIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesDomainsDomainIdValidateGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Validate a custom domain Trigger domain ownership validation for a custom domain */
export const reverseProxiesDomainsDomainIdValidateGet: API.OperationMethod<
	ReverseProxiesDomainsDomainIdValidateGetRequest,
	ReverseProxiesDomainsDomainIdValidateGetResponse,
	ReverseProxiesDomainsDomainIdValidateGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesDomainsDomainIdValidateGetRequest,
	output: ReverseProxiesDomainsDomainIdValidateGetResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesDomainsGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Retrieve Service Domains Get information about domains that can be used for service endpoints. */
export const reverseProxiesDomainsGet: API.OperationMethod<
	ReverseProxiesDomainsGetRequest,
	ReverseProxiesDomainsGetResponse,
	ReverseProxiesDomainsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesDomainsGetRequest,
	output: ReverseProxiesDomainsGetResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesDomainsPostError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Create a Custom domain Create a new Custom domain for use with service endpoints, this will trigger an initial validation check */
export const reverseProxiesDomainsPost: API.OperationMethod<
	ReverseProxiesDomainsPostRequest,
	Service,
	ReverseProxiesDomainsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesDomainsPostRequest,
	output: Service,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesServicesGetError = Forbidden | NetbirdOpError;
/** List all Services Returns a list of all reverse proxy services */
export const reverseProxiesServicesGet: API.OperationMethod<
	ReverseProxiesServicesGetRequest,
	ReverseProxiesServicesGetResponse,
	ReverseProxiesServicesGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesServicesGetRequest,
	output: ReverseProxiesServicesGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesServicesPostError = BadRequest | Forbidden | Conflict | NetbirdOpError;
/** Create a Service Creates a new reverse proxy service */
export const reverseProxiesServicesPost: API.OperationMethod<
	ReverseProxiesServicesPostRequest,
	Service,
	ReverseProxiesServicesPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesServicesPostRequest,
	output: Service,
	errors: [BadRequest, Forbidden, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesServicesServiceIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete a Service Delete an existing service */
export const reverseProxiesServicesServiceIdDelete: API.OperationMethod<
	ReverseProxiesServicesServiceIdDeleteRequest,
	ReverseProxiesServicesServiceIdDeleteResponse,
	ReverseProxiesServicesServiceIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesServicesServiceIdDeleteRequest,
	output: ReverseProxiesServicesServiceIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesServicesServiceIdGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Retrieve a Service Get information about a specific reverse proxy service */
export const reverseProxiesServicesServiceIdGet: API.OperationMethod<
	ReverseProxiesServicesServiceIdGetRequest,
	Service,
	ReverseProxiesServicesServiceIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesServicesServiceIdGetRequest,
	output: Service,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type ReverseProxiesServicesServiceIdPutError = BadRequest | Forbidden | NotFound | Conflict | NetbirdOpError;
/** Update a Service Update an existing service */
export const reverseProxiesServicesServiceIdPut: API.OperationMethod<
	ReverseProxiesServicesServiceIdPutRequest,
	Service,
	ReverseProxiesServicesServiceIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: ReverseProxiesServicesServiceIdPutRequest,
	output: Service,
	errors: [BadRequest, Forbidden, NotFound, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
