import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export interface IntegrationsBillingUsageGetRequest {}
export const IntegrationsBillingUsageGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/billing/usage", code: 200 })),
).annotate({ identifier: "IntegrationsBillingUsageGetRequest" }) as any as S.Schema<IntegrationsBillingUsageGetRequest>;

export interface UsageStats {
	/** Number of active users. */
	active_users: number;
	/** Total number of users. */
	total_users: number;
	/** Number of active peers. */
	active_peers: number;
	/** Total number of peers. */
	total_peers: number;
}
export const UsageStats = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		active_users: S.Number,
		total_users: S.Number,
		active_peers: S.Number,
		total_peers: S.Number,
	}),
).annotate({ identifier: "UsageStats" }) as any as S.Schema<UsageStats>;

export type IntegrationsBillingUsageGetError = NetbirdOpError;
/** Get current usage */
export const integrationsBillingUsageGet: API.OperationMethod<
	IntegrationsBillingUsageGetRequest,
	UsageStats,
	IntegrationsBillingUsageGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsBillingUsageGetRequest,
	output: UsageStats,
	errors: [UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
