/**
 * Renders the IR as a Nix attribute set of `lib.mkOption` declarations.
 *
 * Every generated option is `nullOf <type>` with `default = null`, and the
 * module strips nulls before writing JSON. This matters: pi layers project
 * settings over global ones and applies its own defaults for absent keys, so
 * materialising a default here would turn "unset" into "explicitly set to
 * pi's current default", freezing behaviour that upstream may change and
 * defeating project-level overrides. Defaults are documented instead.
 */
import type { NixType, OptionNode } from "./model.ts";

const INDENT = "  ";

const indent = (depth: number): string => INDENT.repeat(depth);

/** Quote a string as a Nix string literal. */
export const nixString = (value: string): string => `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/** Nix attribute names need quoting unless they are plain identifiers. */
export const nixAttrName = (name: string): string => (/^[A-Za-z_][A-Za-z0-9_'-]*$/.test(name) ? name : nixString(name));

/** Render a `NixType` as a `lib.types` expression. */
export const renderType = (type: NixType, depth: number): string => {
	switch (type.kind) {
		case "bool":
			return "types.bool";
		case "str":
			return "types.str";
		case "lines":
			return "types.lines";
		case "int":
			return "types.int";
		case "number":
			return "types.number";
		case "path":
			return "types.path";
		case "enum":
			return `types.enum [ ${type.values.map(nixString).join(" ")} ]`;
		case "intBetween":
			return `types.ints.between ${type.lo} ${type.hi}`;
		case "listOf":
			return `types.listOf (${renderType(type.of, depth)})`;
		case "attrsOf":
			return `types.attrsOf (${renderType(type.of, depth)})`;
		case "oneOf":
			// `types.either` is binary; fold right for more than two members.
			return type.of
				.slice(0, -1)
				.reduceRight(
					(accumulator, member) => `types.either (${renderType(member, depth)}) (${accumulator})`,
					renderType(type.of[type.of.length - 1]!, depth),
				);
		case "submodule":
			return `types.submodule {\n${indent(depth + 1)}options = {\n${type.options
				.map(option => renderOption(option, depth + 2))
				.join("\n")}\n${indent(depth + 1)}};\n${indent(depth)}}`;
		case "anything":
			return "types.anything";
	}
};

/** Build the description block, folding in the upstream default. */
const renderDescription = (option: OptionNode): string => {
	const parts: string[] = [];
	if (option.description !== undefined && option.description !== "") {
		// Docs cells rarely end in punctuation; add it so the appended default
		// sentence does not run into the description.
		parts.push(/[.!?]$/.test(option.description) ? option.description : `${option.description}.`);
	}
	if (option.upstreamDefault !== undefined) {
		parts.push(`Pi's default when unset: ${option.upstreamDefault}.`);
	}
	if (parts.length === 0) {
		parts.push(`The \`${option.path}\` setting. See pi's settings documentation.`);
	}
	return parts.join(" ");
};

/** Render one option as `name = lib.mkOption { ... };`. */
export const renderOption = (option: OptionNode, depth: number): string => {
	const pad = indent(depth);
	const inner = indent(depth + 1);
	const lines = [
		`${pad}${nixAttrName(option.name)} = mkOption {`,
		`${inner}type = types.nullOr (${renderType(option.type, depth + 1)});`,
		`${inner}default = null;`,
	];
	if (option.example !== undefined) {
		lines.push(`${inner}example = ${option.example};`);
	}
	lines.push(`${inner}description = ${nixString(renderDescription(option))};`);
	lines.push(`${pad}};`);
	return lines.join("\n");
};

export interface EmitMeta {
	piVersion: string;
	generator: string;
	skipped: { path: string; reason: string; note: string }[];
}

/** Emit the full generated options file. */
export const emitOptionsFile = (options: OptionNode[], meta: EmitMeta): string => {
	const header = [
		"# Generated by @yorganci/pi-nix-options — DO NOT EDIT BY HAND.",
		"#",
		`# Source: @earendil-works/pi-coding-agent ${meta.piVersion}`,
		`#         dist/core/settings-manager.d.ts (interface Settings)`,
		`# Regenerate: ${meta.generator}`,
		"#",
		"# Every option is nullable and defaults to null; the module drops null",
		"# values so unset options are absent from settings.json and pi applies its",
		"# own default. Documented defaults are therefore prose, not Nix defaults.",
	];
	if (meta.skipped.length > 0) {
		header.push("#");
		header.push("# Intentionally omitted (pi writes these itself at runtime):");
		for (const entry of meta.skipped) {
			header.push(`#   - ${entry.path} (${entry.reason}): ${entry.note}`);
		}
	}

	const body = options.map(option => renderOption(option, 1)).join("\n");

	return `${header.join("\n")}
{ lib }:
let
  inherit (lib) mkOption types;
in
{
${body}
}
`;
};

/** Emit the keybindings option: a fixed set of known action ids. */
export const emitKeybindingsFile = (
	ids: string[],
	docs: Map<string, { default?: string; description: string }>,
	meta: EmitMeta,
): string => {
	const options = ids
		.slice()
		.sort()
		.map(id => {
			const entry = docs.get(id);
			const prose =
				entry === undefined || entry.description === ""
					? `The ${id} action.`
					: /[.!?]$/.test(entry.description)
						? entry.description
						: `${entry.description}.`;
			const description = entry?.default === undefined ? prose : `${prose} Pi's default binding: ${entry.default}.`;
			return [
				`    ${nixAttrName(id)} = mkOption {`,
				`      type = types.nullOr (types.either types.str (types.listOf types.str));`,
				`      default = null;`,
				`      description = ${nixString(description)};`,
				`    };`,
			].join("\n");
		})
		.join("\n");

	return `# Generated by @yorganci/pi-nix-options — DO NOT EDIT BY HAND.
#
# Source: @earendil-works/pi-coding-agent ${meta.piVersion}
#         dist/core/keybindings.d.ts (AppKeybindings)
#         @earendil-works/pi-tui dist/keybindings.d.ts (Keybindings)
# Regenerate: ${meta.generator}
#
# ${ids.length} action ids. A value may be a single key ("ctrl+p") or a list of
# keys. Unset actions keep pi's default binding.
{ lib }:
let
  inherit (lib) mkOption types;
in
{
${options}
}
`;
};
