# Generated by @yorganci/pi-nix-options — DO NOT EDIT BY HAND.
#
# Source: @earendil-works/pi-coding-agent 0.84.4
#         dist/core/settings-manager.d.ts (interface Settings)
# Regenerate: bun run --filter @yorganci/pi-nix-options generate
#
# Every option is nullable and defaults to null; the module drops null
# values so unset options are absent from settings.json and pi applies its
# own default. Documented defaults are therefore prose, not Nix defaults.
#
# Intentionally omitted (pi writes these itself at runtime):
#   - lastChangelogVersion (runtime-state): written by pi after showing the changelog; pinning it suppresses or repeats the changelog
#   - trackingId (machine-specific): analytics identifier generated on first opt-in; must stay per-machine
{lib}: let
  inherit (lib) mkOption types;
in {
  defaultProvider = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Startup provider (e.g., \"anthropic\", \"openai\"; saved with Ctrl+S in /model, or edited manually).";
  };
  defaultModel = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Startup model ID (saved with Ctrl+S in /model, or edited manually).";
  };
  defaultThinkingLevel = mkOption {
    type = types.nullOr (types.enum ["off" "minimal" "low" "medium" "high" "xhigh" "max"]);
    default = null;
    description = "Startup thinking level (saved with Ctrl+S in /thinking, or edited manually): \"off\", \"minimal\", \"low\", \"medium\", \"high\", \"xhigh\", \"max\".";
  };
  modelThinkingLevels = mkOption {
    type = types.nullOr (types.attrsOf (types.enum ["off" "minimal" "low" "medium" "high" "xhigh" "max"]));
    default = null;
    description = "Per-model startup thinking levels keyed by \"provider/modelId\"; configure from /settings → Default thinking level per model or edit manually.";
  };
  transport = mkOption {
    type = types.nullOr (types.enum ["sse" "websocket" "websocket-cached" "auto"]);
    default = null;
    description = "Preferred transport for providers that support multiple transports: \"sse\", \"websocket\", \"websocket-cached\", or \"auto\". Pi's default when unset: \"auto\".";
  };
  steeringMode = mkOption {
    type = types.nullOr (types.enum ["all" "one-at-a-time"]);
    default = null;
    description = "How steering messages are sent: \"all\" or \"one-at-a-time\". Pi's default when unset: \"one-at-a-time\".";
  };
  followUpMode = mkOption {
    type = types.nullOr (types.enum ["all" "one-at-a-time"]);
    default = null;
    description = "How follow-up messages are sent: \"all\" or \"one-at-a-time\". Pi's default when unset: \"one-at-a-time\".";
  };
  theme = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Theme name (\"dark\", \"light\", or custom). Pi's default when unset: \"dark\".";
  };
  compaction = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        enabled = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Enable auto-compaction. Pi's default when unset: true.";
        };
        reserveTokens = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "Tokens reserved for LLM response. Pi's default when unset: 16384.";
        };
        keepRecentTokens = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "Recent tokens to keep (not summarized). Pi's default when unset: 20000.";
        };
      };
    });
    default = null;
    description = "The `compaction` setting. See pi's settings documentation.";
  };
  branchSummary = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        reserveTokens = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "Tokens reserved for branch summarization. Pi's default when unset: 16384.";
        };
        skipPrompt = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Skip \"Summarize branch?\" prompt on /tree navigation (defaults to no summary). Pi's default when unset: false.";
        };
      };
    });
    default = null;
    description = "The `branchSummary` setting. See pi's settings documentation.";
  };
  retry = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        enabled = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Enable automatic agent-level retry on transient errors. Pi's default when unset: true.";
        };
        maxRetries = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "Maximum agent-level retry attempts. Pi's default when unset: 3.";
        };
        baseDelayMs = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "Base delay for agent-level exponential backoff (2s, 4s, 8s). Pi's default when unset: 2000.";
        };
        provider = mkOption {
          type = types.nullOr (types.submodule {
            options = {
              timeoutMs = mkOption {
                type = types.nullOr (types.number);
                default = null;
                description = "Provider/SDK request timeout in milliseconds. Pi's default when unset: SDK default.";
              };
              maxRetries = mkOption {
                type = types.nullOr (types.number);
                default = null;
                description = "Provider/SDK retry attempts. Pi's default when unset: 0.";
              };
              maxRetryDelayMs = mkOption {
                type = types.nullOr (types.number);
                default = null;
                description = "Max server-requested delay before failing (60s). Pi's default when unset: 60000.";
              };
            };
          });
          default = null;
          description = "The `retry.provider` setting. See pi's settings documentation.";
        };
      };
    });
    default = null;
    description = "The `retry` setting. See pi's settings documentation.";
  };
  hideThinkingBlock = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Hide thinking blocks in output. Pi's default when unset: false.";
  };
  showCacheMissNotices = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Show transcript notices for significant prompt-cache misses and compaction or branch-summary usage. Pi's default when unset: false.";
  };
  externalEditor = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Command for Ctrl+G external editor; takes precedence over environment variables. Pi's default when unset: $VISUAL, then $EDITOR, then Notepad on Windows or nano elsewhere.";
  };
  shellPath = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Custom shell path (e.g., for Cygwin on Windows); supports a leading ~ for the home directory.";
  };
  quietStartup = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Hide startup header. Pi's default when unset: false.";
  };
  defaultProjectTrust = mkOption {
    type = types.nullOr (types.enum ["ask" "always" "never"]);
    default = null;
    description = "Fallback project trust behavior: \"ask\", \"always\", or \"never\". Global setting only. Pi's default when unset: \"ask\".";
  };
  shellCommandPrefix = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Prefix for every bash command (e.g., \"shopt -s expand_aliases\").";
  };
  npmCommand = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Command argv used for npm package lookup/install operations (e.g., [\"mise\", \"exec\", \"node@20\", \"--\", \"npm\"]).";
  };
  collapseChangelog = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Show condensed changelog after updates. Pi's default when unset: false.";
  };
  enableInstallTelemetry = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Send an anonymous install/update version ping after first install or changelog-detected updates. This does not control update checks. Pi's default when unset: true.";
  };
  enableAnalytics = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Opt-in analytics data sharing. Currently only asked for during the experimental first-time setup (PI_EXPERIMENTAL=1). Pi's default when unset: false.";
  };
  packages = mkOption {
    type = types.nullOr (types.listOf (types.anything));
    default = null;
    description = "npm/git packages to load resources from. Pi's default when unset: [].";
  };
  extensions = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Local extension file paths or directories. Pi's default when unset: [].";
  };
  skills = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Local skill file paths or directories. Pi's default when unset: [].";
  };
  prompts = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Local prompt template paths or directories. Pi's default when unset: [].";
  };
  themes = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Local theme file paths or directories. Pi's default when unset: [].";
  };
  enableSkillCommands = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Register skills as /skill:name commands. Pi's default when unset: true.";
  };
  terminal = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        showImages = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Show images in terminal (if supported). Pi's default when unset: true.";
        };
        imageWidthCells = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "Preferred inline image width in terminal cells. Pi's default when unset: 60.";
        };
        clearOnShrink = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Clear empty rows when content shrinks (can cause flicker). Pi's default when unset: false.";
        };
        showTerminalProgress = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "The `terminal.showTerminalProgress` setting. See pi's settings documentation.";
        };
        hyperlinks = mkOption {
          type = types.nullOr (types.either (types.bool) (types.enum ["auto"]));
          default = null;
          description = "Override OSC 8 hyperlink support (advanced, JSON-only). Pi's default when unset: \"auto\".";
        };
        images = mkOption {
          type = types.nullOr (types.either (types.bool) (types.enum ["auto" "kitty" "iterm2"]));
          default = null;
          description = "Override image protocol support with \"kitty\", \"iterm2\", false, or \"auto\" (advanced, JSON-only). Pi's default when unset: \"auto\".";
        };
        trueColor = mkOption {
          type = types.nullOr (types.either (types.bool) (types.enum ["auto"]));
          default = null;
          description = "Override truecolor support (advanced, JSON-only). Pi's default when unset: \"auto\".";
        };
      };
    });
    default = null;
    description = "The `terminal` setting. See pi's settings documentation.";
  };
  images = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        autoResize = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Resize images to 2000x2000 max. Applies to @file attachments, read, and images returned by tools. Pi's default when unset: true.";
        };
        blockImages = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Block all images from being sent to LLM. Pi's default when unset: false.";
        };
      };
    });
    default = null;
    description = "The `images` setting. See pi's settings documentation.";
  };
  enabledModels = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Model patterns for Ctrl+P cycling (same format as --models CLI flag).";
  };
  defaultTools = mkOption {
    type = types.nullOr (types.listOf (types.str));
    default = null;
    description = "Built-in tools enabled initially. When omitted, Pi uses its standard defaults.";
  };
  doubleEscapeAction = mkOption {
    type = types.nullOr (types.enum ["fork" "tree" "none"]);
    default = null;
    description = "Action for double-escape: \"tree\", \"fork\", or \"none\". Pi's default when unset: \"tree\".";
  };
  treeFilterMode = mkOption {
    type = types.nullOr (types.enum ["all" "default" "no-tools" "user-only" "labeled-only"]);
    default = null;
    description = "Default filter for /tree: \"default\", \"no-tools\", \"user-only\", \"labeled-only\", \"all\". Pi's default when unset: \"default\".";
  };
  thinkingBudgets = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        minimal = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "The `thinkingBudgets.minimal` setting. See pi's settings documentation.";
        };
        low = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "The `thinkingBudgets.low` setting. See pi's settings documentation.";
        };
        medium = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "The `thinkingBudgets.medium` setting. See pi's settings documentation.";
        };
        high = mkOption {
          type = types.nullOr (types.number);
          default = null;
          description = "The `thinkingBudgets.high` setting. See pi's settings documentation.";
        };
      };
    });
    default = null;
    description = "Custom token budgets per thinking level. Anthropic, Google, and Bedrock use these natively. OpenAI-compatible models use them when compat.thinkingTokenBudgetField (or supportsThinkingTokenBudget) is set.";
  };
  editorPaddingX = mkOption {
    type = types.nullOr (types.number);
    default = null;
    description = "Horizontal padding for input editor (0-3). Pi's default when unset: 0.";
  };
  outputPad = mkOption {
    type = types.nullOr (types.ints.between 0 1);
    default = null;
    description = "Horizontal padding for user messages, assistant messages, and thinking (0 or 1). Pi's default when unset: 1.";
  };
  autocompleteMaxVisible = mkOption {
    type = types.nullOr (types.number);
    default = null;
    description = "Max visible items in autocomplete dropdown (3-20). Pi's default when unset: 5.";
  };
  showHardwareCursor = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Show the terminal cursor while TUI positions it for IME support. Pi's default when unset: false.";
  };
  markdown = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        codeBlockIndent = mkOption {
          type = types.nullOr (types.str);
          default = null;
          description = "Indentation for code blocks. Pi's default when unset: \"  \".";
        };
        mermaid = mkOption {
          type = types.nullOr (types.enum ["off" "final" "streaming"]);
          default = null;
          description = "Mermaid rendering mode: \"off\", \"final\", or \"streaming\". Pi's default when unset: \"streaming\".";
        };
      };
    });
    default = null;
    description = "The `markdown` setting. See pi's settings documentation.";
  };
  warnings = mkOption {
    type = types.nullOr (types.submodule {
      options = {
        anthropicExtraUsage = mkOption {
          type = types.nullOr (types.bool);
          default = null;
          description = "Show a warning when Anthropic subscription auth may use paid extra usage. Pi's default when unset: true.";
        };
      };
    });
    default = null;
    description = "The `warnings` setting. See pi's settings documentation.";
  };
  sessionDir = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "Directory where session files are stored. Accepts absolute or relative paths, plus ~.";
  };
  httpProxy = mkOption {
    type = types.nullOr (types.str);
    default = null;
    description = "HTTP proxy URL applied as HTTP_PROXY and HTTPS_PROXY. Global setting only.";
  };
  httpIdleTimeoutMs = mkOption {
    type = types.nullOr (types.number);
    default = null;
    description = "HTTP header/body idle timeout in milliseconds, also used by providers with explicit stream idle timeouts. Set to 0 to disable. Pi's default when unset: 300000.";
  };
  websocketConnectTimeoutMs = mkOption {
    type = types.nullOr (types.number);
    default = null;
    description = "WebSocket connect/open handshake timeout in milliseconds for providers that support WebSocket transports. Set to 0 to disable. Pi's default when unset: 15000.";
  };
  tuiMode = mkOption {
    type = types.nullOr (types.enum ["regular" "fullscreen"]);
    default = null;
    description = "Interactive TUI mode: \"regular\" or experimental \"fullscreen\". Changes from /settings apply immediately; --tui-mode overrides this setting at startup. Pi's default when unset: \"regular\".";
  };
  fullscreenExitOutput = mkOption {
    type = types.nullOr (types.enum ["transcript" "resume-hint"]);
    default = null;
    description = "Fullscreen exit output: \"transcript\" prints the final transcript and resume hint, while \"resume-hint\" restores the previous screen and prints only the resume hint. Has no effect in regular TUI mode. Pi's default when unset: \"transcript\".";
  };
  fullscreenScrollbar = mkOption {
    type = types.nullOr (types.enum ["auto" "always" "hidden"]);
    default = null;
    description = "Fullscreen transcript scrollbar: \"auto\" shows it temporarily while scrolling, \"always\" reserves the rightmost column and keeps it visible, and \"hidden\" hides it. Has no effect in regular TUI mode. Pi's default when unset: \"auto\".";
  };
  fullscreenCopyOnSelect = mkOption {
    type = types.nullOr (types.bool);
    default = null;
    description = "Automatically copy selected text in fullscreen mode. When disabled, selections stay highlighted and Ctrl+X copies the active selection. Pi's default when unset: true.";
  };
}
