# Keep the secrets repository's recipients in step with the flake.
#
# Usage:
#   sops-config render         print the .sops.yaml the flake implies
#   sops-config check <dir>    exit 1 if <dir>/.sops.yaml or any file's
#                              recipients differ from what the flake implies
#   sops-config <dir>          write <dir>/.sops.yaml, then re-encrypt every
#                              file whose recipients differ (needs an admin key)
#
# Recipients:
#   hosts/<host>.yaml          the admins and <host>, whose age recipient is
#                              derived from its pinned SSH host key
#   identities/<host>/<file>   the admins only
#
# SOPS_SPEC (set by the package) is JSON: {"admins": [<GPG fingerprint>],
# "hosts": {<host>: "ssh-ed25519 <key>"}}.
LOG_PREFIX=sops-config
SPEC="${SOPS_SPEC:?SOPS_SPEC must point at the recipients spec}"

log() {
    printf '%s: %s\n' "$LOG_PREFIX" "$*" >&2
}

die() {
    log "$*"
    exit 1
}

admins() {
    jq -r '.admins[]' "$SPEC"
}

hosts() {
    jq -r '.hosts | keys[]' "$SPEC"
}

host_age() {
    local key
    key="$(jq -r --arg h "$1" '.hosts[$h] // empty' "$SPEC")"
    [[ -n $key ]] || return 1
    # A raw ssh-ed25519 recipient also encrypts, but sops-nix decrypts with
    # the converted age identity and could not open it: always convert.
    printf '%s\n' "$key" | ssh-to-age
}

render() {
    local host admin
    echo '# Generated by "nix run .#sops-config" in nix-config; do not edit.'
    echo '# Admins come from flake.sops.admins, hosts from hostInventory.ssh.hostKey.'
    echo 'creation_rules:'
    for host in $(hosts); do
        echo "  - path_regex: '^hosts/${host}\\.yaml\$'"
        echo '    key_groups:'
        echo '      - pgp:'
        for admin in $(admins); do
            echo "          - ${admin}"
        done
        echo '        age:'
        echo "          - $(host_age "$host")"
    done
    echo "  - path_regex: '^identities/[^/]+/[^/]+\$'"
    echo '    key_groups:'
    echo '      - pgp:'
    for admin in $(admins); do
        echo "          - ${admin}"
    done
}

# The recipients a file must have, one `pgp:<fp>` / `age:<recipient>` per line.
expected_recipients() {
    local file=$1 host age
    case "$file" in
        hosts/*.yaml)
            host="${file#hosts/}"
            host="${host%.yaml}"
            age="$(host_age "$host")" || return 1
            {
                admins | sed 's/^/pgp:/'
                echo "age:${age}"
            } | sort
            ;;
        identities/*/*)
            admins | sed 's/^/pgp:/' | sort
            ;;
    esac
}

# The recipients a file is encrypted to, read from its SOPS metadata. Binary
# files (the identities) are stored as JSON, which yq reads as YAML.
actual_recipients() {
    yq -p yaml -o yaml '((.sops.pgp // [])[] | "pgp:" + .fp), ((.sops.age // [])[] | "age:" + .recipient)' "$1" | sort
}

# Print every file under <dir> whose recipients drift, and fail on anything
# that does not belong in the repository.
drifted_files() {
    local dir=$1 file status=0 want
    while IFS= read -r file; do
        case "$file" in
            README.md | .sops.yaml | .gitignore | .gitattributes) ;;
            hosts/*.yaml | identities/*/*)
                if ! want="$(expected_recipients "$file")"; then
                    log "${file}: no pinned host key for this host"
                    status=1
                elif [[ $want != "$(actual_recipients "$dir/$file")" ]]; then
                    echo "$file"
                fi
                ;;
            *)
                log "${file}: unexpected file (secrets belong in hosts/ or identities/)"
                status=1
                ;;
        esac
    done < <(cd "$dir" && find . -type f -not -path './.git/*' | sed 's|^\./||' | sort)
    return "$status"
}

check() {
    local dir=$1 status=0 drift
    if ! diff -u "$dir/.sops.yaml" <(render) >&2; then
        log ".sops.yaml differs from the flake (run: nix run .#sops-config -- <dir>)"
        status=1
    fi
    drift="$(drifted_files "$dir")" || status=1
    if [[ -n $drift ]]; then
        while IFS= read -r file; do
            log "${file}: recipients differ from the flake"
        done <<< "$drift"
        status=1
    fi
    return "$status"
}

update() {
    local dir=$1 drift file
    render > "$dir/.sops.yaml"
    log "wrote ${dir}/.sops.yaml"
    drift="$(drifted_files "$dir")" || die "fix the problems above first"
    if [[ -n $drift ]]; then
        while IFS= read -r file; do
            log "re-encrypting ${file}"
            (cd "$dir" && sops updatekeys --yes "$file")
        done <<< "$drift"
    fi
    check "$dir"
    log "recipients match the flake"
}

case "${1:-}" in
    render)
        render
        ;;
    check)
        check "${2:?usage: sops-config check <dir>}"
        ;;
    "" | -h | --help)
        cat << 'EOF'
Usage:
  sops-config render         print the .sops.yaml the flake implies
  sops-config check <dir>    exit 1 if <dir>/.sops.yaml or any file's recipients drift
  sops-config <dir>          write <dir>/.sops.yaml and re-encrypt drifted files
                             (needs an admin key)
EOF
        ;;
    *)
        update "$1"
        ;;
esac
