{
  flake.modules.nixos.netbird-server = {
    lib,
    config,
    pkgs,
    ...
  }: let
    cfg = config.netbird-server;

    stateDir = "/var/lib/netbird";
    secretsDir = "${stateDir}/secrets";
    runtimeDir = "/run/netbird-server";
    listenPort = 8081;
    healthcheckPort = 9000;
    metricsPort = 9090;
    stunPort = 3478;
    # Avoid Traefik's historical default API port (:8080).
    dashboardPort = 8090;

    # Placeholders are replaced at service start so secrets stay out of the Nix store.
    configTemplate = pkgs.writeText "netbird-server-config.yaml" ''
      # Generated by NixOS netbird-server module. Secrets are injected at runtime.
      server:
        listenAddress: "127.0.0.1:${toString listenPort}"
        exposedAddress: "https://${cfg.domain}:443"
        stunPorts:
          - ${toString stunPort}
        metricsPort: ${toString metricsPort}
        healthcheckAddress: "127.0.0.1:${toString healthcheckPort}"
        logLevel: "info"
        logFile: "console"
        authSecret: "@authSecret@"
        dataDir: "${stateDir}"
        disableAnonymousMetrics: true
        disableGeoliteUpdate: false
        auth:
          issuer: "https://${cfg.domain}/oauth2"
          localAuthDisabled: false
          signKeyRefreshEnabled: true
          sessionCookieEncryptionKey: "@sessionCookieKey@"
          dashboardRedirectURIs:
            - "https://${cfg.domain}/nb-auth"
            - "https://${cfg.domain}/nb-silent-auth"
          cliRedirectURIs:
            - "http://localhost:53000/"
        store:
          engine: "sqlite"
          encryptionKey: "@encryptionKey@"
        reverseProxy:
          trustedHTTPProxies:
            - "127.0.0.1/32"
            - "::1/128"
    '';

    dashboardDrv = let
      settings = {
        AUTH_AUDIENCE = "netbird-dashboard";
        AUTH_CLIENT_ID = "netbird-dashboard";
        AUTH_CLIENT_SECRET = "";
        AUTH_AUTHORITY = "https://${cfg.domain}/oauth2";
        AUTH_SUPPORTED_SCOPES = "openid profile email groups";
        AUTH_REDIRECT_URI = "/nb-auth";
        AUTH_SILENT_REDIRECT_URI = "/nb-silent-auth";
        NETBIRD_TOKEN_SOURCE = "accessToken";
        USE_AUTH0 = false;
        NETBIRD_MGMT_API_ENDPOINT = "https://${cfg.domain}";
        NETBIRD_MGMT_GRPC_API_ENDPOINT = "https://${cfg.domain}";
        NETBIRD_AGENT_NETWORK_ENABLED = cfg.enableAgentNetwork;
        NETBIRD_AGENT_NETWORK_ONLY = false;
      };
      toStringEnv = value:
        if builtins.isBool value
        then lib.boolToString value
        else toString value;
    in
      pkgs.runCommand "netbird-dashboard-templated" {
        nativeBuildInputs = [pkgs.gettext];
        env =
          {
            ENV_STR = lib.concatStringsSep " " [
              "$AUTH_AUDIENCE"
              "$AUTH_AUTHORITY"
              "$AUTH_CLIENT_ID"
              "$AUTH_CLIENT_SECRET"
              "$AUTH_REDIRECT_URI"
              "$AUTH_SILENT_REDIRECT_URI"
              "$AUTH_SUPPORTED_SCOPES"
              "$NETBIRD_AGENT_NETWORK_ENABLED"
              "$NETBIRD_AGENT_NETWORK_ONLY"
              "$NETBIRD_DRAG_QUERY_PARAMS"
              "$NETBIRD_GOOGLE_ANALYTICS_ID"
              "$NETBIRD_GOOGLE_TAG_MANAGER_ID"
              "$NETBIRD_HOTJAR_TRACK_ID"
              "$NETBIRD_MGMT_API_ENDPOINT"
              "$NETBIRD_MGMT_GRPC_API_ENDPOINT"
              "$NETBIRD_TOKEN_SOURCE"
              "$NETBIRD_WASM_PATH"
              "$USE_AUTH0"
            ];
          }
          // (lib.mapAttrs (_: toStringEnv) settings);
      } ''
        cp -R ${pkgs.netbird-dashboard} build
        find build -type d -exec chmod 755 {} \;
        OIDC_TRUSTED_DOMAINS="build/OidcTrustedDomains.js"
        envsubst "$ENV_STR" < "$OIDC_TRUSTED_DOMAINS.tmpl" > "$OIDC_TRUSTED_DOMAINS"
        for f in $(grep -R -l -E 'AUTH_SUPPORTED_SCOPES|NETBIRD_AGENT_NETWORK' build/); do
          mv "$f" "$f.copy"
          envsubst "$ENV_STR" < "$f.copy" > "$f"
          rm "$f.copy"
        done
        cp -R build $out
      '';

    prepareConfig = pkgs.writeShellApplication {
      name = "netbird-server-prepare-config";
      runtimeInputs = [pkgs.openssl pkgs.replace-secret];
      text = ''
        set -euo pipefail

        mkdir -p ${lib.escapeShellArg secretsDir}
        chmod 700 ${lib.escapeShellArg secretsDir}

        auth_secret=${lib.escapeShellArg "${secretsDir}/auth-secret"}
        encryption_key=${lib.escapeShellArg "${secretsDir}/store-encryption-key"}
        session_cookie_key=${lib.escapeShellArg "${secretsDir}/session-cookie-key"}
        runtime_config=${lib.escapeShellArg "${runtimeDir}/config.yaml"}

        if [[ ! -s "$auth_secret" ]]; then
          openssl rand -base64 32 | tr -d '=\n' >"$auth_secret"
          chmod 600 "$auth_secret"
        fi

        if [[ ! -s "$encryption_key" ]]; then
          # Keep base64 padding; NetBird decodes this as a 32-byte AES key.
          openssl rand -base64 32 | tr -d '\n' >"$encryption_key"
          chmod 600 "$encryption_key"
        fi

        if [[ ! -s "$session_cookie_key" ]]; then
          openssl rand -hex 16 | tr -d '\n' >"$session_cookie_key"
          chmod 600 "$session_cookie_key"
        fi

        install -m 600 ${configTemplate} "$runtime_config"

        replace-secret '@authSecret@' "$auth_secret" "$runtime_config"
        replace-secret '@encryptionKey@' "$encryption_key" "$runtime_config"
        replace-secret '@sessionCookieKey@' "$session_cookie_key" "$runtime_config"
      '';
    };
  in {
    options.netbird-server = {
      enable = lib.mkEnableOption "self-hosted NetBird unified server";

      domain = lib.mkOption {
        type = lib.types.str;
        example = "netbird.example.com";
        description = "Public hostname for the NetBird dashboard, API, signal, and relay.";
      };

      acmeEmail = lib.mkOption {
        type = lib.types.str;
        description = "Email address used for Let's Encrypt ACME registration.";
      };

      package = lib.mkOption {
        type = lib.types.package;
        default = pkgs.netbird-server;
        defaultText = lib.literalExpression "pkgs.netbird-server";
        description = "Combined NetBird server package.";
      };

      # When true, Traefik TCP-passthroughs unknown SNI to netbird-proxy :8443.
      enableProxyPassthrough = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable Traefik TLS passthrough for NetBird reverse proxy (HostSNI `*`).";
      };

      enableAgentNetwork = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Expose the Agent Network section in the dashboard nav (NETBIRD_AGENT_NETWORK_ENABLED).
          Keeps the full NetBird UI; does not enable agent-network-only mode.
        '';
      };
    };

    config = lib.mkIf cfg.enable {
      users.users.netbird = {
        isSystemUser = true;
        group = "netbird";
        home = stateDir;
        createHome = true;
      };
      users.groups.netbird = {};

      networking.firewall = {
        allowedTCPPorts = [80 443];
        allowedUDPPorts = [stunPort];
      };

      # Local static file server for the dashboard SPA (Traefik terminates TLS publicly).
      systemd.services.netbird-dashboard = {
        description = "NetBird dashboard static files";
        after = ["network.target"];
        wantedBy = ["multi-user.target"];
        serviceConfig = {
          Type = "simple";
          ExecStart = "${lib.getExe pkgs.static-web-server} --host 127.0.0.1 --port ${toString dashboardPort} --root ${dashboardDrv} --page-fallback ${dashboardDrv}/index.html --log-level error";
          Restart = "on-failure";
          RestartSec = "3s";
          DynamicUser = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          PrivateTmp = true;
          NoNewPrivileges = true;
        };
      };

      services.traefik = {
        enable = true;
        staticConfigOptions = {
          # Do not enable api/ping — both create a default :8080 "traefik" entrypoint.
          entryPoints = {
            web.address = ":80";
            websecure.address = ":443";
          };
          certificatesResolvers.letsencrypt.acme = {
            email = cfg.acmeEmail;
            storage = "/var/lib/traefik/acme.json";
            tlsChallenge = {};
          };
        };
        dynamicConfigOptions =
          {
            http = {
              middlewares.redirect-to-https.redirectScheme = {
                scheme = "https";
                permanent = true;
              };
              routers = {
                # NetBird proxy HTTP-01 challenges (must win over HTTPS redirect).
                netbird-proxy-acme = {
                  rule = "PathPrefix(`/.well-known/acme-challenge/`)";
                  entryPoints = ["web"];
                  service = "netbird-proxy-acme";
                  priority = 1000;
                };
                http-to-https = {
                  rule = "PathPrefix(`/`)";
                  entryPoints = ["web"];
                  middlewares = ["redirect-to-https"];
                  service = "netbird-dashboard";
                  priority = 1;
                };
                netbird-dashboard = {
                  rule = "Host(`${cfg.domain}`)";
                  entryPoints = ["websecure"];
                  service = "netbird-dashboard";
                  tls.certResolver = "letsencrypt";
                  priority = 10;
                };
                netbird-backend = {
                  rule = "Host(`${cfg.domain}`) && (PathPrefix(`/relay`) || PathPrefix(`/ws-proxy/`) || PathPrefix(`/api`) || PathPrefix(`/oauth2`))";
                  entryPoints = ["websecure"];
                  service = "netbird-backend";
                  tls.certResolver = "letsencrypt";
                  priority = 100;
                };
                # Include ProxyService so remote proxies can reach management over TLS.
                netbird-grpc = {
                  rule = "Host(`${cfg.domain}`) && (PathPrefix(`/signalexchange.SignalExchange/`) || PathPrefix(`/management.ManagementService/`) || PathPrefix(`/management.ProxyService/`))";
                  entryPoints = ["websecure"];
                  service = "netbird-grpc";
                  tls.certResolver = "letsencrypt";
                  priority = 100;
                };
              };
              services = {
                netbird-dashboard.loadBalancer.servers = [
                  {url = "http://127.0.0.1:${toString dashboardPort}";}
                ];
                netbird-backend.loadBalancer.servers = [
                  {url = "http://127.0.0.1:${toString listenPort}";}
                ];
                netbird-grpc.loadBalancer.servers = [
                  {url = "h2c://127.0.0.1:${toString listenPort}";}
                ];
                netbird-proxy-acme.loadBalancer.servers = [
                  {url = "http://127.0.0.1:8085";}
                ];
              };
            };
          }
          // lib.optionalAttrs cfg.enableProxyPassthrough {
            tcp = {
              routers.proxy-passthrough = {
                entryPoints = ["websecure"];
                rule = "HostSNI(`*`)";
                service = "proxy-tls";
                priority = 1;
                tls.passthrough = true;
              };
              services.proxy-tls.loadBalancer.servers = [
                {address = "127.0.0.1:8443";}
              ];
            };
          };
      };

      systemd.services.netbird-server = {
        description = "NetBird combined management/signal/relay/STUN server";
        documentation = ["https://docs.netbird.io/selfhosted/selfhosted-quickstart"];
        after = ["network-online.target" "traefik.service"];
        wants = ["network-online.target"];
        wantedBy = ["multi-user.target"];

        # Allow Alchemy /api/setup to mint an initial admin PAT (create_pat: true).
        environment.NB_SETUP_PAT_ENABLED = "true";

        serviceConfig = {
          Type = "simple";
          User = "netbird";
          Group = "netbird";
          ExecStartPre = ["${lib.getExe prepareConfig}"];
          ExecStart = "${lib.getExe cfg.package} --config ${runtimeDir}/config.yaml";
          Restart = "on-failure";
          RestartSec = "5s";

          StateDirectory = "netbird";
          StateDirectoryMode = "0750";
          RuntimeDirectory = "netbird-server";
          RuntimeDirectoryMode = "0750";
          WorkingDirectory = stateDir;

          # Hardening
          NoNewPrivileges = true;
          PrivateTmp = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          ProtectKernelTunables = true;
          ProtectKernelModules = true;
          ProtectControlGroups = true;
          ProtectHostname = true;
          ProtectClock = true;
          LockPersonality = true;
          MemoryDenyWriteExecute = true;
          RestrictSUIDSGID = true;
          RestrictRealtime = true;
          RestrictNamespaces = true;
          RemoveIPC = true;
          SystemCallArchitectures = "native";
          ReadWritePaths = [stateDir runtimeDir];
          CapabilityBoundingSet = "";
          AmbientCapabilities = "";
        };
      };
    };
  };
}
