import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Conflict
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withConflictError),
		[{ status: 409 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export type AgentNetworkAccessLogSessionsGetRequestSortBy =
	| "timestamp"
	| "started_at"
	| "cost_usd"
	| "total_tokens"
	| "duration"
	| "request_count"
	| "status_code"
	| "user_id"
	| "decision";
export const AgentNetworkAccessLogSessionsGetRequestSortBy = /*@__PURE__*/ S.String;

export type AgentNetworkAccessLogSessionsGetRequestSortOrder = "asc" | "desc";
export const AgentNetworkAccessLogSessionsGetRequestSortOrder = /*@__PURE__*/ S.String;

export type AgentNetworkAccessLogSessionsGetRequestGroupIdList = ReadonlyArray<string>;
export const AgentNetworkAccessLogSessionsGetRequestGroupIdList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogSessionsGetRequestGroupIdList>;

export type AgentNetworkAccessLogSessionsGetRequestProviderIdList = ReadonlyArray<string>;
export const AgentNetworkAccessLogSessionsGetRequestProviderIdList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogSessionsGetRequestProviderIdList>;

export type AgentNetworkAccessLogSessionsGetRequestModelList = ReadonlyArray<string>;
export const AgentNetworkAccessLogSessionsGetRequestModelList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogSessionsGetRequestModelList>;

export interface AgentNetworkAccessLogSessionsGetRequest {
	/** Page number for pagination (1-indexed). */
	page?: number;
	/** Number of sessions per page (max 100). */
	page_size?: number;
	/** Session-level field to sort by. "timestamp" is the session's last activity, "started_at" its first. */
	sort_by?: AgentNetworkAccessLogSessionsGetRequestSortBy;
	/** Sort order (ascending or descending). */
	sort_order?: AgentNetworkAccessLogSessionsGetRequestSortOrder;
	/** General search across log ID, host, path, model, and user email/name. */
	search?: string;
	/** Filter by authenticated user ID. */
	user_id?: string;
	/** Filter to a single conversation / coding session id. */
	session_id?: string;
	/** Filter by authorising group id. Repeat for multiple (matches any). */
	group_id?: AgentNetworkAccessLogSessionsGetRequestGroupIdList;
	/** Filter by resolved provider id. Repeat for multiple (matches any). */
	provider_id?: AgentNetworkAccessLogSessionsGetRequestProviderIdList;
	/** Filter by model. Repeat for multiple (matches any). */
	model?: AgentNetworkAccessLogSessionsGetRequestModelList;
	/** Filter by policy decision (e.g. allow, deny). */
	decision?: string;
	/** Filter by request path prefix (matches entries whose path starts with this value). */
	path?: string;
	/** Filter by timestamp >= start_date (RFC3339 format). */
	start_date?: string;
	/** Filter by timestamp <= end_date (RFC3339 format). */
	end_date?: string;
}
export const AgentNetworkAccessLogSessionsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		page: S.optional(S.Number.pipe(T.Query())),
		page_size: S.optional(S.Number.pipe(T.Query())),
		sort_by: S.optional(AgentNetworkAccessLogSessionsGetRequestSortBy.pipe(T.Query())),
		sort_order: S.optional(AgentNetworkAccessLogSessionsGetRequestSortOrder.pipe(T.Query())),
		search: S.optional(S.String.pipe(T.Query())),
		user_id: S.optional(S.String.pipe(T.Query())),
		session_id: S.optional(S.String.pipe(T.Query())),
		group_id: S.optional(AgentNetworkAccessLogSessionsGetRequestGroupIdList.pipe(T.Query())),
		provider_id: S.optional(AgentNetworkAccessLogSessionsGetRequestProviderIdList.pipe(T.Query())),
		model: S.optional(AgentNetworkAccessLogSessionsGetRequestModelList.pipe(T.Query())),
		decision: S.optional(S.String.pipe(T.Query())),
		path: S.optional(S.String.pipe(T.Query())),
		start_date: S.optional(S.String.pipe(T.Query())),
		end_date: S.optional(S.String.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/access-log-sessions", code: 200 })),
).annotate({
	identifier: "AgentNetworkAccessLogSessionsGetRequest",
}) as any as S.Schema<AgentNetworkAccessLogSessionsGetRequest>;

/** Union of the authorising group ids across the session's entries. */
export type AgentNetworkAccessLogSessionGroupIdsList = ReadonlyArray<string>;
export const AgentNetworkAccessLogSessionGroupIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogSessionGroupIdsList>;

/** Distinct LLM provider vendors seen in the session. */
export type AgentNetworkAccessLogSessionProvidersList = ReadonlyArray<string>;
export const AgentNetworkAccessLogSessionProvidersList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogSessionProvidersList>;

/** Distinct models seen in the session. */
export type AgentNetworkAccessLogSessionModelsList = ReadonlyArray<string>;
export const AgentNetworkAccessLogSessionModelsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogSessionModelsList>;

/** NetBird group ids that authorised the request (the caller's groups intersected with the policy's source groups). */
export type AgentNetworkAccessLogGroupIdsList = ReadonlyArray<string>;
export const AgentNetworkAccessLogGroupIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogGroupIdsList>;

/** One per-request agent-network (LLM) access log entry with flattened, queryable LLM dimensions. */
export interface AgentNetworkAccessLog {
	/** Unique identifier for the access log entry. */
	id: string;
	/** ID of the synthesised agent-network service that handled the request. */
	service_id: string;
	/** Timestamp when the request was made. */
	timestamp: string;
	/** HTTP status code returned upstream. */
	status_code: number;
	/** Duration of the request in milliseconds. */
	duration_ms: number;
	/** NetBird user id of the authenticated caller, if applicable. */
	user_id?: string;
	/** Source IP of the request. Empty when log collection is disabled. */
	source_ip?: string;
	/** HTTP method of the request. */
	method?: string;
	/** Upstream host the request was routed to. Empty when log collection is disabled. */
	host?: string;
	/** Request path. Empty when log collection is disabled. */
	path?: string;
	/** LLM provider vendor (e.g. openai, anthropic). */
	provider?: string;
	/** Requested LLM model. */
	model?: string;
	/** Conversation / coding-session identifier that groups related requests. Sourced from the client's session marker (e.g. OpenAI Codex client_metadata.session_id, Claude Code metadata.user_id). Empty for clients that send none. */
	session_id?: string;
	/** NetBird agent-network provider id that served the request. */
	resolved_provider_id?: string;
	/** Agent-network policy id that authorised (or denied) the request. */
	selected_policy_id?: string;
	/** Policy decision for the request (e.g. allow, deny). */
	decision?: string;
	/** Raw deny reason code when the request was blocked (e.g. llm_policy.token_cap_exceeded). */
	deny_reason?: string;
	/** Input (prompt) tokens consumed. */
	input_tokens: number;
	/** Output (completion) tokens produced. */
	output_tokens: number;
	/** Total tokens consumed. */
	total_tokens: number;
	/** Estimated USD cost of the request. */
	cost_usd: number;
	/** Whether the request was a streaming completion. */
	stream?: boolean;
	/** NetBird group ids that authorised the request (the caller's groups intersected with the policy's source groups). */
	group_ids?: AgentNetworkAccessLogGroupIdsList;
	/** Captured request prompt. Present only when prompt collection is enabled. */
	request_prompt?: string;
	/** Captured response completion. Present only when prompt collection is enabled. */
	response_completion?: string;
}
export const AgentNetworkAccessLog = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		service_id: S.String,
		timestamp: S.String,
		status_code: S.Number,
		duration_ms: S.Number,
		user_id: S.optional(S.String),
		source_ip: S.optional(S.String),
		method: S.optional(S.String),
		host: S.optional(S.String),
		path: S.optional(S.String),
		provider: S.optional(S.String),
		model: S.optional(S.String),
		session_id: S.optional(S.String),
		resolved_provider_id: S.optional(S.String),
		selected_policy_id: S.optional(S.String),
		decision: S.optional(S.String),
		deny_reason: S.optional(S.String),
		input_tokens: S.Number,
		output_tokens: S.Number,
		total_tokens: S.Number,
		cost_usd: S.Number,
		stream: S.optional(S.Boolean),
		group_ids: S.optional(AgentNetworkAccessLogGroupIdsList),
		request_prompt: S.optional(S.String),
		response_completion: S.optional(S.String),
	}),
).annotate({ identifier: "AgentNetworkAccessLog" }) as any as S.Schema<AgentNetworkAccessLog>;

/** The session's access-log entries, oldest first. */
export type AgentNetworkAccessLogSessionEntriesList = ReadonlyArray<AgentNetworkAccessLog>;
export const AgentNetworkAccessLogSessionEntriesList = /*@__PURE__*/ S.Array(
	AgentNetworkAccessLog,
) as any as S.Schema<AgentNetworkAccessLogSessionEntriesList>;

/** A session-grouped view of agent-network access logs — all requests sharing a session id (or a single session-less request) folded into one summary plus its ordered entries. */
export interface AgentNetworkAccessLogSession {
	/** Conversation / coding-session identifier shared by the entries. Empty for a session-less (singleton) request grouped on its own id. */
	session_id?: string;
	/** NetBird user id of the session's caller. */
	user_id?: string;
	/** Union of the authorising group ids across the session's entries. */
	group_ids?: AgentNetworkAccessLogSessionGroupIdsList;
	/** Timestamp of the session's earliest request. */
	started_at: string;
	/** Timestamp of the session's latest request. */
	ended_at: string;
	/** Number of requests in the session. */
	request_count: number;
	/** Total input (prompt) tokens across the session. */
	input_tokens: number;
	/** Total output (completion) tokens across the session. */
	output_tokens: number;
	/** Total tokens across the session. */
	total_tokens: number;
	/** Total estimated USD cost across the session. */
	cost_usd: number;
	/** Distinct LLM provider vendors seen in the session. */
	providers?: AgentNetworkAccessLogSessionProvidersList;
	/** Distinct models seen in the session. */
	models?: AgentNetworkAccessLogSessionModelsList;
	/** Session decision — "deny" if any request was denied, otherwise "allow". */
	decision: string;
	/** The session's access-log entries, oldest first. */
	entries: AgentNetworkAccessLogSessionEntriesList;
}
export const AgentNetworkAccessLogSession = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		session_id: S.optional(S.String),
		user_id: S.optional(S.String),
		group_ids: S.optional(AgentNetworkAccessLogSessionGroupIdsList),
		started_at: S.String,
		ended_at: S.String,
		request_count: S.Number,
		input_tokens: S.Number,
		output_tokens: S.Number,
		total_tokens: S.Number,
		cost_usd: S.Number,
		providers: S.optional(AgentNetworkAccessLogSessionProvidersList),
		models: S.optional(AgentNetworkAccessLogSessionModelsList),
		decision: S.String,
		entries: AgentNetworkAccessLogSessionEntriesList,
	}),
).annotate({ identifier: "AgentNetworkAccessLogSession" }) as any as S.Schema<AgentNetworkAccessLogSession>;

/** List of session-grouped agent-network access logs. */
export type AgentNetworkAccessLogSessionsResponseDataList = ReadonlyArray<AgentNetworkAccessLogSession>;
export const AgentNetworkAccessLogSessionsResponseDataList = /*@__PURE__*/ S.Array(
	AgentNetworkAccessLogSession,
) as any as S.Schema<AgentNetworkAccessLogSessionsResponseDataList>;

export interface AgentNetworkAccessLogSessionsResponse {
	/** List of session-grouped agent-network access logs. */
	data: AgentNetworkAccessLogSessionsResponseDataList;
	/** Current page number. */
	page: number;
	/** Number of sessions per page. */
	page_size: number;
	/** Total number of sessions matching the filter. */
	total_records: number;
	/** Total number of pages available. */
	total_pages: number;
}
export const AgentNetworkAccessLogSessionsResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		data: AgentNetworkAccessLogSessionsResponseDataList,
		page: S.Number,
		page_size: S.Number,
		total_records: S.Number,
		total_pages: S.Number,
	}),
).annotate({
	identifier: "AgentNetworkAccessLogSessionsResponse",
}) as any as S.Schema<AgentNetworkAccessLogSessionsResponse>;

export type AgentNetworkAccessLogsGetRequestSortBy =
	| "timestamp"
	| "model"
	| "provider"
	| "status_code"
	| "duration"
	| "cost_usd"
	| "total_tokens"
	| "user_id"
	| "decision";
export const AgentNetworkAccessLogsGetRequestSortBy = /*@__PURE__*/ S.String;

export type AgentNetworkAccessLogsGetRequestSortOrder = "asc" | "desc";
export const AgentNetworkAccessLogsGetRequestSortOrder = /*@__PURE__*/ S.String;

export type AgentNetworkAccessLogsGetRequestGroupIdList = ReadonlyArray<string>;
export const AgentNetworkAccessLogsGetRequestGroupIdList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogsGetRequestGroupIdList>;

export type AgentNetworkAccessLogsGetRequestProviderIdList = ReadonlyArray<string>;
export const AgentNetworkAccessLogsGetRequestProviderIdList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogsGetRequestProviderIdList>;

export type AgentNetworkAccessLogsGetRequestModelList = ReadonlyArray<string>;
export const AgentNetworkAccessLogsGetRequestModelList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkAccessLogsGetRequestModelList>;

export interface AgentNetworkAccessLogsGetRequest {
	/** Page number for pagination (1-indexed). */
	page?: number;
	/** Number of items per page (max 100). */
	page_size?: number;
	/** Field to sort by. */
	sort_by?: AgentNetworkAccessLogsGetRequestSortBy;
	/** Sort order (ascending or descending). */
	sort_order?: AgentNetworkAccessLogsGetRequestSortOrder;
	/** General search across log ID, host, path, model, and user email/name. */
	search?: string;
	/** Filter by authenticated user ID. */
	user_id?: string;
	/** Filter to a single conversation / coding session id (groups all requests of one session). */
	session_id?: string;
	/** Filter by authorising group id. Repeat for multiple (matches any). */
	group_id?: AgentNetworkAccessLogsGetRequestGroupIdList;
	/** Filter by resolved provider id. Repeat for multiple (matches any). */
	provider_id?: AgentNetworkAccessLogsGetRequestProviderIdList;
	/** Filter by model. Repeat for multiple (matches any). */
	model?: AgentNetworkAccessLogsGetRequestModelList;
	/** Filter by policy decision (e.g. allow, deny). */
	decision?: string;
	/** Filter by request path prefix (matches entries whose path starts with this value). */
	path?: string;
	/** Filter by timestamp >= start_date (RFC3339 format). */
	start_date?: string;
	/** Filter by timestamp <= end_date (RFC3339 format). */
	end_date?: string;
}
export const AgentNetworkAccessLogsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		page: S.optional(S.Number.pipe(T.Query())),
		page_size: S.optional(S.Number.pipe(T.Query())),
		sort_by: S.optional(AgentNetworkAccessLogsGetRequestSortBy.pipe(T.Query())),
		sort_order: S.optional(AgentNetworkAccessLogsGetRequestSortOrder.pipe(T.Query())),
		search: S.optional(S.String.pipe(T.Query())),
		user_id: S.optional(S.String.pipe(T.Query())),
		session_id: S.optional(S.String.pipe(T.Query())),
		group_id: S.optional(AgentNetworkAccessLogsGetRequestGroupIdList.pipe(T.Query())),
		provider_id: S.optional(AgentNetworkAccessLogsGetRequestProviderIdList.pipe(T.Query())),
		model: S.optional(AgentNetworkAccessLogsGetRequestModelList.pipe(T.Query())),
		decision: S.optional(S.String.pipe(T.Query())),
		path: S.optional(S.String.pipe(T.Query())),
		start_date: S.optional(S.String.pipe(T.Query())),
		end_date: S.optional(S.String.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/access-logs", code: 200 })),
).annotate({ identifier: "AgentNetworkAccessLogsGetRequest" }) as any as S.Schema<AgentNetworkAccessLogsGetRequest>;

/** List of agent-network access log entries. */
export type AgentNetworkAccessLogsResponseDataList = ReadonlyArray<AgentNetworkAccessLog>;
export const AgentNetworkAccessLogsResponseDataList = /*@__PURE__*/ S.Array(
	AgentNetworkAccessLog,
) as any as S.Schema<AgentNetworkAccessLogsResponseDataList>;

export interface AgentNetworkAccessLogsResponse {
	/** List of agent-network access log entries. */
	data: AgentNetworkAccessLogsResponseDataList;
	/** Current page number. */
	page: number;
	/** Number of items per page. */
	page_size: number;
	/** Total number of log records matching the filter. */
	total_records: number;
	/** Total number of pages available. */
	total_pages: number;
}
export const AgentNetworkAccessLogsResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		data: AgentNetworkAccessLogsResponseDataList,
		page: S.Number,
		page_size: S.Number,
		total_records: S.Number,
		total_pages: S.Number,
	}),
).annotate({ identifier: "AgentNetworkAccessLogsResponse" }) as any as S.Schema<AgentNetworkAccessLogsResponse>;

export interface AgentNetworkBudgetRulesGetRequest {}
export const AgentNetworkBudgetRulesGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/budget-rules", code: 200 })),
).annotate({ identifier: "AgentNetworkBudgetRulesGetRequest" }) as any as S.Schema<AgentNetworkBudgetRulesGetRequest>;

/** NetBird group ids the rule binds. Empty plus empty target_users means account-wide. */
export type AgentNetworkBudgetRuleTargetGroupsList = ReadonlyArray<string>;
export const AgentNetworkBudgetRuleTargetGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkBudgetRuleTargetGroupsList>;

/** NetBird user ids the rule binds directly. */
export type AgentNetworkBudgetRuleTargetUsersList = ReadonlyArray<string>;
export const AgentNetworkBudgetRuleTargetUsersList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkBudgetRuleTargetUsersList>;

/** Per-policy token cap. `group_cap` is applied to each source group independently — every group in the policy's `source_groups` gets its own bucket of this size. `user_cap` is applied independently to each individual user. Caps reset to zero at the start of each window. */
export interface AgentNetworkPolicyTokenLimit {
	enabled: boolean;
	/** Tokens allowed per source group within the window (each group has its own bucket of this size). 0 means uncapped. */
	group_cap: number;
	/** Tokens allowed per individual user within the window. 0 means uncapped. */
	user_cap: number;
	/** Reset frequency in seconds. The cap counter resets to zero at the start of each window. Minimum 60 (one minute) when the limit is enabled. */
	window_seconds: number;
}
export const AgentNetworkPolicyTokenLimit = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_cap: S.Number,
		user_cap: S.Number,
		window_seconds: S.Number,
	}),
).annotate({ identifier: "AgentNetworkPolicyTokenLimit" }) as any as S.Schema<AgentNetworkPolicyTokenLimit>;

/** Per-policy USD spend cap. `group_cap_usd` is applied to each source group independently — every group in the policy's `source_groups` gets its own bucket of this size. `user_cap_usd` is applied independently to each individual user. Caps reset to zero at the start of each window. */
export interface AgentNetworkPolicyBudgetLimit {
	enabled: boolean;
	/** USD allowed per source group within the window (each group has its own bucket of this size). 0 means uncapped. */
	group_cap_usd: number;
	/** USD allowed per individual user within the window. 0 means uncapped. */
	user_cap_usd: number;
	/** Reset frequency in seconds. Caps reset at the start of each window. Minimum 60 (one minute) when the limit is enabled. */
	window_seconds: number;
}
export const AgentNetworkPolicyBudgetLimit = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_cap_usd: S.Number,
		user_cap_usd: S.Number,
		window_seconds: S.Number,
	}),
).annotate({ identifier: "AgentNetworkPolicyBudgetLimit" }) as any as S.Schema<AgentNetworkPolicyBudgetLimit>;

/** Token and budget caps attached directly to the policy. These compose with any guardrail-level checks. */
export interface AgentNetworkPolicyLimits {
	token_limit: AgentNetworkPolicyTokenLimit;
	budget_limit: AgentNetworkPolicyBudgetLimit;
}
export const AgentNetworkPolicyLimits = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		token_limit: AgentNetworkPolicyTokenLimit,
		budget_limit: AgentNetworkPolicyBudgetLimit,
	}),
).annotate({ identifier: "AgentNetworkPolicyLimits" }) as any as S.Schema<AgentNetworkPolicyLimits>;

/** Account-level budget rule. A limit-only rule bound to groups and/or users that applies across all policies as a min-wins ceiling. Empty targets means it applies to every caller. */
export interface AgentNetworkBudgetRule {
	/** Budget rule ID. */
	id: string;
	/** Display name for the budget rule. */
	name: string;
	/** Whether the rule is enforced. */
	enabled: boolean;
	/** NetBird group ids the rule binds. Empty plus empty target_users means account-wide. */
	target_groups: AgentNetworkBudgetRuleTargetGroupsList;
	/** NetBird user ids the rule binds directly. */
	target_users: AgentNetworkBudgetRuleTargetUsersList;
	limits: AgentNetworkPolicyLimits;
	created_at: string;
	updated_at: string;
}
export const AgentNetworkBudgetRule = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		enabled: S.Boolean,
		target_groups: AgentNetworkBudgetRuleTargetGroupsList,
		target_users: AgentNetworkBudgetRuleTargetUsersList,
		limits: AgentNetworkPolicyLimits,
		created_at: S.String,
		updated_at: S.String,
	}),
).annotate({ identifier: "AgentNetworkBudgetRule" }) as any as S.Schema<AgentNetworkBudgetRule>;

export type AgentNetworkBudgetRulesGetResponseBodyList = ReadonlyArray<AgentNetworkBudgetRule>;
export const AgentNetworkBudgetRulesGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkBudgetRule,
) as any as S.Schema<AgentNetworkBudgetRulesGetResponseBodyList>;

export type AgentNetworkBudgetRulesGetResponse = AgentNetworkBudgetRulesGetResponseBodyList;
export const AgentNetworkBudgetRulesGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkBudgetRulesGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "AgentNetworkBudgetRulesGetResponse" }) as any as S.Schema<AgentNetworkBudgetRulesGetResponse>;

/** NetBird group ids the rule binds. Empty plus empty target_users means account-wide. */
export type AgentNetworkBudgetRulesPostRequestTargetGroupsList = ReadonlyArray<string>;
export const AgentNetworkBudgetRulesPostRequestTargetGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkBudgetRulesPostRequestTargetGroupsList>;

/** NetBird user ids the rule binds directly. */
export type AgentNetworkBudgetRulesPostRequestTargetUsersList = ReadonlyArray<string>;
export const AgentNetworkBudgetRulesPostRequestTargetUsersList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkBudgetRulesPostRequestTargetUsersList>;

export interface AgentNetworkBudgetRulesPostRequest {
	/** Display name for the budget rule. */
	name: string;
	/** Whether the rule is enforced. Defaults to true on create. */
	enabled?: boolean;
	/** NetBird group ids the rule binds. Empty plus empty target_users means account-wide. */
	target_groups?: AgentNetworkBudgetRulesPostRequestTargetGroupsList;
	/** NetBird user ids the rule binds directly. */
	target_users?: AgentNetworkBudgetRulesPostRequestTargetUsersList;
	limits: AgentNetworkPolicyLimits;
}
export const AgentNetworkBudgetRulesPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		enabled: S.optional(S.Boolean),
		target_groups: S.optional(AgentNetworkBudgetRulesPostRequestTargetGroupsList),
		target_users: S.optional(AgentNetworkBudgetRulesPostRequestTargetUsersList),
		limits: AgentNetworkPolicyLimits,
	}).pipe(T.Http({ method: "POST", uri: "/api/agent-network/budget-rules", code: 200 })),
).annotate({ identifier: "AgentNetworkBudgetRulesPostRequest" }) as any as S.Schema<AgentNetworkBudgetRulesPostRequest>;

export interface AgentNetworkBudgetRulesRuleIdDeleteRequest {
	/** The unique identifier of a budget rule */
	ruleId: string;
}
export const AgentNetworkBudgetRulesRuleIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ruleId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/agent-network/budget-rules/{ruleId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkBudgetRulesRuleIdDeleteRequest",
}) as any as S.Schema<AgentNetworkBudgetRulesRuleIdDeleteRequest>;

export type AgentNetworkBudgetRulesRuleIdDeleteResponse = unknown;
export const AgentNetworkBudgetRulesRuleIdDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "AgentNetworkBudgetRulesRuleIdDeleteResponse",
}) as any as S.Schema<AgentNetworkBudgetRulesRuleIdDeleteResponse>;

export interface AgentNetworkBudgetRulesRuleIdGetRequest {
	/** The unique identifier of a budget rule */
	ruleId: string;
}
export const AgentNetworkBudgetRulesRuleIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ruleId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/budget-rules/{ruleId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkBudgetRulesRuleIdGetRequest",
}) as any as S.Schema<AgentNetworkBudgetRulesRuleIdGetRequest>;

/** NetBird group ids the rule binds. Empty plus empty target_users means account-wide. */
export type AgentNetworkBudgetRulesRuleIdPutRequestTargetGroupsList = ReadonlyArray<string>;
export const AgentNetworkBudgetRulesRuleIdPutRequestTargetGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkBudgetRulesRuleIdPutRequestTargetGroupsList>;

/** NetBird user ids the rule binds directly. */
export type AgentNetworkBudgetRulesRuleIdPutRequestTargetUsersList = ReadonlyArray<string>;
export const AgentNetworkBudgetRulesRuleIdPutRequestTargetUsersList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkBudgetRulesRuleIdPutRequestTargetUsersList>;

export interface AgentNetworkBudgetRulesRuleIdPutRequest {
	/** The unique identifier of a budget rule */
	ruleId: string;
	/** Display name for the budget rule. */
	name: string;
	/** Whether the rule is enforced. Defaults to true on create. */
	enabled?: boolean;
	/** NetBird group ids the rule binds. Empty plus empty target_users means account-wide. */
	target_groups?: AgentNetworkBudgetRulesRuleIdPutRequestTargetGroupsList;
	/** NetBird user ids the rule binds directly. */
	target_users?: AgentNetworkBudgetRulesRuleIdPutRequestTargetUsersList;
	limits: AgentNetworkPolicyLimits;
}
export const AgentNetworkBudgetRulesRuleIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ruleId: S.String.pipe(T.Label()),
		name: S.String,
		enabled: S.optional(S.Boolean),
		target_groups: S.optional(AgentNetworkBudgetRulesRuleIdPutRequestTargetGroupsList),
		target_users: S.optional(AgentNetworkBudgetRulesRuleIdPutRequestTargetUsersList),
		limits: AgentNetworkPolicyLimits,
	}).pipe(T.Http({ method: "PUT", uri: "/api/agent-network/budget-rules/{ruleId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkBudgetRulesRuleIdPutRequest",
}) as any as S.Schema<AgentNetworkBudgetRulesRuleIdPutRequest>;

export interface AgentNetworkCatalogProvidersGetRequest {}
export const AgentNetworkCatalogProvidersGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/catalog/providers", code: 200 })),
).annotate({
	identifier: "AgentNetworkCatalogProvidersGetRequest",
}) as any as S.Schema<AgentNetworkCatalogProvidersGetRequest>;

/** Presentation grouping for the provider Select on the dashboard. "provider" — first-party vendor API (OpenAI, Anthropic, …); the upstream is the model itself. "gateway" — routing/aggregation layer in front of multiple providers (LiteLLM, Portkey, …); typically pairs with NetBird identity stamping. "custom" — generic OpenAI-compatible self-hosted endpoint catch-all. */
export type AgentNetworkCatalogProviderKind = "provider" | "gateway" | "custom";
export const AgentNetworkCatalogProviderKind = /*@__PURE__*/ S.String;

/** One optional per-provider routing/config header surfaced on the dashboard. Operator-typed value lives on the provider record's `extra_values` map keyed by `name`. UI copy (input label, helper line, tooltip) is owned by the dashboard, keyed by `name`. */
export interface AgentNetworkCatalogExtraHeader {
	/** Wire header name the proxy stamps with the operator-typed value. */
	name: string;
}
export const AgentNetworkCatalogExtraHeader = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
	}),
).annotate({ identifier: "AgentNetworkCatalogExtraHeader" }) as any as S.Schema<AgentNetworkCatalogExtraHeader>;

/** Catalog-declared list of optional per-provider routing/config headers the proxy stamps on every upstream request. Each entry surfaces an input on the dashboard's provider modal (one per item, labeled with `label`). Operators fill any subset; values land on the provider record's `extra_values` map keyed by `name`. Used by gateways like Portkey for `x-portkey-config: pc-...` (saved-config id resolving upstream provider + virtual key). */
export type AgentNetworkCatalogProviderExtraHeadersList = ReadonlyArray<AgentNetworkCatalogExtraHeader>;
export const AgentNetworkCatalogProviderExtraHeadersList = /*@__PURE__*/ S.Array(
	AgentNetworkCatalogExtraHeader,
) as any as S.Schema<AgentNetworkCatalogProviderExtraHeadersList>;

/** HeaderPair identity-injection shape — separate per-dimension headers (LiteLLM-style, Bifrost). */
export interface AgentNetworkCatalogHeaderPairInjection {
	/** When true, the wire header names are operator-overridable per provider record (Bifrost). When false, the catalog values are authoritative (LiteLLM and similar gateways with a fixed wire protocol). */
	customizable: boolean;
	/** Wire header name for the caller's display identity. Default placeholder when `customizable` is true. */
	end_user_id_header: string;
	/** Wire header name for the caller's groups CSV. Default placeholder when `customizable` is true. */
	tags_header: string;
}
export const AgentNetworkCatalogHeaderPairInjection = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		customizable: S.Boolean,
		end_user_id_header: S.String,
		tags_header: S.String,
	}),
).annotate({
	identifier: "AgentNetworkCatalogHeaderPairInjection",
}) as any as S.Schema<AgentNetworkCatalogHeaderPairInjection>;

/** JSONMetadata identity-injection shape — one wire header carrying a JSON object whose keys label each dimension (Portkey-style, Cloudflare AI Gateway). */
export interface AgentNetworkCatalogJSONMetadataInjection {
	/** When true, the JSON keys are operator-overridable per provider record (Cloudflare). The wire header itself stays catalog-owned. When false, the catalog values are authoritative (Portkey and similar gateways with a fixed JSON schema). */
	customizable: boolean;
	/** Wire header name carrying the JSON metadata payload. Catalog-owned (not customizable per provider record). */
	header: string;
	/** JSON key for the caller's display identity. Default placeholder when `customizable` is true. */
	user_key: string;
	/** JSON key for the caller's groups CSV. Default placeholder when `customizable` is true. */
	groups_key: string;
}
export const AgentNetworkCatalogJSONMetadataInjection = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		customizable: S.Boolean,
		header: S.String,
		user_key: S.String,
		groups_key: S.String,
	}),
).annotate({
	identifier: "AgentNetworkCatalogJSONMetadataInjection",
}) as any as S.Schema<AgentNetworkCatalogJSONMetadataInjection>;

/** Catalog-declared identity-injection shape. Present when this provider supports stamping the caller's NetBird identity onto upstream requests. Exactly one of `header_pair` or `json_metadata` is set per provider entry. The dashboard reads the `customizable` flag on whichever shape is present to decide whether to surface the labels as editable inputs (true → editable with the catalog values shown as placeholders; false → fixed and read-only). */
export interface AgentNetworkCatalogIdentityInjection {
	header_pair?: AgentNetworkCatalogHeaderPairInjection;
	json_metadata?: AgentNetworkCatalogJSONMetadataInjection;
}
export const AgentNetworkCatalogIdentityInjection = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		header_pair: S.optional(AgentNetworkCatalogHeaderPairInjection),
		json_metadata: S.optional(AgentNetworkCatalogJSONMetadataInjection),
	}),
).annotate({
	identifier: "AgentNetworkCatalogIdentityInjection",
}) as any as S.Schema<AgentNetworkCatalogIdentityInjection>;

export interface AgentNetworkCatalogModel {
	/** Catalog model identifier as exposed by the upstream provider. */
	id: string;
	/** Human-friendly model name for the dashboard. */
	label: string;
	/** Input token price per 1k tokens, in USD. */
	input_per_1k: number;
	/** Output token price per 1k tokens, in USD. */
	output_per_1k: number;
	/** Maximum context window in tokens. */
	context_window: number;
}
export const AgentNetworkCatalogModel = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		label: S.String,
		input_per_1k: S.Number,
		output_per_1k: S.Number,
		context_window: S.Number,
	}),
).annotate({ identifier: "AgentNetworkCatalogModel" }) as any as S.Schema<AgentNetworkCatalogModel>;

/** Catalog models available for this provider. */
export type AgentNetworkCatalogProviderModelsList = ReadonlyArray<AgentNetworkCatalogModel>;
export const AgentNetworkCatalogProviderModelsList = /*@__PURE__*/ S.Array(
	AgentNetworkCatalogModel,
) as any as S.Schema<AgentNetworkCatalogProviderModelsList>;

export interface AgentNetworkCatalogProvider {
	/** Catalog provider identifier (referenced by AgentNetworkProvider.provider_id). */
	id: string;
	/** Display name for the provider. */
	name: string;
	/** Short description shown in the provider picker. */
	description: string;
	/** Default upstream host suggested when adding a provider of this type. */
	default_host: string;
	/** Template the proxy uses to inject the API key (the literal string ${API_KEY} is replaced at request time). */
	auth_header_template: string;
	/** Default Content-Type for upstream requests. */
	default_content_type: string;
	/** Hex brand color used to render the provider badge in the dashboard. */
	brand_color: string;
	/** Presentation grouping for the provider Select on the dashboard. "provider" — first-party vendor API (OpenAI, Anthropic, …); the upstream is the model itself. "gateway" — routing/aggregation layer in front of multiple providers (LiteLLM, Portkey, …); typically pairs with NetBird identity stamping. "custom" — generic OpenAI-compatible self-hosted endpoint catch-all. */
	kind: AgentNetworkCatalogProviderKind;
	/** Catalog-declared list of optional per-provider routing/config headers the proxy stamps on every upstream request. Each entry surfaces an input on the dashboard's provider modal (one per item, labeled with `label`). Operators fill any subset; values land on the provider record's `extra_values` map keyed by `name`. Used by gateways like Portkey for `x-portkey-config: pc-...` (saved-config id resolving upstream provider + virtual key). */
	extra_headers?: AgentNetworkCatalogProviderExtraHeadersList;
	identity_injection?: AgentNetworkCatalogIdentityInjection;
	/** Catalog models available for this provider. */
	models: AgentNetworkCatalogProviderModelsList;
}
export const AgentNetworkCatalogProvider = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		default_host: S.String,
		auth_header_template: S.String,
		default_content_type: S.String,
		brand_color: S.String,
		kind: AgentNetworkCatalogProviderKind,
		extra_headers: S.optional(AgentNetworkCatalogProviderExtraHeadersList),
		identity_injection: S.optional(AgentNetworkCatalogIdentityInjection),
		models: AgentNetworkCatalogProviderModelsList,
	}),
).annotate({ identifier: "AgentNetworkCatalogProvider" }) as any as S.Schema<AgentNetworkCatalogProvider>;

export type AgentNetworkCatalogProvidersGetResponseBodyList = ReadonlyArray<AgentNetworkCatalogProvider>;
export const AgentNetworkCatalogProvidersGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkCatalogProvider,
) as any as S.Schema<AgentNetworkCatalogProvidersGetResponseBodyList>;

export type AgentNetworkCatalogProvidersGetResponse = AgentNetworkCatalogProvidersGetResponseBodyList;
export const AgentNetworkCatalogProvidersGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkCatalogProvidersGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "AgentNetworkCatalogProvidersGetResponse",
}) as any as S.Schema<AgentNetworkCatalogProvidersGetResponse>;

export interface AgentNetworkConsumptionGetRequest {}
export const AgentNetworkConsumptionGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/consumption", code: 200 })),
).annotate({ identifier: "AgentNetworkConsumptionGetRequest" }) as any as S.Schema<AgentNetworkConsumptionGetRequest>;

/** Whether this row counts a single end user or a single source group across every member. */
export type AgentNetworkConsumptionDimensionKind = "user" | "group";
export const AgentNetworkConsumptionDimensionKind = /*@__PURE__*/ S.String;

/** One per-(dimension, window) consumption counter row. The proxy ticks one row per dimension on every served LLM request; the dashboard reads this listing to surface live counter growth. */
export interface AgentNetworkConsumption {
	/** Whether this row counts a single end user or a single source group across every member. */
	dimension_kind: AgentNetworkConsumptionDimensionKind;
	/** NetBird user id (when `dimension_kind=user`) or NetBird group id (when `dimension_kind=group`). */
	dimension_id: string;
	/** Length of the aligned window this counter covers, in seconds. Distinct window lengths produce independent counters even on the same dimension. */
	window_seconds: number;
	/** UTC start of the aligned window this counter covers. Aligned to the unix epoch so every node computes the same boundary. */
	window_start_utc: string;
	/** Total input tokens consumed within the window. */
	tokens_input: number;
	/** Total output tokens consumed within the window. */
	tokens_output: number;
	/** Total USD spend booked against this dimension for the window. */
	cost_usd: number;
	/** Timestamp of the last increment recorded for this row. */
	updated_at?: string;
}
export const AgentNetworkConsumption = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		dimension_kind: AgentNetworkConsumptionDimensionKind,
		dimension_id: S.String,
		window_seconds: S.Number,
		window_start_utc: S.String,
		tokens_input: S.Number,
		tokens_output: S.Number,
		cost_usd: S.Number,
		updated_at: S.optional(S.String),
	}),
).annotate({ identifier: "AgentNetworkConsumption" }) as any as S.Schema<AgentNetworkConsumption>;

export type AgentNetworkConsumptionGetResponseBodyList = ReadonlyArray<AgentNetworkConsumption>;
export const AgentNetworkConsumptionGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkConsumption,
) as any as S.Schema<AgentNetworkConsumptionGetResponseBodyList>;

export type AgentNetworkConsumptionGetResponse = AgentNetworkConsumptionGetResponseBodyList;
export const AgentNetworkConsumptionGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkConsumptionGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "AgentNetworkConsumptionGetResponse" }) as any as S.Schema<AgentNetworkConsumptionGetResponse>;

export interface AgentNetworkGuardrailsGetRequest {}
export const AgentNetworkGuardrailsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/guardrails", code: 200 })),
).annotate({ identifier: "AgentNetworkGuardrailsGetRequest" }) as any as S.Schema<AgentNetworkGuardrailsGetRequest>;

/** Allowed catalog model ids. Requests for any other model are denied. */
export type AgentNetworkGuardrailChecksModelAllowlistModelsList = ReadonlyArray<string>;
export const AgentNetworkGuardrailChecksModelAllowlistModelsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkGuardrailChecksModelAllowlistModelsList>;

export interface AgentNetworkGuardrailChecksModelAllowlist {
	enabled: boolean;
	/** Allowed catalog model ids. Requests for any other model are denied. */
	models: AgentNetworkGuardrailChecksModelAllowlistModelsList;
}
export const AgentNetworkGuardrailChecksModelAllowlist = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		models: AgentNetworkGuardrailChecksModelAllowlistModelsList,
	}),
).annotate({
	identifier: "AgentNetworkGuardrailChecksModelAllowlist",
}) as any as S.Schema<AgentNetworkGuardrailChecksModelAllowlist>;

export interface AgentNetworkGuardrailChecksPromptCapture {
	enabled: boolean;
	redact_pii: boolean;
}
export const AgentNetworkGuardrailChecksPromptCapture = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		redact_pii: S.Boolean,
	}),
).annotate({
	identifier: "AgentNetworkGuardrailChecksPromptCapture",
}) as any as S.Schema<AgentNetworkGuardrailChecksPromptCapture>;

/** Guardrail check parameters. Each entry has an `enabled` flag plus per-check configuration; disabled entries are inert. */
export interface AgentNetworkGuardrailChecks {
	model_allowlist: AgentNetworkGuardrailChecksModelAllowlist;
	prompt_capture: AgentNetworkGuardrailChecksPromptCapture;
}
export const AgentNetworkGuardrailChecks = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		model_allowlist: AgentNetworkGuardrailChecksModelAllowlist,
		prompt_capture: AgentNetworkGuardrailChecksPromptCapture,
	}),
).annotate({ identifier: "AgentNetworkGuardrailChecks" }) as any as S.Schema<AgentNetworkGuardrailChecks>;

export interface AgentNetworkGuardrail {
	/** Guardrail ID */
	id: string;
	/** Display name for the guardrail. */
	name: string;
	/** Optional human-readable description. */
	description: string;
	checks: AgentNetworkGuardrailChecks;
	/** Timestamp when the guardrail was created. */
	created_at: string;
	/** Timestamp when the guardrail was last updated. */
	updated_at: string;
}
export const AgentNetworkGuardrail = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		checks: AgentNetworkGuardrailChecks,
		created_at: S.String,
		updated_at: S.String,
	}),
).annotate({ identifier: "AgentNetworkGuardrail" }) as any as S.Schema<AgentNetworkGuardrail>;

export type AgentNetworkGuardrailsGetResponseBodyList = ReadonlyArray<AgentNetworkGuardrail>;
export const AgentNetworkGuardrailsGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkGuardrail,
) as any as S.Schema<AgentNetworkGuardrailsGetResponseBodyList>;

export type AgentNetworkGuardrailsGetResponse = AgentNetworkGuardrailsGetResponseBodyList;
export const AgentNetworkGuardrailsGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkGuardrailsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "AgentNetworkGuardrailsGetResponse" }) as any as S.Schema<AgentNetworkGuardrailsGetResponse>;

export interface AgentNetworkGuardrailsGuardrailIdDeleteRequest {
	/** The unique identifier of an Agent Network guardrail */
	guardrailId: string;
}
export const AgentNetworkGuardrailsGuardrailIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		guardrailId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/agent-network/guardrails/{guardrailId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkGuardrailsGuardrailIdDeleteRequest",
}) as any as S.Schema<AgentNetworkGuardrailsGuardrailIdDeleteRequest>;

export interface AgentNetworkGuardrailsGuardrailIdDeleteResponse {}
export const AgentNetworkGuardrailsGuardrailIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "AgentNetworkGuardrailsGuardrailIdDeleteResponse",
}) as any as S.Schema<AgentNetworkGuardrailsGuardrailIdDeleteResponse>;

export interface AgentNetworkGuardrailsGuardrailIdGetRequest {
	/** The unique identifier of an Agent Network guardrail */
	guardrailId: string;
}
export const AgentNetworkGuardrailsGuardrailIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		guardrailId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/guardrails/{guardrailId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkGuardrailsGuardrailIdGetRequest",
}) as any as S.Schema<AgentNetworkGuardrailsGuardrailIdGetRequest>;

export interface AgentNetworkGuardrailsGuardrailIdPutRequest {
	/** The unique identifier of an Agent Network guardrail */
	guardrailId: string;
	/** Display name for the guardrail. */
	name: string;
	/** Optional human-readable description. */
	description?: string;
	checks: AgentNetworkGuardrailChecks;
}
export const AgentNetworkGuardrailsGuardrailIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		guardrailId: S.String.pipe(T.Label()),
		name: S.String,
		description: S.optional(S.String),
		checks: AgentNetworkGuardrailChecks,
	}).pipe(T.Http({ method: "PUT", uri: "/api/agent-network/guardrails/{guardrailId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkGuardrailsGuardrailIdPutRequest",
}) as any as S.Schema<AgentNetworkGuardrailsGuardrailIdPutRequest>;

export interface AgentNetworkGuardrailsPostRequest {
	/** Display name for the guardrail. */
	name: string;
	/** Optional human-readable description. */
	description?: string;
	checks: AgentNetworkGuardrailChecks;
}
export const AgentNetworkGuardrailsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		description: S.optional(S.String),
		checks: AgentNetworkGuardrailChecks,
	}).pipe(T.Http({ method: "POST", uri: "/api/agent-network/guardrails", code: 200 })),
).annotate({ identifier: "AgentNetworkGuardrailsPostRequest" }) as any as S.Schema<AgentNetworkGuardrailsPostRequest>;

export interface AgentNetworkPoliciesGetRequest {}
export const AgentNetworkPoliciesGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/policies", code: 200 })),
).annotate({ identifier: "AgentNetworkPoliciesGetRequest" }) as any as S.Schema<AgentNetworkPoliciesGetRequest>;

/** NetBird group ids whose members are allowed to call the destination providers. */
export type AgentNetworkPolicySourceGroupsList = ReadonlyArray<string>;
export const AgentNetworkPolicySourceGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPolicySourceGroupsList>;

/** Agent Network provider ids (returned by the providers API) the source groups can reach. */
export type AgentNetworkPolicyDestinationProviderIdsList = ReadonlyArray<string>;
export const AgentNetworkPolicyDestinationProviderIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPolicyDestinationProviderIdsList>;

/** Agent Network guardrail ids attached to this policy. */
export type AgentNetworkPolicyGuardrailIdsList = ReadonlyArray<string>;
export const AgentNetworkPolicyGuardrailIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPolicyGuardrailIdsList>;

export interface AgentNetworkPolicy {
	/** Policy ID */
	id: string;
	/** Display name for the policy. */
	name: string;
	/** Optional human-readable description. */
	description: string;
	/** Whether the policy is enabled. */
	enabled: boolean;
	/** NetBird group ids whose members are allowed to call the destination providers. */
	source_groups: AgentNetworkPolicySourceGroupsList;
	/** Agent Network provider ids (returned by the providers API) the source groups can reach. */
	destination_provider_ids: AgentNetworkPolicyDestinationProviderIdsList;
	/** Agent Network guardrail ids attached to this policy. */
	guardrail_ids: AgentNetworkPolicyGuardrailIdsList;
	limits: AgentNetworkPolicyLimits;
	/** Timestamp when the policy was created. */
	created_at: string;
	/** Timestamp when the policy was last updated. */
	updated_at: string;
}
export const AgentNetworkPolicy = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		enabled: S.Boolean,
		source_groups: AgentNetworkPolicySourceGroupsList,
		destination_provider_ids: AgentNetworkPolicyDestinationProviderIdsList,
		guardrail_ids: AgentNetworkPolicyGuardrailIdsList,
		limits: AgentNetworkPolicyLimits,
		created_at: S.String,
		updated_at: S.String,
	}),
).annotate({ identifier: "AgentNetworkPolicy" }) as any as S.Schema<AgentNetworkPolicy>;

export type AgentNetworkPoliciesGetResponseBodyList = ReadonlyArray<AgentNetworkPolicy>;
export const AgentNetworkPoliciesGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkPolicy,
) as any as S.Schema<AgentNetworkPoliciesGetResponseBodyList>;

export type AgentNetworkPoliciesGetResponse = AgentNetworkPoliciesGetResponseBodyList;
export const AgentNetworkPoliciesGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkPoliciesGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "AgentNetworkPoliciesGetResponse" }) as any as S.Schema<AgentNetworkPoliciesGetResponse>;

export interface AgentNetworkPoliciesPolicyIdDeleteRequest {
	/** The unique identifier of an Agent Network policy */
	policyId: string;
}
export const AgentNetworkPoliciesPolicyIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		policyId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/agent-network/policies/{policyId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkPoliciesPolicyIdDeleteRequest",
}) as any as S.Schema<AgentNetworkPoliciesPolicyIdDeleteRequest>;

export interface AgentNetworkPoliciesPolicyIdDeleteResponse {}
export const AgentNetworkPoliciesPolicyIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "AgentNetworkPoliciesPolicyIdDeleteResponse",
}) as any as S.Schema<AgentNetworkPoliciesPolicyIdDeleteResponse>;

export interface AgentNetworkPoliciesPolicyIdGetRequest {
	/** The unique identifier of an Agent Network policy */
	policyId: string;
}
export const AgentNetworkPoliciesPolicyIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		policyId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/policies/{policyId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkPoliciesPolicyIdGetRequest",
}) as any as S.Schema<AgentNetworkPoliciesPolicyIdGetRequest>;

/** NetBird group ids whose members are allowed to call the destination providers. */
export type AgentNetworkPoliciesPolicyIdPutRequestSourceGroupsList = ReadonlyArray<string>;
export const AgentNetworkPoliciesPolicyIdPutRequestSourceGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPoliciesPolicyIdPutRequestSourceGroupsList>;

/** Agent Network provider ids the source groups can reach. */
export type AgentNetworkPoliciesPolicyIdPutRequestDestinationProviderIdsList = ReadonlyArray<string>;
export const AgentNetworkPoliciesPolicyIdPutRequestDestinationProviderIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPoliciesPolicyIdPutRequestDestinationProviderIdsList>;

/** Agent Network guardrail ids to attach to this policy. */
export type AgentNetworkPoliciesPolicyIdPutRequestGuardrailIdsList = ReadonlyArray<string>;
export const AgentNetworkPoliciesPolicyIdPutRequestGuardrailIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPoliciesPolicyIdPutRequestGuardrailIdsList>;

export interface AgentNetworkPoliciesPolicyIdPutRequest {
	/** The unique identifier of an Agent Network policy */
	policyId: string;
	/** Display name for the policy. */
	name: string;
	/** Optional human-readable description. */
	description?: string;
	/** Whether the policy is enabled. Defaults to true on create. */
	enabled?: boolean;
	/** NetBird group ids whose members are allowed to call the destination providers. */
	source_groups: AgentNetworkPoliciesPolicyIdPutRequestSourceGroupsList;
	/** Agent Network provider ids the source groups can reach. */
	destination_provider_ids: AgentNetworkPoliciesPolicyIdPutRequestDestinationProviderIdsList;
	/** Agent Network guardrail ids to attach to this policy. */
	guardrail_ids?: AgentNetworkPoliciesPolicyIdPutRequestGuardrailIdsList;
	limits?: AgentNetworkPolicyLimits;
}
export const AgentNetworkPoliciesPolicyIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		policyId: S.String.pipe(T.Label()),
		name: S.String,
		description: S.optional(S.String),
		enabled: S.optional(S.Boolean),
		source_groups: AgentNetworkPoliciesPolicyIdPutRequestSourceGroupsList,
		destination_provider_ids: AgentNetworkPoliciesPolicyIdPutRequestDestinationProviderIdsList,
		guardrail_ids: S.optional(AgentNetworkPoliciesPolicyIdPutRequestGuardrailIdsList),
		limits: S.optional(AgentNetworkPolicyLimits),
	}).pipe(T.Http({ method: "PUT", uri: "/api/agent-network/policies/{policyId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkPoliciesPolicyIdPutRequest",
}) as any as S.Schema<AgentNetworkPoliciesPolicyIdPutRequest>;

/** NetBird group ids whose members are allowed to call the destination providers. */
export type AgentNetworkPoliciesPostRequestSourceGroupsList = ReadonlyArray<string>;
export const AgentNetworkPoliciesPostRequestSourceGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPoliciesPostRequestSourceGroupsList>;

/** Agent Network provider ids the source groups can reach. */
export type AgentNetworkPoliciesPostRequestDestinationProviderIdsList = ReadonlyArray<string>;
export const AgentNetworkPoliciesPostRequestDestinationProviderIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPoliciesPostRequestDestinationProviderIdsList>;

/** Agent Network guardrail ids to attach to this policy. */
export type AgentNetworkPoliciesPostRequestGuardrailIdsList = ReadonlyArray<string>;
export const AgentNetworkPoliciesPostRequestGuardrailIdsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkPoliciesPostRequestGuardrailIdsList>;

export interface AgentNetworkPoliciesPostRequest {
	/** Display name for the policy. */
	name: string;
	/** Optional human-readable description. */
	description?: string;
	/** Whether the policy is enabled. Defaults to true on create. */
	enabled?: boolean;
	/** NetBird group ids whose members are allowed to call the destination providers. */
	source_groups: AgentNetworkPoliciesPostRequestSourceGroupsList;
	/** Agent Network provider ids the source groups can reach. */
	destination_provider_ids: AgentNetworkPoliciesPostRequestDestinationProviderIdsList;
	/** Agent Network guardrail ids to attach to this policy. */
	guardrail_ids?: AgentNetworkPoliciesPostRequestGuardrailIdsList;
	limits?: AgentNetworkPolicyLimits;
}
export const AgentNetworkPoliciesPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		description: S.optional(S.String),
		enabled: S.optional(S.Boolean),
		source_groups: AgentNetworkPoliciesPostRequestSourceGroupsList,
		destination_provider_ids: AgentNetworkPoliciesPostRequestDestinationProviderIdsList,
		guardrail_ids: S.optional(AgentNetworkPoliciesPostRequestGuardrailIdsList),
		limits: S.optional(AgentNetworkPolicyLimits),
	}).pipe(T.Http({ method: "POST", uri: "/api/agent-network/policies", code: 200 })),
).annotate({ identifier: "AgentNetworkPoliciesPostRequest" }) as any as S.Schema<AgentNetworkPoliciesPostRequest>;

export interface AgentNetworkProvidersGetRequest {}
export const AgentNetworkProvidersGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/providers", code: 200 })),
).annotate({ identifier: "AgentNetworkProvidersGetRequest" }) as any as S.Schema<AgentNetworkProvidersGetRequest>;

/** A model exposed by the provider, with the operator's per-1k input/output prices in USD. */
export interface AgentNetworkProviderModel {
	/** Model identifier (e.g. "gpt-4o-mini"). */
	id: string;
	/** Cost per 1k input tokens, in USD. */
	input_per_1k: number;
	/** Cost per 1k output tokens, in USD. */
	output_per_1k: number;
}
export const AgentNetworkProviderModel = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		input_per_1k: S.Number,
		output_per_1k: S.Number,
	}),
).annotate({ identifier: "AgentNetworkProviderModel" }) as any as S.Schema<AgentNetworkProviderModel>;

/** Models exposed through this endpoint, with the operator's per-1k input/output prices. Empty means all catalog models are allowed at catalog prices. */
export type AgentNetworkProviderModelsList = ReadonlyArray<AgentNetworkProviderModel>;
export const AgentNetworkProviderModelsList = /*@__PURE__*/ S.Array(
	AgentNetworkProviderModel,
) as any as S.Schema<AgentNetworkProviderModelsList>;

/** Operator-typed values for catalog-declared extra headers. Keys are wire header names (e.g. `x-portkey-config`); values are the strings the proxy stamps on every upstream request to this provider. Catalog (AgentNetworkCatalogProvider.extra_headers) declares which keys are accepted; values not declared by the catalog are ignored at synth time. Empty / missing values mean no header stamped. */
export type AgentNetworkProviderExtraValuesMap = { [key: string]: string };
export const AgentNetworkProviderExtraValuesMap = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<AgentNetworkProviderExtraValuesMap>;

export interface AgentNetworkProvider {
	/** Provider ID */
	id: string;
	/** Catalog identifier for the upstream AI provider (e.g. openai_api, anthropic_api, azure_openai_api, bedrock_api, vertex_ai_api, mistral_api, custom). */
	provider_id: string;
	/** Display name shown in the dashboard. */
	name: string;
	/** Full upstream URL (with scheme) that NetBird forwards traffic to. */
	upstream_url: string;
	/** Models exposed through this endpoint, with the operator's per-1k input/output prices. Empty means all catalog models are allowed at catalog prices. */
	models: AgentNetworkProviderModelsList;
	/** Operator-typed values for catalog-declared extra headers. Keys are wire header names (e.g. `x-portkey-config`); values are the strings the proxy stamps on every upstream request to this provider. Catalog (AgentNetworkCatalogProvider.extra_headers) declares which keys are accepted; values not declared by the catalog are ignored at synth time. Empty / missing values mean no header stamped. */
	extra_values?: AgentNetworkProviderExtraValuesMap;
	/** Wire header name the proxy stamps with the caller's display identity (user email or peer name) when the catalog entry's HeaderPair is `customizable`. Empty disables stamping for this dimension. Ignored when the catalog entry has a fixed HeaderPair (e.g. LiteLLM, Portkey). Used today by Bifrost: typical values are `x-bf-lh-netbird_user_id` (always-on log metadata) or `x-bf-dim-netbird_user_id` (Prometheus / OTEL — requires the label to be pre-declared in the gateway's `client.prometheus_labels` config). */
	identity_header_user_id?: string;
	/** Wire header name the proxy stamps with the caller's NetBird groups as a comma-separated list (sorted) when the catalog entry's HeaderPair is `customizable`. Empty disables stamping for this dimension. Same per-catalog semantics as `identity_header_user_id`. */
	identity_header_groups?: string;
	/** Whether the provider is enabled. */
	enabled: boolean;
	/** Whether upstream TLS certificate verification is skipped when the proxy dials this provider's URL. Intended for self-hosted / internal gateways behind a private or self-signed certificate. */
	skip_tls_verification: boolean;
	/** Whether identity metadata injection is disabled for this provider. When enabled (the default), the proxy stamps the caller's user and authorizing group onto upstream requests as provider-specific metadata (e.g. AWS Bedrock's X-Amzn-Bedrock-Request-Metadata header). Set true to suppress it. */
	metadata_disabled: boolean;
	/** Timestamp when the provider was created. */
	created_at: string;
	/** Timestamp when the provider was last updated. */
	updated_at: string;
}
export const AgentNetworkProvider = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		provider_id: S.String,
		name: S.String,
		upstream_url: S.String,
		models: AgentNetworkProviderModelsList,
		extra_values: S.optional(AgentNetworkProviderExtraValuesMap),
		identity_header_user_id: S.optional(S.String),
		identity_header_groups: S.optional(S.String),
		enabled: S.Boolean,
		skip_tls_verification: S.Boolean,
		metadata_disabled: S.Boolean,
		created_at: S.String,
		updated_at: S.String,
	}),
).annotate({ identifier: "AgentNetworkProvider" }) as any as S.Schema<AgentNetworkProvider>;

export type AgentNetworkProvidersGetResponseBodyList = ReadonlyArray<AgentNetworkProvider>;
export const AgentNetworkProvidersGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkProvider,
) as any as S.Schema<AgentNetworkProvidersGetResponseBodyList>;

export type AgentNetworkProvidersGetResponse = AgentNetworkProvidersGetResponseBodyList;
export const AgentNetworkProvidersGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkProvidersGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "AgentNetworkProvidersGetResponse" }) as any as S.Schema<AgentNetworkProvidersGetResponse>;

/** Models exposed through this endpoint, with the operator's per-1k input/output prices. Empty means all catalog models are allowed at catalog prices. */
export type AgentNetworkProvidersPostRequestModelsList = ReadonlyArray<AgentNetworkProviderModel>;
export const AgentNetworkProvidersPostRequestModelsList = /*@__PURE__*/ S.Array(
	AgentNetworkProviderModel,
) as any as S.Schema<AgentNetworkProvidersPostRequestModelsList>;

/** Operator-typed values for catalog-declared extra headers (see AgentNetworkProvider.extra_values). When present on a request, the whole map replaces the stored values. Empty strings drop the corresponding key. */
export type AgentNetworkProvidersPostRequestExtraValuesMap = { [key: string]: string };
export const AgentNetworkProvidersPostRequestExtraValuesMap = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<AgentNetworkProvidersPostRequestExtraValuesMap>;

export interface AgentNetworkProvidersPostRequest {
	/** Catalog identifier for the upstream AI provider (e.g. openai_api, anthropic_api, azure_openai_api, bedrock_api, vertex_ai_api, mistral_api, custom). */
	provider_id: string;
	/** Display name for the provider. */
	name: string;
	/** Full upstream URL (with scheme) that NetBird forwards traffic to. */
	upstream_url: string;
	/** Proxy cluster used to bootstrap the per-account agent-network endpoint when the first provider is created. Ignored on subsequent creates and on updates because the cluster is pinned on the account-level Settings row. */
	bootstrap_cluster?: string;
	/** Upstream provider API key. Sealed at rest on the management server and never returned in responses. Required on create; optional on update (omit to keep the existing key). */
	api_key?: string | Redacted.Redacted<string>;
	/** Models exposed through this endpoint, with the operator's per-1k input/output prices. Empty means all catalog models are allowed at catalog prices. */
	models?: AgentNetworkProvidersPostRequestModelsList;
	/** Operator-typed values for catalog-declared extra headers (see AgentNetworkProvider.extra_values). When present on a request, the whole map replaces the stored values. Empty strings drop the corresponding key. */
	extra_values?: AgentNetworkProvidersPostRequestExtraValuesMap;
	/** Wire header name for the caller's display identity. See AgentNetworkProvider.identity_header_user_id. When omitted on a request, the stored value is left unchanged; pass an empty string explicitly to clear it (which disables stamping for this dimension). */
	identity_header_user_id?: string;
	/** Wire header name for the caller's groups CSV. See AgentNetworkProvider.identity_header_groups. Same omit / empty semantics as `identity_header_user_id`. */
	identity_header_groups?: string;
	/** Whether the provider is enabled. Defaults to true on create. */
	enabled?: boolean;
	/** Skip upstream TLS certificate verification when the proxy dials this provider's URL. For self-hosted / internal gateways behind a private or self-signed certificate. Defaults to false. When omitted on update, the stored value is left unchanged. */
	skip_tls_verification?: boolean;
	/** Disable identity metadata injection (the caller's user + authorizing group) for this provider. Defaults to false (metadata is injected). When omitted on update, the stored value is left unchanged. */
	metadata_disabled?: boolean;
}
export const AgentNetworkProvidersPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		provider_id: S.String,
		name: S.String,
		upstream_url: S.String,
		bootstrap_cluster: S.optional(S.String),
		api_key: S.optional(S.String.pipe(T.SensitiveValue({}))),
		models: S.optional(AgentNetworkProvidersPostRequestModelsList),
		extra_values: S.optional(AgentNetworkProvidersPostRequestExtraValuesMap),
		identity_header_user_id: S.optional(S.String),
		identity_header_groups: S.optional(S.String),
		enabled: S.optional(S.Boolean),
		skip_tls_verification: S.optional(S.Boolean),
		metadata_disabled: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "POST", uri: "/api/agent-network/providers", code: 200 })),
).annotate({ identifier: "AgentNetworkProvidersPostRequest" }) as any as S.Schema<AgentNetworkProvidersPostRequest>;

export interface AgentNetworkProvidersProviderIdDeleteRequest {
	/** The unique identifier of an Agent Network provider */
	providerId: string;
}
export const AgentNetworkProvidersProviderIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		providerId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/agent-network/providers/{providerId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkProvidersProviderIdDeleteRequest",
}) as any as S.Schema<AgentNetworkProvidersProviderIdDeleteRequest>;

export interface AgentNetworkProvidersProviderIdDeleteResponse {}
export const AgentNetworkProvidersProviderIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "AgentNetworkProvidersProviderIdDeleteResponse",
}) as any as S.Schema<AgentNetworkProvidersProviderIdDeleteResponse>;

export interface AgentNetworkProvidersProviderIdGetRequest {
	/** The unique identifier of an Agent Network provider */
	providerId: string;
}
export const AgentNetworkProvidersProviderIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		providerId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/providers/{providerId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkProvidersProviderIdGetRequest",
}) as any as S.Schema<AgentNetworkProvidersProviderIdGetRequest>;

/** Models exposed through this endpoint, with the operator's per-1k input/output prices. Empty means all catalog models are allowed at catalog prices. */
export type AgentNetworkProvidersProviderIdPutRequestModelsList = ReadonlyArray<AgentNetworkProviderModel>;
export const AgentNetworkProvidersProviderIdPutRequestModelsList = /*@__PURE__*/ S.Array(
	AgentNetworkProviderModel,
) as any as S.Schema<AgentNetworkProvidersProviderIdPutRequestModelsList>;

/** Operator-typed values for catalog-declared extra headers (see AgentNetworkProvider.extra_values). When present on a request, the whole map replaces the stored values. Empty strings drop the corresponding key. */
export type AgentNetworkProvidersProviderIdPutRequestExtraValuesMap = { [key: string]: string };
export const AgentNetworkProvidersProviderIdPutRequestExtraValuesMap = /*@__PURE__*/ S.Record(
	S.String,
	S.String,
) as any as S.Schema<AgentNetworkProvidersProviderIdPutRequestExtraValuesMap>;

export interface AgentNetworkProvidersProviderIdPutRequest {
	/** The unique identifier of an Agent Network provider */
	providerId: string;
	/** Catalog identifier for the upstream AI provider (e.g. openai_api, anthropic_api, azure_openai_api, bedrock_api, vertex_ai_api, mistral_api, custom). */
	provider_id: string;
	/** Display name for the provider. */
	name: string;
	/** Full upstream URL (with scheme) that NetBird forwards traffic to. */
	upstream_url: string;
	/** Proxy cluster used to bootstrap the per-account agent-network endpoint when the first provider is created. Ignored on subsequent creates and on updates because the cluster is pinned on the account-level Settings row. */
	bootstrap_cluster?: string;
	/** Upstream provider API key. Sealed at rest on the management server and never returned in responses. Required on create; optional on update (omit to keep the existing key). */
	api_key?: string | Redacted.Redacted<string>;
	/** Models exposed through this endpoint, with the operator's per-1k input/output prices. Empty means all catalog models are allowed at catalog prices. */
	models?: AgentNetworkProvidersProviderIdPutRequestModelsList;
	/** Operator-typed values for catalog-declared extra headers (see AgentNetworkProvider.extra_values). When present on a request, the whole map replaces the stored values. Empty strings drop the corresponding key. */
	extra_values?: AgentNetworkProvidersProviderIdPutRequestExtraValuesMap;
	/** Wire header name for the caller's display identity. See AgentNetworkProvider.identity_header_user_id. When omitted on a request, the stored value is left unchanged; pass an empty string explicitly to clear it (which disables stamping for this dimension). */
	identity_header_user_id?: string;
	/** Wire header name for the caller's groups CSV. See AgentNetworkProvider.identity_header_groups. Same omit / empty semantics as `identity_header_user_id`. */
	identity_header_groups?: string;
	/** Whether the provider is enabled. Defaults to true on create. */
	enabled?: boolean;
	/** Skip upstream TLS certificate verification when the proxy dials this provider's URL. For self-hosted / internal gateways behind a private or self-signed certificate. Defaults to false. When omitted on update, the stored value is left unchanged. */
	skip_tls_verification?: boolean;
	/** Disable identity metadata injection (the caller's user + authorizing group) for this provider. Defaults to false (metadata is injected). When omitted on update, the stored value is left unchanged. */
	metadata_disabled?: boolean;
}
export const AgentNetworkProvidersProviderIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		providerId: S.String.pipe(T.Label()),
		provider_id: S.String,
		name: S.String,
		upstream_url: S.String,
		bootstrap_cluster: S.optional(S.String),
		api_key: S.optional(S.String.pipe(T.SensitiveValue({}))),
		models: S.optional(AgentNetworkProvidersProviderIdPutRequestModelsList),
		extra_values: S.optional(AgentNetworkProvidersProviderIdPutRequestExtraValuesMap),
		identity_header_user_id: S.optional(S.String),
		identity_header_groups: S.optional(S.String),
		enabled: S.optional(S.Boolean),
		skip_tls_verification: S.optional(S.Boolean),
		metadata_disabled: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "PUT", uri: "/api/agent-network/providers/{providerId}", code: 200 })),
).annotate({
	identifier: "AgentNetworkProvidersProviderIdPutRequest",
}) as any as S.Schema<AgentNetworkProvidersProviderIdPutRequest>;

export interface AgentNetworkSettingsGetRequest {}
export const AgentNetworkSettingsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/settings", code: 200 })),
).annotate({ identifier: "AgentNetworkSettingsGetRequest" }) as any as S.Schema<AgentNetworkSettingsGetRequest>;

/** Per-account Agent Network gateway settings. One row per account; cluster and subdomain are auto-assigned on first provider create and immutable thereafter. */
export interface AgentNetworkSettings {
	/** Address of the NetBird proxy cluster fronting this account's agent-network endpoint. */
	cluster: string;
	/** Auto-generated DNS-safe label that prefixes the cluster to form the agent-network endpoint. */
	subdomain: string;
	/** Bare hostname agents call for this account, computed as `<subdomain>.<cluster>`. */
	endpoint: string;
	/** Whether per-request access-log entries are collected for this account's agent-network traffic. */
	enable_log_collection: boolean;
	/** Master switch for request/response prompt capture. Capture runs only when this is on AND a policy guardrail also enables it. */
	enable_prompt_collection: boolean;
	/** Whether captured prompts have PII redacted. Effective redaction is the OR of this and any policy guardrail's redact setting. */
	redact_pii: boolean;
	/** Days to retain full access-log rows; older rows are swept. 0 or less means keep indefinitely. Usage records are retained independently. */
	access_log_retention_days?: number;
	/** Timestamp when the settings row was created. */
	created_at: string;
	/** Timestamp when the settings row was last updated. */
	updated_at: string;
}
export const AgentNetworkSettings = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		cluster: S.String,
		subdomain: S.String,
		endpoint: S.String,
		enable_log_collection: S.Boolean,
		enable_prompt_collection: S.Boolean,
		redact_pii: S.Boolean,
		access_log_retention_days: S.optional(S.Number),
		created_at: S.String,
		updated_at: S.String,
	}),
).annotate({ identifier: "AgentNetworkSettings" }) as any as S.Schema<AgentNetworkSettings>;

export interface AgentNetworkSettingsPutRequest {
	/** Whether per-request access-log entries are collected for this account's agent-network traffic. */
	enable_log_collection: boolean;
	/** Master switch for request/response prompt capture. */
	enable_prompt_collection: boolean;
	/** Whether captured prompts have PII redacted. */
	redact_pii: boolean;
	/** Days to retain full access-log rows; older rows are swept. 0 or less means keep indefinitely. */
	access_log_retention_days?: number;
}
export const AgentNetworkSettingsPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enable_log_collection: S.Boolean,
		enable_prompt_collection: S.Boolean,
		redact_pii: S.Boolean,
		access_log_retention_days: S.optional(S.Number),
	}).pipe(T.Http({ method: "PUT", uri: "/api/agent-network/settings", code: 200 })),
).annotate({ identifier: "AgentNetworkSettingsPutRequest" }) as any as S.Schema<AgentNetworkSettingsPutRequest>;

export type AgentNetworkUsageOverviewGetRequestGranularity = "day" | "week" | "month";
export const AgentNetworkUsageOverviewGetRequestGranularity = /*@__PURE__*/ S.String;

export type AgentNetworkUsageOverviewGetRequestGroupIdList = ReadonlyArray<string>;
export const AgentNetworkUsageOverviewGetRequestGroupIdList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkUsageOverviewGetRequestGroupIdList>;

export type AgentNetworkUsageOverviewGetRequestProviderIdList = ReadonlyArray<string>;
export const AgentNetworkUsageOverviewGetRequestProviderIdList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkUsageOverviewGetRequestProviderIdList>;

export type AgentNetworkUsageOverviewGetRequestModelList = ReadonlyArray<string>;
export const AgentNetworkUsageOverviewGetRequestModelList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<AgentNetworkUsageOverviewGetRequestModelList>;

export interface AgentNetworkUsageOverviewGetRequest {
	/** Time bucket width. Defaults to day. */
	granularity?: AgentNetworkUsageOverviewGetRequestGranularity;
	/** Filter by timestamp >= start_date (RFC3339 format). */
	start_date?: string;
	/** Filter by timestamp <= end_date (RFC3339 format). */
	end_date?: string;
	/** Filter by user ID. */
	user_id?: string;
	/** Filter to a single conversation / coding session id. */
	session_id?: string;
	/** Filter by authorising group id. Repeat for multiple (matches any). */
	group_id?: AgentNetworkUsageOverviewGetRequestGroupIdList;
	/** Filter by resolved provider id. Repeat for multiple (matches any). */
	provider_id?: AgentNetworkUsageOverviewGetRequestProviderIdList;
	/** Filter by model. Repeat for multiple (matches any). */
	model?: AgentNetworkUsageOverviewGetRequestModelList;
}
export const AgentNetworkUsageOverviewGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		granularity: S.optional(AgentNetworkUsageOverviewGetRequestGranularity.pipe(T.Query())),
		start_date: S.optional(S.String.pipe(T.Query())),
		end_date: S.optional(S.String.pipe(T.Query())),
		user_id: S.optional(S.String.pipe(T.Query())),
		session_id: S.optional(S.String.pipe(T.Query())),
		group_id: S.optional(AgentNetworkUsageOverviewGetRequestGroupIdList.pipe(T.Query())),
		provider_id: S.optional(AgentNetworkUsageOverviewGetRequestProviderIdList.pipe(T.Query())),
		model: S.optional(AgentNetworkUsageOverviewGetRequestModelList.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/agent-network/usage/overview", code: 200 })),
).annotate({
	identifier: "AgentNetworkUsageOverviewGetRequest",
}) as any as S.Schema<AgentNetworkUsageOverviewGetRequest>;

/** One aggregated agent-network usage time bucket (UTC). The bucket width is set by the request's granularity. */
export interface AgentNetworkUsageBucket {
	/** Start of the bucket in YYYY-MM-DD (UTC) — the day, the week start (Monday), or the month start, depending on granularity. */
	period_start: string;
	/** Total input (prompt) tokens in the bucket. */
	input_tokens: number;
	/** Total output (completion) tokens in the bucket. */
	output_tokens: number;
	/** Total tokens in the bucket. */
	total_tokens: number;
	/** Total estimated USD spend in the bucket. */
	cost_usd: number;
}
export const AgentNetworkUsageBucket = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		period_start: S.String,
		input_tokens: S.Number,
		output_tokens: S.Number,
		total_tokens: S.Number,
		cost_usd: S.Number,
	}),
).annotate({ identifier: "AgentNetworkUsageBucket" }) as any as S.Schema<AgentNetworkUsageBucket>;

export type AgentNetworkUsageOverviewGetResponseBodyList = ReadonlyArray<AgentNetworkUsageBucket>;
export const AgentNetworkUsageOverviewGetResponseBodyList = /*@__PURE__*/ S.Array(
	AgentNetworkUsageBucket,
) as any as S.Schema<AgentNetworkUsageOverviewGetResponseBodyList>;

export type AgentNetworkUsageOverviewGetResponse = AgentNetworkUsageOverviewGetResponseBodyList;
export const AgentNetworkUsageOverviewGetResponse = /*@__PURE__*/ S.suspend(() =>
	AgentNetworkUsageOverviewGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "AgentNetworkUsageOverviewGetResponse",
}) as any as S.Schema<AgentNetworkUsageOverviewGetResponse>;

export type AgentNetworkAccessLogSessionsGetError = Forbidden | NetbirdOpError;
/** List Agent Network access logs grouped by session Returns a paginated, server-side-filtered list of agent-network (LLM) access logs grouped by session. The page unit is a session (total_records counts sessions); each session carries an aggregate summary and its ordered entries. Requests the client sent no session id for each form their own singleton group. Accepts the same filters as the flat access-logs endpoint. Available only when the account has log collection enabled. */
export const agentNetworkAccessLogSessionsGet: API.OperationMethod<
	AgentNetworkAccessLogSessionsGetRequest,
	AgentNetworkAccessLogSessionsResponse,
	AgentNetworkAccessLogSessionsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkAccessLogSessionsGetRequest,
	output: AgentNetworkAccessLogSessionsResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkAccessLogsGetError = Forbidden | NetbirdOpError;
/** List Agent Network access logs Returns a paginated, server-side-filtered list of agent-network (LLM) access log entries. Available only when the account has log collection enabled; otherwise entries are not retained. */
export const agentNetworkAccessLogsGet: API.OperationMethod<
	AgentNetworkAccessLogsGetRequest,
	AgentNetworkAccessLogsResponse,
	AgentNetworkAccessLogsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkAccessLogsGetRequest,
	output: AgentNetworkAccessLogsResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkBudgetRulesGetError = Forbidden | NetbirdOpError;
/** List all Agent Network budget rules Returns all account-level budget rules. */
export const agentNetworkBudgetRulesGet: API.OperationMethod<
	AgentNetworkBudgetRulesGetRequest,
	AgentNetworkBudgetRulesGetResponse,
	AgentNetworkBudgetRulesGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkBudgetRulesGetRequest,
	output: AgentNetworkBudgetRulesGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkBudgetRulesPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create an Agent Network budget rule Creates a new account-level budget rule. */
export const agentNetworkBudgetRulesPost: API.OperationMethod<
	AgentNetworkBudgetRulesPostRequest,
	AgentNetworkBudgetRule,
	AgentNetworkBudgetRulesPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkBudgetRulesPostRequest,
	output: AgentNetworkBudgetRule,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkBudgetRulesRuleIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete an Agent Network budget rule Deletes an account-level budget rule. */
export const agentNetworkBudgetRulesRuleIdDelete: API.OperationMethod<
	AgentNetworkBudgetRulesRuleIdDeleteRequest,
	AgentNetworkBudgetRulesRuleIdDeleteResponse,
	AgentNetworkBudgetRulesRuleIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkBudgetRulesRuleIdDeleteRequest,
	output: AgentNetworkBudgetRulesRuleIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkBudgetRulesRuleIdGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Retrieve an Agent Network budget rule Get a specific account-level budget rule. */
export const agentNetworkBudgetRulesRuleIdGet: API.OperationMethod<
	AgentNetworkBudgetRulesRuleIdGetRequest,
	AgentNetworkBudgetRule,
	AgentNetworkBudgetRulesRuleIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkBudgetRulesRuleIdGetRequest,
	output: AgentNetworkBudgetRule,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkBudgetRulesRuleIdPutError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Update an Agent Network budget rule Updates an existing account-level budget rule. */
export const agentNetworkBudgetRulesRuleIdPut: API.OperationMethod<
	AgentNetworkBudgetRulesRuleIdPutRequest,
	AgentNetworkBudgetRule,
	AgentNetworkBudgetRulesRuleIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkBudgetRulesRuleIdPutRequest,
	output: AgentNetworkBudgetRule,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkCatalogProvidersGetError = Forbidden | NetbirdOpError;
/** List Agent Network catalog providers Returns the static catalog of supported Agent Network providers (OpenAI, Anthropic, …) along with their default upstream host, auth header template, brand color, and known models. */
export const agentNetworkCatalogProvidersGet: API.OperationMethod<
	AgentNetworkCatalogProvidersGetRequest,
	AgentNetworkCatalogProvidersGetResponse,
	AgentNetworkCatalogProvidersGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkCatalogProvidersGetRequest,
	output: AgentNetworkCatalogProvidersGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkConsumptionGetError = Forbidden | NetbirdOpError;
/** List Agent Network consumption counters Returns every per-(dimension, window) consumption counter recorded for the account, ordered window-newest-first. Empty list when nothing has been consumed yet. */
export const agentNetworkConsumptionGet: API.OperationMethod<
	AgentNetworkConsumptionGetRequest,
	AgentNetworkConsumptionGetResponse,
	AgentNetworkConsumptionGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkConsumptionGetRequest,
	output: AgentNetworkConsumptionGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkGuardrailsGetError = Forbidden | NetbirdOpError;
/** List all Agent Network Guardrails Returns a list of all Agent Network guardrails for the account. */
export const agentNetworkGuardrailsGet: API.OperationMethod<
	AgentNetworkGuardrailsGetRequest,
	AgentNetworkGuardrailsGetResponse,
	AgentNetworkGuardrailsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkGuardrailsGetRequest,
	output: AgentNetworkGuardrailsGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkGuardrailsGuardrailIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete an Agent Network Guardrail Delete an existing Agent Network guardrail. */
export const agentNetworkGuardrailsGuardrailIdDelete: API.OperationMethod<
	AgentNetworkGuardrailsGuardrailIdDeleteRequest,
	AgentNetworkGuardrailsGuardrailIdDeleteResponse,
	AgentNetworkGuardrailsGuardrailIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkGuardrailsGuardrailIdDeleteRequest,
	output: AgentNetworkGuardrailsGuardrailIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkGuardrailsGuardrailIdGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Retrieve an Agent Network Guardrail Get information about a specific Agent Network guardrail. */
export const agentNetworkGuardrailsGuardrailIdGet: API.OperationMethod<
	AgentNetworkGuardrailsGuardrailIdGetRequest,
	AgentNetworkGuardrail,
	AgentNetworkGuardrailsGuardrailIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkGuardrailsGuardrailIdGetRequest,
	output: AgentNetworkGuardrail,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkGuardrailsGuardrailIdPutError = BadRequest | Forbidden | NotFound | Conflict | NetbirdOpError;
/** Update an Agent Network Guardrail Update an existing Agent Network guardrail. */
export const agentNetworkGuardrailsGuardrailIdPut: API.OperationMethod<
	AgentNetworkGuardrailsGuardrailIdPutRequest,
	AgentNetworkGuardrail,
	AgentNetworkGuardrailsGuardrailIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkGuardrailsGuardrailIdPutRequest,
	output: AgentNetworkGuardrail,
	errors: [BadRequest, Forbidden, NotFound, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkGuardrailsPostError = BadRequest | Forbidden | Conflict | NetbirdOpError;
/** Create an Agent Network Guardrail Creates a new Agent Network guardrail that can be attached to one or more policies. */
export const agentNetworkGuardrailsPost: API.OperationMethod<
	AgentNetworkGuardrailsPostRequest,
	AgentNetworkGuardrail,
	AgentNetworkGuardrailsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkGuardrailsPostRequest,
	output: AgentNetworkGuardrail,
	errors: [BadRequest, Forbidden, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkPoliciesGetError = Forbidden | NetbirdOpError;
/** List all Agent Network Policies Returns a list of all Agent Network policies for the account. */
export const agentNetworkPoliciesGet: API.OperationMethod<
	AgentNetworkPoliciesGetRequest,
	AgentNetworkPoliciesGetResponse,
	AgentNetworkPoliciesGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkPoliciesGetRequest,
	output: AgentNetworkPoliciesGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkPoliciesPolicyIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete an Agent Network Policy Delete an existing Agent Network policy. */
export const agentNetworkPoliciesPolicyIdDelete: API.OperationMethod<
	AgentNetworkPoliciesPolicyIdDeleteRequest,
	AgentNetworkPoliciesPolicyIdDeleteResponse,
	AgentNetworkPoliciesPolicyIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkPoliciesPolicyIdDeleteRequest,
	output: AgentNetworkPoliciesPolicyIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkPoliciesPolicyIdGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Retrieve an Agent Network Policy Get information about a specific Agent Network policy. */
export const agentNetworkPoliciesPolicyIdGet: API.OperationMethod<
	AgentNetworkPoliciesPolicyIdGetRequest,
	AgentNetworkPolicy,
	AgentNetworkPoliciesPolicyIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkPoliciesPolicyIdGetRequest,
	output: AgentNetworkPolicy,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkPoliciesPolicyIdPutError = BadRequest | Forbidden | NotFound | Conflict | NetbirdOpError;
/** Update an Agent Network Policy Update an existing Agent Network policy. */
export const agentNetworkPoliciesPolicyIdPut: API.OperationMethod<
	AgentNetworkPoliciesPolicyIdPutRequest,
	AgentNetworkPolicy,
	AgentNetworkPoliciesPolicyIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkPoliciesPolicyIdPutRequest,
	output: AgentNetworkPolicy,
	errors: [BadRequest, Forbidden, NotFound, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkPoliciesPostError = BadRequest | Forbidden | Conflict | NetbirdOpError;
/** Create an Agent Network Policy Creates a new Agent Network policy binding source groups to destination providers, optionally enforced by guardrails. */
export const agentNetworkPoliciesPost: API.OperationMethod<
	AgentNetworkPoliciesPostRequest,
	AgentNetworkPolicy,
	AgentNetworkPoliciesPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkPoliciesPostRequest,
	output: AgentNetworkPolicy,
	errors: [BadRequest, Forbidden, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkProvidersGetError = Forbidden | NetbirdOpError;
/** List all Agent Network Providers Returns a list of all Agent Network AI providers configured for the account. */
export const agentNetworkProvidersGet: API.OperationMethod<
	AgentNetworkProvidersGetRequest,
	AgentNetworkProvidersGetResponse,
	AgentNetworkProvidersGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkProvidersGetRequest,
	output: AgentNetworkProvidersGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkProvidersPostError = BadRequest | Forbidden | Conflict | NetbirdOpError;
/** Create an Agent Network Provider Connects a new Agent Network AI provider for the account. */
export const agentNetworkProvidersPost: API.OperationMethod<
	AgentNetworkProvidersPostRequest,
	AgentNetworkProvider,
	AgentNetworkProvidersPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkProvidersPostRequest,
	output: AgentNetworkProvider,
	errors: [BadRequest, Forbidden, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkProvidersProviderIdDeleteError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Delete an Agent Network Provider Delete an existing Agent Network AI provider. */
export const agentNetworkProvidersProviderIdDelete: API.OperationMethod<
	AgentNetworkProvidersProviderIdDeleteRequest,
	AgentNetworkProvidersProviderIdDeleteResponse,
	AgentNetworkProvidersProviderIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkProvidersProviderIdDeleteRequest,
	output: AgentNetworkProvidersProviderIdDeleteResponse,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkProvidersProviderIdGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Retrieve an Agent Network Provider Get information about a specific Agent Network AI provider. */
export const agentNetworkProvidersProviderIdGet: API.OperationMethod<
	AgentNetworkProvidersProviderIdGetRequest,
	AgentNetworkProvider,
	AgentNetworkProvidersProviderIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkProvidersProviderIdGetRequest,
	output: AgentNetworkProvider,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkProvidersProviderIdPutError = BadRequest | Forbidden | NotFound | Conflict | NetbirdOpError;
/** Update an Agent Network Provider Update an existing Agent Network AI provider. */
export const agentNetworkProvidersProviderIdPut: API.OperationMethod<
	AgentNetworkProvidersProviderIdPutRequest,
	AgentNetworkProvider,
	AgentNetworkProvidersProviderIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkProvidersProviderIdPutRequest,
	output: AgentNetworkProvider,
	errors: [BadRequest, Forbidden, NotFound, Conflict, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkSettingsGetError = Forbidden | NotFound | NetbirdOpError;
/** Retrieve Agent Network settings Returns the per-account Agent Network gateway settings (cluster, subdomain, endpoint). Returns 404 when no provider has been created yet — settings are lazily bootstrapped on first provider create. */
export const agentNetworkSettingsGet: API.OperationMethod<
	AgentNetworkSettingsGetRequest,
	AgentNetworkSettings,
	AgentNetworkSettingsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkSettingsGetRequest,
	output: AgentNetworkSettings,
	errors: [Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkSettingsPutError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** Update Agent Network settings Updates the mutable account-level Agent Network settings (collection toggles). Cluster and subdomain are immutable and ignored if sent. Returns 404 when settings have not been bootstrapped (no provider created yet). */
export const agentNetworkSettingsPut: API.OperationMethod<
	AgentNetworkSettingsPutRequest,
	AgentNetworkSettings,
	AgentNetworkSettingsPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkSettingsPutRequest,
	output: AgentNetworkSettings,
	errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type AgentNetworkUsageOverviewGetError = Forbidden | NetbirdOpError;
/** Agent Network usage overview Returns agent-network token and cost usage aggregated into time buckets, server-side filtered. Usage is always collected (independent of log collection). */
export const agentNetworkUsageOverviewGet: API.OperationMethod<
	AgentNetworkUsageOverviewGetRequest,
	AgentNetworkUsageOverviewGetResponse,
	AgentNetworkUsageOverviewGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: AgentNetworkUsageOverviewGetRequest,
	output: AgentNetworkUsageOverviewGetResponse,
	errors: [Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
