import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export interface DnsNameserversGetRequest {}
export const DnsNameserversGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/dns/nameservers", code: 200 })),
).annotate({ identifier: "DnsNameserversGetRequest" }) as any as S.Schema<DnsNameserversGetRequest>;

/** Nameserver Type */
export type NameserverNsType = "udp";
export const NameserverNsType = /*@__PURE__*/ S.String;

export interface Nameserver {
	/** Nameserver IP */
	ip: string;
	/** Nameserver Type */
	ns_type: NameserverNsType;
	/** Nameserver Port */
	port: number;
}
export const Nameserver = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ip: S.String,
		ns_type: NameserverNsType,
		port: S.Number,
	}),
).annotate({ identifier: "Nameserver" }) as any as S.Schema<Nameserver>;

/** Nameserver list */
export type NameserverGroupNameserversList = ReadonlyArray<Nameserver>;
export const NameserverGroupNameserversList = /*@__PURE__*/ S.Array(
	Nameserver,
) as any as S.Schema<NameserverGroupNameserversList>;

/** Distribution group IDs that defines group of peers that will use this nameserver group */
export type NameserverGroupGroupsList = ReadonlyArray<string>;
export const NameserverGroupGroupsList = /*@__PURE__*/ S.Array(S.String) as any as S.Schema<NameserverGroupGroupsList>;

/** Match domain list. It should be empty only if primary is true. */
export type NameserverGroupDomainsList = ReadonlyArray<string>;
export const NameserverGroupDomainsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<NameserverGroupDomainsList>;

export interface NameserverGroup {
	/** Nameserver group ID */
	id: string;
	/** Name of nameserver group name */
	name: string;
	/** Description of the nameserver group */
	description: string;
	/** Nameserver list */
	nameservers: NameserverGroupNameserversList;
	/** Nameserver group status */
	enabled: boolean;
	/** Distribution group IDs that defines group of peers that will use this nameserver group */
	groups: NameserverGroupGroupsList;
	/** Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty. */
	primary: boolean;
	/** Match domain list. It should be empty only if primary is true. */
	domains: NameserverGroupDomainsList;
	/** Search domain status for match domains. It should be true only if domains list is not empty. */
	search_domains_enabled: boolean;
}
export const NameserverGroup = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		nameservers: NameserverGroupNameserversList,
		enabled: S.Boolean,
		groups: NameserverGroupGroupsList,
		primary: S.Boolean,
		domains: NameserverGroupDomainsList,
		search_domains_enabled: S.Boolean,
	}),
).annotate({ identifier: "NameserverGroup" }) as any as S.Schema<NameserverGroup>;

export type DnsNameserversGetResponseBodyList = ReadonlyArray<NameserverGroup>;
export const DnsNameserversGetResponseBodyList = /*@__PURE__*/ S.Array(
	NameserverGroup,
) as any as S.Schema<DnsNameserversGetResponseBodyList>;

export type DnsNameserversGetResponse = DnsNameserversGetResponseBodyList;
export const DnsNameserversGetResponse = /*@__PURE__*/ S.suspend(() =>
	DnsNameserversGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "DnsNameserversGetResponse" }) as any as S.Schema<DnsNameserversGetResponse>;

export interface DnsNameserversNsgroupIdDeleteRequest {
	/** The unique identifier of a Nameserver Group */
	nsgroupId: string;
}
export const DnsNameserversNsgroupIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		nsgroupId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/dns/nameservers/{nsgroupId}", code: 200 })),
).annotate({
	identifier: "DnsNameserversNsgroupIdDeleteRequest",
}) as any as S.Schema<DnsNameserversNsgroupIdDeleteRequest>;

export interface DnsNameserversNsgroupIdDeleteResponse {}
export const DnsNameserversNsgroupIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "DnsNameserversNsgroupIdDeleteResponse",
}) as any as S.Schema<DnsNameserversNsgroupIdDeleteResponse>;

export interface DnsNameserversNsgroupIdGetRequest {
	/** The unique identifier of a Nameserver Group */
	nsgroupId: string;
}
export const DnsNameserversNsgroupIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		nsgroupId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/dns/nameservers/{nsgroupId}", code: 200 })),
).annotate({ identifier: "DnsNameserversNsgroupIdGetRequest" }) as any as S.Schema<DnsNameserversNsgroupIdGetRequest>;

/** Nameserver list */
export type DnsNameserversNsgroupIdGetResponseNameserversList = ReadonlyArray<Nameserver>;
export const DnsNameserversNsgroupIdGetResponseNameserversList = /*@__PURE__*/ S.Array(
	Nameserver,
) as any as S.Schema<DnsNameserversNsgroupIdGetResponseNameserversList>;

/** Distribution group IDs that defines group of peers that will use this nameserver group */
export type DnsNameserversNsgroupIdGetResponseGroupsList = ReadonlyArray<string>;
export const DnsNameserversNsgroupIdGetResponseGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversNsgroupIdGetResponseGroupsList>;

/** Match domain list. It should be empty only if primary is true. */
export type DnsNameserversNsgroupIdGetResponseDomainsList = ReadonlyArray<string>;
export const DnsNameserversNsgroupIdGetResponseDomainsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversNsgroupIdGetResponseDomainsList>;

export interface DnsNameserversNsgroupIdGetResponse {
	/** Nameserver group ID */
	id: string;
	/** Name of nameserver group name */
	name: string;
	/** Description of the nameserver group */
	description: string;
	/** Nameserver list */
	nameservers: DnsNameserversNsgroupIdGetResponseNameserversList;
	/** Nameserver group status */
	enabled: boolean;
	/** Distribution group IDs that defines group of peers that will use this nameserver group */
	groups: DnsNameserversNsgroupIdGetResponseGroupsList;
	/** Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty. */
	primary: boolean;
	/** Match domain list. It should be empty only if primary is true. */
	domains: DnsNameserversNsgroupIdGetResponseDomainsList;
	/** Search domain status for match domains. It should be true only if domains list is not empty. */
	search_domains_enabled: boolean;
}
export const DnsNameserversNsgroupIdGetResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		nameservers: DnsNameserversNsgroupIdGetResponseNameserversList,
		enabled: S.Boolean,
		groups: DnsNameserversNsgroupIdGetResponseGroupsList,
		primary: S.Boolean,
		domains: DnsNameserversNsgroupIdGetResponseDomainsList,
		search_domains_enabled: S.Boolean,
	}),
).annotate({ identifier: "DnsNameserversNsgroupIdGetResponse" }) as any as S.Schema<DnsNameserversNsgroupIdGetResponse>;

/** Nameserver list */
export type DnsNameserversNsgroupIdPutRequestNameserversList = ReadonlyArray<Nameserver>;
export const DnsNameserversNsgroupIdPutRequestNameserversList = /*@__PURE__*/ S.Array(
	Nameserver,
) as any as S.Schema<DnsNameserversNsgroupIdPutRequestNameserversList>;

/** Distribution group IDs that defines group of peers that will use this nameserver group */
export type DnsNameserversNsgroupIdPutRequestGroupsList = ReadonlyArray<string>;
export const DnsNameserversNsgroupIdPutRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversNsgroupIdPutRequestGroupsList>;

/** Match domain list. It should be empty only if primary is true. */
export type DnsNameserversNsgroupIdPutRequestDomainsList = ReadonlyArray<string>;
export const DnsNameserversNsgroupIdPutRequestDomainsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversNsgroupIdPutRequestDomainsList>;

export interface DnsNameserversNsgroupIdPutRequest {
	/** The unique identifier of a Nameserver Group */
	nsgroupId: string;
	/** Name of nameserver group name */
	name: string;
	/** Description of the nameserver group */
	description: string;
	/** Nameserver list */
	nameservers: DnsNameserversNsgroupIdPutRequestNameserversList;
	/** Nameserver group status */
	enabled: boolean;
	/** Distribution group IDs that defines group of peers that will use this nameserver group */
	groups: DnsNameserversNsgroupIdPutRequestGroupsList;
	/** Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty. */
	primary: boolean;
	/** Match domain list. It should be empty only if primary is true. */
	domains: DnsNameserversNsgroupIdPutRequestDomainsList;
	/** Search domain status for match domains. It should be true only if domains list is not empty. */
	search_domains_enabled: boolean;
}
export const DnsNameserversNsgroupIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		nsgroupId: S.String.pipe(T.Label()),
		name: S.String,
		description: S.String,
		nameservers: DnsNameserversNsgroupIdPutRequestNameserversList,
		enabled: S.Boolean,
		groups: DnsNameserversNsgroupIdPutRequestGroupsList,
		primary: S.Boolean,
		domains: DnsNameserversNsgroupIdPutRequestDomainsList,
		search_domains_enabled: S.Boolean,
	}).pipe(T.Http({ method: "PUT", uri: "/api/dns/nameservers/{nsgroupId}", code: 200 })),
).annotate({ identifier: "DnsNameserversNsgroupIdPutRequest" }) as any as S.Schema<DnsNameserversNsgroupIdPutRequest>;

/** Nameserver list */
export type DnsNameserversNsgroupIdPutResponseNameserversList = ReadonlyArray<Nameserver>;
export const DnsNameserversNsgroupIdPutResponseNameserversList = /*@__PURE__*/ S.Array(
	Nameserver,
) as any as S.Schema<DnsNameserversNsgroupIdPutResponseNameserversList>;

/** Distribution group IDs that defines group of peers that will use this nameserver group */
export type DnsNameserversNsgroupIdPutResponseGroupsList = ReadonlyArray<string>;
export const DnsNameserversNsgroupIdPutResponseGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversNsgroupIdPutResponseGroupsList>;

/** Match domain list. It should be empty only if primary is true. */
export type DnsNameserversNsgroupIdPutResponseDomainsList = ReadonlyArray<string>;
export const DnsNameserversNsgroupIdPutResponseDomainsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversNsgroupIdPutResponseDomainsList>;

export interface DnsNameserversNsgroupIdPutResponse {
	/** Nameserver group ID */
	id: string;
	/** Name of nameserver group name */
	name: string;
	/** Description of the nameserver group */
	description: string;
	/** Nameserver list */
	nameservers: DnsNameserversNsgroupIdPutResponseNameserversList;
	/** Nameserver group status */
	enabled: boolean;
	/** Distribution group IDs that defines group of peers that will use this nameserver group */
	groups: DnsNameserversNsgroupIdPutResponseGroupsList;
	/** Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty. */
	primary: boolean;
	/** Match domain list. It should be empty only if primary is true. */
	domains: DnsNameserversNsgroupIdPutResponseDomainsList;
	/** Search domain status for match domains. It should be true only if domains list is not empty. */
	search_domains_enabled: boolean;
}
export const DnsNameserversNsgroupIdPutResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		nameservers: DnsNameserversNsgroupIdPutResponseNameserversList,
		enabled: S.Boolean,
		groups: DnsNameserversNsgroupIdPutResponseGroupsList,
		primary: S.Boolean,
		domains: DnsNameserversNsgroupIdPutResponseDomainsList,
		search_domains_enabled: S.Boolean,
	}),
).annotate({ identifier: "DnsNameserversNsgroupIdPutResponse" }) as any as S.Schema<DnsNameserversNsgroupIdPutResponse>;

/** Nameserver list */
export type DnsNameserversPostRequestNameserversList = ReadonlyArray<Nameserver>;
export const DnsNameserversPostRequestNameserversList = /*@__PURE__*/ S.Array(
	Nameserver,
) as any as S.Schema<DnsNameserversPostRequestNameserversList>;

/** Distribution group IDs that defines group of peers that will use this nameserver group */
export type DnsNameserversPostRequestGroupsList = ReadonlyArray<string>;
export const DnsNameserversPostRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversPostRequestGroupsList>;

/** Match domain list. It should be empty only if primary is true. */
export type DnsNameserversPostRequestDomainsList = ReadonlyArray<string>;
export const DnsNameserversPostRequestDomainsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversPostRequestDomainsList>;

export interface DnsNameserversPostRequest {
	/** Name of nameserver group name */
	name: string;
	/** Description of the nameserver group */
	description: string;
	/** Nameserver list */
	nameservers: DnsNameserversPostRequestNameserversList;
	/** Nameserver group status */
	enabled: boolean;
	/** Distribution group IDs that defines group of peers that will use this nameserver group */
	groups: DnsNameserversPostRequestGroupsList;
	/** Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty. */
	primary: boolean;
	/** Match domain list. It should be empty only if primary is true. */
	domains: DnsNameserversPostRequestDomainsList;
	/** Search domain status for match domains. It should be true only if domains list is not empty. */
	search_domains_enabled: boolean;
}
export const DnsNameserversPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		description: S.String,
		nameservers: DnsNameserversPostRequestNameserversList,
		enabled: S.Boolean,
		groups: DnsNameserversPostRequestGroupsList,
		primary: S.Boolean,
		domains: DnsNameserversPostRequestDomainsList,
		search_domains_enabled: S.Boolean,
	}).pipe(T.Http({ method: "POST", uri: "/api/dns/nameservers", code: 200 })),
).annotate({ identifier: "DnsNameserversPostRequest" }) as any as S.Schema<DnsNameserversPostRequest>;

/** Nameserver list */
export type DnsNameserversPostResponseNameserversList = ReadonlyArray<Nameserver>;
export const DnsNameserversPostResponseNameserversList = /*@__PURE__*/ S.Array(
	Nameserver,
) as any as S.Schema<DnsNameserversPostResponseNameserversList>;

/** Distribution group IDs that defines group of peers that will use this nameserver group */
export type DnsNameserversPostResponseGroupsList = ReadonlyArray<string>;
export const DnsNameserversPostResponseGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversPostResponseGroupsList>;

/** Match domain list. It should be empty only if primary is true. */
export type DnsNameserversPostResponseDomainsList = ReadonlyArray<string>;
export const DnsNameserversPostResponseDomainsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsNameserversPostResponseDomainsList>;

export interface DnsNameserversPostResponse {
	/** Nameserver group ID */
	id: string;
	/** Name of nameserver group name */
	name: string;
	/** Description of the nameserver group */
	description: string;
	/** Nameserver list */
	nameservers: DnsNameserversPostResponseNameserversList;
	/** Nameserver group status */
	enabled: boolean;
	/** Distribution group IDs that defines group of peers that will use this nameserver group */
	groups: DnsNameserversPostResponseGroupsList;
	/** Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty. */
	primary: boolean;
	/** Match domain list. It should be empty only if primary is true. */
	domains: DnsNameserversPostResponseDomainsList;
	/** Search domain status for match domains. It should be true only if domains list is not empty. */
	search_domains_enabled: boolean;
}
export const DnsNameserversPostResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		description: S.String,
		nameservers: DnsNameserversPostResponseNameserversList,
		enabled: S.Boolean,
		groups: DnsNameserversPostResponseGroupsList,
		primary: S.Boolean,
		domains: DnsNameserversPostResponseDomainsList,
		search_domains_enabled: S.Boolean,
	}),
).annotate({ identifier: "DnsNameserversPostResponse" }) as any as S.Schema<DnsNameserversPostResponse>;

export interface DnsSettingsGetRequest {}
export const DnsSettingsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/dns/settings", code: 200 })),
).annotate({ identifier: "DnsSettingsGetRequest" }) as any as S.Schema<DnsSettingsGetRequest>;

export type DnsSettingsGetResponse = unknown;
export const DnsSettingsGetResponse = /*@__PURE__*/ S.suspend(() => S.Unknown.pipe(T.RawResponseRoot())).annotate({
	identifier: "DnsSettingsGetResponse",
}) as any as S.Schema<DnsSettingsGetResponse>;

/** Groups whose DNS management is disabled */
export type DnsSettingsPutRequestDisabledManagementGroupsList = ReadonlyArray<string>;
export const DnsSettingsPutRequestDisabledManagementGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DnsSettingsPutRequestDisabledManagementGroupsList>;

export interface DnsSettingsPutRequest {
	/** Groups whose DNS management is disabled */
	disabled_management_groups: DnsSettingsPutRequestDisabledManagementGroupsList;
}
export const DnsSettingsPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		disabled_management_groups: DnsSettingsPutRequestDisabledManagementGroupsList,
	}).pipe(T.Http({ method: "PUT", uri: "/api/dns/settings", code: 200 })),
).annotate({ identifier: "DnsSettingsPutRequest" }) as any as S.Schema<DnsSettingsPutRequest>;

/** Groups whose DNS management is disabled */
export type DNSSettingsDisabledManagementGroupsList = ReadonlyArray<string>;
export const DNSSettingsDisabledManagementGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<DNSSettingsDisabledManagementGroupsList>;

export interface DNSSettings {
	/** Groups whose DNS management is disabled */
	disabled_management_groups: DNSSettingsDisabledManagementGroupsList;
}
export const DNSSettings = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		disabled_management_groups: DNSSettingsDisabledManagementGroupsList,
	}),
).annotate({ identifier: "DNSSettings" }) as any as S.Schema<DNSSettings>;

export type DnsNameserversGetError = BadRequest | Forbidden | NetbirdOpError;
/** List all Nameserver Groups Returns a list of all Nameserver Groups */
export const dnsNameserversGet: API.OperationMethod<
	DnsNameserversGetRequest,
	DnsNameserversGetResponse,
	DnsNameserversGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsNameserversGetRequest,
	output: DnsNameserversGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type DnsNameserversNsgroupIdDeleteError = BadRequest | Forbidden | NetbirdOpError;
/** Delete a Nameserver Group Delete a Nameserver Group */
export const dnsNameserversNsgroupIdDelete: API.OperationMethod<
	DnsNameserversNsgroupIdDeleteRequest,
	DnsNameserversNsgroupIdDeleteResponse,
	DnsNameserversNsgroupIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsNameserversNsgroupIdDeleteRequest,
	output: DnsNameserversNsgroupIdDeleteResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type DnsNameserversNsgroupIdGetError = BadRequest | Forbidden | NetbirdOpError;
/** Retrieve a Nameserver Group Get information about a Nameserver Groups */
export const dnsNameserversNsgroupIdGet: API.OperationMethod<
	DnsNameserversNsgroupIdGetRequest,
	DnsNameserversNsgroupIdGetResponse,
	DnsNameserversNsgroupIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsNameserversNsgroupIdGetRequest,
	output: DnsNameserversNsgroupIdGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type DnsNameserversNsgroupIdPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update a Nameserver Group Update/Replace a Nameserver Group */
export const dnsNameserversNsgroupIdPut: API.OperationMethod<
	DnsNameserversNsgroupIdPutRequest,
	DnsNameserversNsgroupIdPutResponse,
	DnsNameserversNsgroupIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsNameserversNsgroupIdPutRequest,
	output: DnsNameserversNsgroupIdPutResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type DnsNameserversPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create a Nameserver Group Creates a Nameserver Group */
export const dnsNameserversPost: API.OperationMethod<
	DnsNameserversPostRequest,
	DnsNameserversPostResponse,
	DnsNameserversPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsNameserversPostRequest,
	output: DnsNameserversPostResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type DnsSettingsGetError = BadRequest | Forbidden | NetbirdOpError;
/** Retrieve DNS settings Returns a DNS settings object */
export const dnsSettingsGet: API.OperationMethod<
	DnsSettingsGetRequest,
	DnsSettingsGetResponse,
	DnsSettingsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsSettingsGetRequest,
	output: DnsSettingsGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type DnsSettingsPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update DNS Settings Updates a DNS settings object */
export const dnsSettingsPut: API.OperationMethod<
	DnsSettingsPutRequest,
	DNSSettings,
	DnsSettingsPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: DnsSettingsPutRequest,
	output: DNSSettings,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
