import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsEdrFleetdmDeleteRequest {}
export const IntegrationsEdrFleetdmDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/edr/fleetdm", code: 200 })),
).annotate({
	identifier: "IntegrationsEdrFleetdmDeleteRequest",
}) as any as S.Schema<IntegrationsEdrFleetdmDeleteRequest>;

export type IntegrationsEdrFleetdmDeleteResponse = unknown;
export const IntegrationsEdrFleetdmDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsEdrFleetdmDeleteResponse",
}) as any as S.Schema<IntegrationsEdrFleetdmDeleteResponse>;

export interface IntegrationsEdrFleetdmGetRequest {}
export const IntegrationsEdrFleetdmGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/edr/fleetdm", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFleetdmGetRequest" }) as any as S.Schema<IntegrationsEdrFleetdmGetRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupIssued = "api" | "integration" | "jwt";
export const GroupIssued = /*@__PURE__*/ S.String;

export interface PeerMinimum {
	/** Peer ID */
	id: string;
	/** Peer's hostname */
	name: string;
}
export const PeerMinimum = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
	}),
).annotate({ identifier: "PeerMinimum" }) as any as S.Schema<PeerMinimum>;

/** List of peers object */
export type GroupPeersList = ReadonlyArray<PeerMinimum>;
export const GroupPeersList = /*@__PURE__*/ S.Array(PeerMinimum) as any as S.Schema<GroupPeersList>;

export interface Resource {
	/** ID of the resource */
	id: string;
	/** Type of the resource */
	type: unknown;
}
export const Resource = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: S.Unknown,
	}),
).annotate({ identifier: "Resource" }) as any as S.Schema<Resource>;

export type GroupResourcesList = ReadonlyArray<Resource>;
export const GroupResourcesList = /*@__PURE__*/ S.Array(Resource) as any as S.Schema<GroupResourcesList>;

export interface Group {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupIssued;
	/** List of peers object */
	peers: GroupPeersList | null;
	resources: GroupResourcesList | null;
}
export const Group = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupIssued),
		peers: S.NullOr(GroupPeersList),
		resources: S.NullOr(GroupResourcesList),
	}),
).annotate({ identifier: "Group" }) as any as S.Schema<Group>;

/** List of groups */
export type EDRFleetDMResponseGroupsList = ReadonlyArray<Group>;
export const EDRFleetDMResponseGroupsList = /*@__PURE__*/ S.Array(
	Group,
) as any as S.Schema<EDRFleetDMResponseGroupsList>;

/** List of FleetDM policy IDs that must be passing on the host. If any of these policies is failing, the host is non-compliant */
export type FleetDMMatchAttributesRequiredPoliciesList = ReadonlyArray<number>;
export const FleetDMMatchAttributesRequiredPoliciesList = /*@__PURE__*/ S.Array(
	S.Number,
) as any as S.Schema<FleetDMMatchAttributesRequiredPoliciesList>;

/** Attribute conditions to match when approving FleetDM hosts. Most attributes work with FleetDM's free/open-source version. Premium-only attributes are marked accordingly */
export interface FleetDMMatchAttributes {
	/** Whether disk encryption (FileVault/BitLocker) must be enabled on the host */
	disk_encryption_enabled?: boolean;
	/** Maximum number of allowed failing policies. Use 0 to require all policies to pass */
	failing_policies_count_max?: number;
	/** Maximum number of allowed vulnerable software on the host */
	vulnerable_software_count_max?: number;
	/** Whether the host must be online (recently seen by Fleet) */
	status_online?: boolean;
	/** List of FleetDM policy IDs that must be passing on the host. If any of these policies is failing, the host is non-compliant */
	required_policies?: FleetDMMatchAttributesRequiredPoliciesList;
}
export const FleetDMMatchAttributes = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		disk_encryption_enabled: S.optional(S.Boolean),
		failing_policies_count_max: S.optional(S.Number),
		vulnerable_software_count_max: S.optional(S.Number),
		status_online: S.optional(S.Boolean),
		required_policies: S.optional(FleetDMMatchAttributesRequiredPoliciesList),
	}),
).annotate({ identifier: "FleetDMMatchAttributes" }) as any as S.Schema<FleetDMMatchAttributes>;

/** Represents a FleetDM EDR integration configuration */
export interface EDRFleetDMResponse {
	/** The unique numeric identifier for the integration. */
	id: number;
	/** The identifier of the account this integration belongs to. */
	account_id: string;
	/** FleetDM server URL */
	api_url: string;
	/** Timestamp of when the integration was last synced. */
	last_synced_at: string;
	/** The user id that created the integration */
	created_by: string;
	/** Timestamp of when the integration was created. */
	created_at: string;
	/** Timestamp of when the integration was last updated. */
	updated_at: string;
	/** List of groups */
	groups: EDRFleetDMResponseGroupsList;
	/** The devices last sync requirement interval in hours. */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled: boolean;
	match_attributes: FleetDMMatchAttributes;
}
export const EDRFleetDMResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number,
		account_id: S.String,
		api_url: S.String,
		last_synced_at: S.String,
		created_by: S.String,
		created_at: S.String,
		updated_at: S.String,
		groups: EDRFleetDMResponseGroupsList,
		last_synced_interval: S.Number,
		enabled: S.Boolean,
		match_attributes: FleetDMMatchAttributes,
	}),
).annotate({ identifier: "EDRFleetDMResponse" }) as any as S.Schema<EDRFleetDMResponse>;

/** The Groups this integrations applies to */
export type IntegrationsEdrFleetdmPostRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrFleetdmPostRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrFleetdmPostRequestGroupsList>;

export interface IntegrationsEdrFleetdmPostRequest {
	/** FleetDM server URL */
	api_url: string;
	/** FleetDM API token */
	api_token: string | Redacted.Redacted<string>;
	/** The Groups this integrations applies to */
	groups: IntegrationsEdrFleetdmPostRequestGroupsList;
	/** The devices last sync requirement interval in hours. Minimum value is 24 hours */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
	match_attributes: FleetDMMatchAttributes;
}
export const IntegrationsEdrFleetdmPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		api_url: S.String,
		api_token: S.String.pipe(T.SensitiveValue({})),
		groups: IntegrationsEdrFleetdmPostRequestGroupsList,
		last_synced_interval: S.Number,
		enabled: S.optional(S.Boolean),
		match_attributes: FleetDMMatchAttributes,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/edr/fleetdm", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFleetdmPostRequest" }) as any as S.Schema<IntegrationsEdrFleetdmPostRequest>;

/** The Groups this integrations applies to */
export type IntegrationsEdrFleetdmPutRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrFleetdmPutRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrFleetdmPutRequestGroupsList>;

export interface IntegrationsEdrFleetdmPutRequest {
	/** FleetDM server URL */
	api_url: string;
	/** FleetDM API token */
	api_token: string | Redacted.Redacted<string>;
	/** The Groups this integrations applies to */
	groups: IntegrationsEdrFleetdmPutRequestGroupsList;
	/** The devices last sync requirement interval in hours. Minimum value is 24 hours */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
	match_attributes: FleetDMMatchAttributes;
}
export const IntegrationsEdrFleetdmPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		api_url: S.String,
		api_token: S.String.pipe(T.SensitiveValue({})),
		groups: IntegrationsEdrFleetdmPutRequestGroupsList,
		last_synced_interval: S.Number,
		enabled: S.optional(S.Boolean),
		match_attributes: FleetDMMatchAttributes,
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/edr/fleetdm", code: 200 })),
).annotate({ identifier: "IntegrationsEdrFleetdmPutRequest" }) as any as S.Schema<IntegrationsEdrFleetdmPutRequest>;

export type IntegrationsEdrFleetdmDeleteError = BadRequest | NotFound | NetbirdOpError;
/** Delete EDR FleetDM Integration Deletes an EDR FleetDM Integration by its ID. */
export const integrationsEdrFleetdmDelete: API.OperationMethod<
	IntegrationsEdrFleetdmDeleteRequest,
	IntegrationsEdrFleetdmDeleteResponse,
	IntegrationsEdrFleetdmDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFleetdmDeleteRequest,
	output: IntegrationsEdrFleetdmDeleteResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrFleetdmGetError = BadRequest | NotFound | NetbirdOpError;
/** Get EDR FleetDM Integration Retrieves a specific EDR FleetDM integration by its ID. */
export const integrationsEdrFleetdmGet: API.OperationMethod<
	IntegrationsEdrFleetdmGetRequest,
	EDRFleetDMResponse,
	IntegrationsEdrFleetdmGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFleetdmGetRequest,
	output: EDRFleetDMResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrFleetdmPostError = BadRequest | NetbirdOpError;
/** Create EDR FleetDM Integration Creates a new EDR FleetDM integration */
export const integrationsEdrFleetdmPost: API.OperationMethod<
	IntegrationsEdrFleetdmPostRequest,
	EDRFleetDMResponse,
	IntegrationsEdrFleetdmPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFleetdmPostRequest,
	output: EDRFleetDMResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrFleetdmPutError = BadRequest | NotFound | NetbirdOpError;
/** Update EDR FleetDM Integration Updates an existing EDR FleetDM Integration. */
export const integrationsEdrFleetdmPut: API.OperationMethod<
	IntegrationsEdrFleetdmPutRequest,
	EDRFleetDMResponse,
	IntegrationsEdrFleetdmPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrFleetdmPutRequest,
	output: EDRFleetDMResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
