import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";
import type * as Redacted from "effect/Redacted";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsEdrIntuneDeleteRequest {}
export const IntegrationsEdrIntuneDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/edr/intune", code: 200 })),
).annotate({ identifier: "IntegrationsEdrIntuneDeleteRequest" }) as any as S.Schema<IntegrationsEdrIntuneDeleteRequest>;

export type IntegrationsEdrIntuneDeleteResponse = unknown;
export const IntegrationsEdrIntuneDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsEdrIntuneDeleteResponse",
}) as any as S.Schema<IntegrationsEdrIntuneDeleteResponse>;

export interface IntegrationsEdrIntuneGetRequest {}
export const IntegrationsEdrIntuneGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/edr/intune", code: 200 })),
).annotate({ identifier: "IntegrationsEdrIntuneGetRequest" }) as any as S.Schema<IntegrationsEdrIntuneGetRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupIssued = "api" | "integration" | "jwt";
export const GroupIssued = /*@__PURE__*/ S.String;

export interface PeerMinimum {
	/** Peer ID */
	id: string;
	/** Peer's hostname */
	name: string;
}
export const PeerMinimum = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
	}),
).annotate({ identifier: "PeerMinimum" }) as any as S.Schema<PeerMinimum>;

/** List of peers object */
export type GroupPeersList = ReadonlyArray<PeerMinimum>;
export const GroupPeersList = /*@__PURE__*/ S.Array(PeerMinimum) as any as S.Schema<GroupPeersList>;

export interface Resource {
	/** ID of the resource */
	id: string;
	/** Type of the resource */
	type: unknown;
}
export const Resource = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: S.Unknown,
	}),
).annotate({ identifier: "Resource" }) as any as S.Schema<Resource>;

export type GroupResourcesList = ReadonlyArray<Resource>;
export const GroupResourcesList = /*@__PURE__*/ S.Array(Resource) as any as S.Schema<GroupResourcesList>;

export interface Group {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupIssued;
	/** List of peers object */
	peers: GroupPeersList | null;
	resources: GroupResourcesList | null;
}
export const Group = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupIssued),
		peers: S.NullOr(GroupPeersList),
		resources: S.NullOr(GroupResourcesList),
	}),
).annotate({ identifier: "Group" }) as any as S.Schema<Group>;

/** List of groups */
export type EDRIntuneResponseGroupsList = ReadonlyArray<Group>;
export const EDRIntuneResponseGroupsList = /*@__PURE__*/ S.Array(Group) as any as S.Schema<EDRIntuneResponseGroupsList>;

/** Represents a Intune EDR integration configuration */
export interface EDRIntuneResponse {
	/** The unique numeric identifier for the integration. */
	id: number;
	/** The identifier of the account this integration belongs to. */
	account_id: string;
	/** Timestamp of when the integration was last synced. */
	last_synced_at: string;
	/** The user id that created the integration */
	created_by: string;
	/** Timestamp of when the integration was created. */
	created_at: string;
	/** Timestamp of when the integration was last updated. */
	updated_at: string;
	/** The Azure application client id */
	client_id: string;
	/** The Azure tenant id */
	tenant_id: string;
	/** List of groups */
	groups: EDRIntuneResponseGroupsList;
	/** The devices last sync requirement interval in hours. */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled: boolean;
}
export const EDRIntuneResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number,
		account_id: S.String,
		last_synced_at: S.String,
		created_by: S.String,
		created_at: S.String,
		updated_at: S.String,
		client_id: S.String,
		tenant_id: S.String,
		groups: EDRIntuneResponseGroupsList,
		last_synced_interval: S.Number,
		enabled: S.Boolean,
	}),
).annotate({ identifier: "EDRIntuneResponse" }) as any as S.Schema<EDRIntuneResponse>;

/** The Groups this integrations applies to */
export type IntegrationsEdrIntunePostRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrIntunePostRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrIntunePostRequestGroupsList>;

export interface IntegrationsEdrIntunePostRequest {
	/** The Azure application client id */
	client_id: string;
	/** The Azure tenant id */
	tenant_id: string;
	/** The Azure application client secret */
	secret: string | Redacted.Redacted<string>;
	/** The Groups this integrations applies to */
	groups: IntegrationsEdrIntunePostRequestGroupsList;
	/** The devices last sync requirement interval in hours. Minimum value is 24 hours. */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
}
export const IntegrationsEdrIntunePostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		client_id: S.String,
		tenant_id: S.String,
		secret: S.String.pipe(T.SensitiveValue({})),
		groups: IntegrationsEdrIntunePostRequestGroupsList,
		last_synced_interval: S.Number,
		enabled: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/edr/intune", code: 200 })),
).annotate({ identifier: "IntegrationsEdrIntunePostRequest" }) as any as S.Schema<IntegrationsEdrIntunePostRequest>;

/** The Groups this integrations applies to */
export type IntegrationsEdrIntunePutRequestGroupsList = ReadonlyArray<string>;
export const IntegrationsEdrIntunePutRequestGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsEdrIntunePutRequestGroupsList>;

export interface IntegrationsEdrIntunePutRequest {
	/** The Azure application client id */
	client_id: string;
	/** The Azure tenant id */
	tenant_id: string;
	/** The Azure application client secret */
	secret: string | Redacted.Redacted<string>;
	/** The Groups this integrations applies to */
	groups: IntegrationsEdrIntunePutRequestGroupsList;
	/** The devices last sync requirement interval in hours. Minimum value is 24 hours. */
	last_synced_interval: number;
	/** Indicates whether the integration is enabled */
	enabled?: boolean;
}
export const IntegrationsEdrIntunePutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		client_id: S.String,
		tenant_id: S.String,
		secret: S.String.pipe(T.SensitiveValue({})),
		groups: IntegrationsEdrIntunePutRequestGroupsList,
		last_synced_interval: S.Number,
		enabled: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/edr/intune", code: 200 })),
).annotate({ identifier: "IntegrationsEdrIntunePutRequest" }) as any as S.Schema<IntegrationsEdrIntunePutRequest>;

export type IntegrationsEdrIntuneDeleteError = BadRequest | NotFound | NetbirdOpError;
/** Delete EDR Intune Integration Deletes an EDR Intune Integration by its ID. */
export const integrationsEdrIntuneDelete: API.OperationMethod<
	IntegrationsEdrIntuneDeleteRequest,
	IntegrationsEdrIntuneDeleteResponse,
	IntegrationsEdrIntuneDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrIntuneDeleteRequest,
	output: IntegrationsEdrIntuneDeleteResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrIntuneGetError = BadRequest | NotFound | NetbirdOpError;
/** Get EDR Intune Integration Retrieves a specific EDR Intune integration by its ID. */
export const integrationsEdrIntuneGet: API.OperationMethod<
	IntegrationsEdrIntuneGetRequest,
	EDRIntuneResponse,
	IntegrationsEdrIntuneGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrIntuneGetRequest,
	output: EDRIntuneResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrIntunePostError = BadRequest | NetbirdOpError;
/** Create EDR Intune Integration Creates a new EDR Intune integration for the authenticated account. */
export const integrationsEdrIntunePost: API.OperationMethod<
	IntegrationsEdrIntunePostRequest,
	EDRIntuneResponse,
	IntegrationsEdrIntunePostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrIntunePostRequest,
	output: EDRIntuneResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsEdrIntunePutError = BadRequest | NotFound | NetbirdOpError;
/** Update EDR Intune Integration Updates an existing EDR Intune Integration. The request body structure is `EDRIntuneRequest`. */
export const integrationsEdrIntunePut: API.OperationMethod<
	IntegrationsEdrIntunePutRequest,
	EDRIntuneResponse,
	IntegrationsEdrIntunePutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsEdrIntunePutRequest,
	output: EDRIntuneResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
