import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface GroupsGetRequest {
	/** Filter groups by name (exact match) */
	name?: string;
}
export const GroupsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.optional(S.String.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/groups", code: 200 })),
).annotate({ identifier: "GroupsGetRequest" }) as any as S.Schema<GroupsGetRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupIssued = "api" | "integration" | "jwt";
export const GroupIssued = /*@__PURE__*/ S.String;

export interface PeerMinimum {
	/** Peer ID */
	id: string;
	/** Peer's hostname */
	name: string;
}
export const PeerMinimum = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
	}),
).annotate({ identifier: "PeerMinimum" }) as any as S.Schema<PeerMinimum>;

/** List of peers object */
export type GroupPeersList = ReadonlyArray<PeerMinimum>;
export const GroupPeersList = /*@__PURE__*/ S.Array(PeerMinimum) as any as S.Schema<GroupPeersList>;

export interface Resource {
	/** ID of the resource */
	id: string;
	/** Type of the resource */
	type: unknown;
}
export const Resource = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: S.Unknown,
	}),
).annotate({ identifier: "Resource" }) as any as S.Schema<Resource>;

export type GroupResourcesList = ReadonlyArray<Resource>;
export const GroupResourcesList = /*@__PURE__*/ S.Array(Resource) as any as S.Schema<GroupResourcesList>;

export interface Group {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupIssued;
	/** List of peers object */
	peers: GroupPeersList | null;
	resources: GroupResourcesList | null;
}
export const Group = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupIssued),
		peers: S.NullOr(GroupPeersList),
		resources: S.NullOr(GroupResourcesList),
	}),
).annotate({ identifier: "Group" }) as any as S.Schema<Group>;

export type GroupsGetResponseBodyList = ReadonlyArray<Group>;
export const GroupsGetResponseBodyList = /*@__PURE__*/ S.Array(Group) as any as S.Schema<GroupsGetResponseBodyList>;

export type GroupsGetResponse = GroupsGetResponseBodyList;
export const GroupsGetResponse = /*@__PURE__*/ S.suspend(() =>
	GroupsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "GroupsGetResponse" }) as any as S.Schema<GroupsGetResponse>;

export interface GroupsGroupIdDeleteRequest {
	/** The unique identifier of a group */
	groupId: string;
}
export const GroupsGroupIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		groupId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/groups/{groupId}", code: 200 })),
).annotate({ identifier: "GroupsGroupIdDeleteRequest" }) as any as S.Schema<GroupsGroupIdDeleteRequest>;

export interface GroupsGroupIdDeleteResponse {}
export const GroupsGroupIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "GroupsGroupIdDeleteResponse",
}) as any as S.Schema<GroupsGroupIdDeleteResponse>;

export interface GroupsGroupIdGetRequest {
	/** The unique identifier of a group */
	groupId: string;
}
export const GroupsGroupIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		groupId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/groups/{groupId}", code: 200 })),
).annotate({ identifier: "GroupsGroupIdGetRequest" }) as any as S.Schema<GroupsGroupIdGetRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupsGroupIdGetResponseIssued = "api" | "integration" | "jwt";
export const GroupsGroupIdGetResponseIssued = /*@__PURE__*/ S.String;

/** List of peers object */
export type GroupsGroupIdGetResponsePeersList = ReadonlyArray<PeerMinimum>;
export const GroupsGroupIdGetResponsePeersList = /*@__PURE__*/ S.Array(
	PeerMinimum,
) as any as S.Schema<GroupsGroupIdGetResponsePeersList>;

export type GroupsGroupIdGetResponseResourcesList = ReadonlyArray<Resource>;
export const GroupsGroupIdGetResponseResourcesList = /*@__PURE__*/ S.Array(
	Resource,
) as any as S.Schema<GroupsGroupIdGetResponseResourcesList>;

export interface GroupsGroupIdGetResponse {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupsGroupIdGetResponseIssued;
	/** List of peers object */
	peers: GroupsGroupIdGetResponsePeersList | null;
	resources: GroupsGroupIdGetResponseResourcesList | null;
}
export const GroupsGroupIdGetResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupsGroupIdGetResponseIssued),
		peers: S.NullOr(GroupsGroupIdGetResponsePeersList),
		resources: S.NullOr(GroupsGroupIdGetResponseResourcesList),
	}),
).annotate({ identifier: "GroupsGroupIdGetResponse" }) as any as S.Schema<GroupsGroupIdGetResponse>;

/** List of peers ids */
export type GroupsGroupIdPutRequestPeersList = ReadonlyArray<string>;
export const GroupsGroupIdPutRequestPeersList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<GroupsGroupIdPutRequestPeersList>;

export type GroupsGroupIdPutRequestResourcesList = ReadonlyArray<Resource>;
export const GroupsGroupIdPutRequestResourcesList = /*@__PURE__*/ S.Array(
	Resource,
) as any as S.Schema<GroupsGroupIdPutRequestResourcesList>;

export interface GroupsGroupIdPutRequest {
	/** The unique identifier of a group */
	groupId: string;
	/** Group name identifier */
	name: string;
	/** List of peers ids */
	peers?: GroupsGroupIdPutRequestPeersList;
	resources?: GroupsGroupIdPutRequestResourcesList;
}
export const GroupsGroupIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		groupId: S.String.pipe(T.Label()),
		name: S.String,
		peers: S.optional(GroupsGroupIdPutRequestPeersList),
		resources: S.optional(GroupsGroupIdPutRequestResourcesList),
	}).pipe(T.Http({ method: "PUT", uri: "/api/groups/{groupId}", code: 200 })),
).annotate({ identifier: "GroupsGroupIdPutRequest" }) as any as S.Schema<GroupsGroupIdPutRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupsGroupIdPutResponseIssued = "api" | "integration" | "jwt";
export const GroupsGroupIdPutResponseIssued = /*@__PURE__*/ S.String;

/** List of peers object */
export type GroupsGroupIdPutResponsePeersList = ReadonlyArray<PeerMinimum>;
export const GroupsGroupIdPutResponsePeersList = /*@__PURE__*/ S.Array(
	PeerMinimum,
) as any as S.Schema<GroupsGroupIdPutResponsePeersList>;

export type GroupsGroupIdPutResponseResourcesList = ReadonlyArray<Resource>;
export const GroupsGroupIdPutResponseResourcesList = /*@__PURE__*/ S.Array(
	Resource,
) as any as S.Schema<GroupsGroupIdPutResponseResourcesList>;

export interface GroupsGroupIdPutResponse {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupsGroupIdPutResponseIssued;
	/** List of peers object */
	peers: GroupsGroupIdPutResponsePeersList | null;
	resources: GroupsGroupIdPutResponseResourcesList | null;
}
export const GroupsGroupIdPutResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupsGroupIdPutResponseIssued),
		peers: S.NullOr(GroupsGroupIdPutResponsePeersList),
		resources: S.NullOr(GroupsGroupIdPutResponseResourcesList),
	}),
).annotate({ identifier: "GroupsGroupIdPutResponse" }) as any as S.Schema<GroupsGroupIdPutResponse>;

/** List of peers ids */
export type GroupsPostRequestPeersList = ReadonlyArray<string>;
export const GroupsPostRequestPeersList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<GroupsPostRequestPeersList>;

export type GroupsPostRequestResourcesList = ReadonlyArray<Resource>;
export const GroupsPostRequestResourcesList = /*@__PURE__*/ S.Array(
	Resource,
) as any as S.Schema<GroupsPostRequestResourcesList>;

export interface GroupsPostRequest {
	/** Group name identifier */
	name: string;
	/** List of peers ids */
	peers?: GroupsPostRequestPeersList;
	resources?: GroupsPostRequestResourcesList;
}
export const GroupsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		peers: S.optional(GroupsPostRequestPeersList),
		resources: S.optional(GroupsPostRequestResourcesList),
	}).pipe(T.Http({ method: "POST", uri: "/api/groups", code: 200 })),
).annotate({ identifier: "GroupsPostRequest" }) as any as S.Schema<GroupsPostRequest>;

/** How the group was issued (api, integration, jwt) */
export type GroupsPostResponseIssued = "api" | "integration" | "jwt";
export const GroupsPostResponseIssued = /*@__PURE__*/ S.String;

/** List of peers object */
export type GroupsPostResponsePeersList = ReadonlyArray<PeerMinimum>;
export const GroupsPostResponsePeersList = /*@__PURE__*/ S.Array(
	PeerMinimum,
) as any as S.Schema<GroupsPostResponsePeersList>;

export type GroupsPostResponseResourcesList = ReadonlyArray<Resource>;
export const GroupsPostResponseResourcesList = /*@__PURE__*/ S.Array(
	Resource,
) as any as S.Schema<GroupsPostResponseResourcesList>;

export interface GroupsPostResponse {
	/** Group ID */
	id: string;
	/** Group Name identifier */
	name: string;
	/** Count of peers associated to the group */
	peers_count: number;
	/** Count of resources associated to the group */
	resources_count: number;
	/** How the group was issued (api, integration, jwt) */
	issued?: GroupsPostResponseIssued;
	/** List of peers object */
	peers: GroupsPostResponsePeersList | null;
	resources: GroupsPostResponseResourcesList | null;
}
export const GroupsPostResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		peers_count: S.Number,
		resources_count: S.Number,
		issued: S.optional(GroupsPostResponseIssued),
		peers: S.NullOr(GroupsPostResponsePeersList),
		resources: S.NullOr(GroupsPostResponseResourcesList),
	}),
).annotate({ identifier: "GroupsPostResponse" }) as any as S.Schema<GroupsPostResponse>;

export type GroupsGetError = BadRequest | Forbidden | NotFound | NetbirdOpError;
/** List all Groups Returns a list of all groups */
export const groupsGet: API.OperationMethod<GroupsGetRequest, GroupsGetResponse, GroupsGetError, NetbirdOpContext> =
	/*@__PURE__*/ API.make(() => ({
		input: GroupsGetRequest,
		output: GroupsGetResponse,
		errors: [BadRequest, Forbidden, NotFound, UnknownNetbirdError],
		protocol: NetbirdProtocol,
		retry: Retry.Retry,
	}));

export type GroupsGroupIdDeleteError = BadRequest | Forbidden | NetbirdOpError;
/** Delete a Group Delete a group */
export const groupsGroupIdDelete: API.OperationMethod<
	GroupsGroupIdDeleteRequest,
	GroupsGroupIdDeleteResponse,
	GroupsGroupIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: GroupsGroupIdDeleteRequest,
	output: GroupsGroupIdDeleteResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type GroupsGroupIdGetError = BadRequest | Forbidden | NetbirdOpError;
/** Retrieve a Group Get information about a group */
export const groupsGroupIdGet: API.OperationMethod<
	GroupsGroupIdGetRequest,
	GroupsGroupIdGetResponse,
	GroupsGroupIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: GroupsGroupIdGetRequest,
	output: GroupsGroupIdGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type GroupsGroupIdPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update a Group Update/Replace a group */
export const groupsGroupIdPut: API.OperationMethod<
	GroupsGroupIdPutRequest,
	GroupsGroupIdPutResponse,
	GroupsGroupIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: GroupsGroupIdPutRequest,
	output: GroupsGroupIdPutResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type GroupsPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create a Group Creates a group */
export const groupsPost: API.OperationMethod<GroupsPostRequest, GroupsPostResponse, GroupsPostError, NetbirdOpContext> =
	/*@__PURE__*/ API.make(() => ({
		input: GroupsPostRequest,
		output: GroupsPostResponse,
		errors: [BadRequest, Forbidden, UnknownNetbirdError],
		protocol: NetbirdProtocol,
		retry: Retry.Retry,
	}));
