import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsScimIdpGetRequest {}
export const IntegrationsScimIdpGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/scim-idp", code: 200 })),
).annotate({ identifier: "IntegrationsScimIdpGetRequest" }) as any as S.Schema<IntegrationsScimIdpGetRequest>;

/** List of start_with string patterns for groups to sync */
export type ScimIntegrationGroupPrefixesList = ReadonlyArray<string>;
export const ScimIntegrationGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<ScimIntegrationGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type ScimIntegrationUserGroupPrefixesList = ReadonlyArray<string>;
export const ScimIntegrationUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<ScimIntegrationUserGroupPrefixesList>;

export interface ScimIntegration {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: ScimIntegrationGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: ScimIntegrationUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** The connection prefix used for the SCIM provider */
	prefix: string;
	/** Name of the SCIM identity provider */
	provider: string;
	/** SCIM API token (full on creation, masked otherwise) */
	auth_token: string;
	/** Timestamp of when the integration was last synced */
	last_synced_at: string;
}
export const ScimIntegration = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: ScimIntegrationGroupPrefixesList,
		user_group_prefixes: ScimIntegrationUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		prefix: S.String,
		provider: S.String,
		auth_token: S.String,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "ScimIntegration" }) as any as S.Schema<ScimIntegration>;

export type IntegrationsScimIdpGetResponseBodyList = ReadonlyArray<ScimIntegration>;
export const IntegrationsScimIdpGetResponseBodyList = /*@__PURE__*/ S.Array(
	ScimIntegration,
) as any as S.Schema<IntegrationsScimIdpGetResponseBodyList>;

export type IntegrationsScimIdpGetResponse = IntegrationsScimIdpGetResponseBodyList;
export const IntegrationsScimIdpGetResponse = /*@__PURE__*/ S.suspend(() =>
	IntegrationsScimIdpGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "IntegrationsScimIdpGetResponse" }) as any as S.Schema<IntegrationsScimIdpGetResponse>;

export interface IntegrationsScimIdpIdDeleteRequest {
	/** The unique identifier of the SCIM IDP integration. */
	id: number;
}
export const IntegrationsScimIdpIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/scim-idp/{id}", code: 200 })),
).annotate({ identifier: "IntegrationsScimIdpIdDeleteRequest" }) as any as S.Schema<IntegrationsScimIdpIdDeleteRequest>;

export type IntegrationsScimIdpIdDeleteResponse = unknown;
export const IntegrationsScimIdpIdDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsScimIdpIdDeleteResponse",
}) as any as S.Schema<IntegrationsScimIdpIdDeleteResponse>;

export interface IntegrationsScimIdpIdGetRequest {
	/** The unique identifier of the SCIM IDP integration. */
	id: number;
}
export const IntegrationsScimIdpIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/scim-idp/{id}", code: 200 })),
).annotate({ identifier: "IntegrationsScimIdpIdGetRequest" }) as any as S.Schema<IntegrationsScimIdpIdGetRequest>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsScimIdpIdGetResponseGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpIdGetResponseGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpIdGetResponseGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsScimIdpIdGetResponseUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpIdGetResponseUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpIdGetResponseUserGroupPrefixesList>;

export interface IntegrationsScimIdpIdGetResponse {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: IntegrationsScimIdpIdGetResponseGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: IntegrationsScimIdpIdGetResponseUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** The connection prefix used for the SCIM provider */
	prefix: string;
	/** Name of the SCIM identity provider */
	provider: string;
	/** SCIM API token (full on creation, masked otherwise) */
	auth_token: string;
	/** Timestamp of when the integration was last synced */
	last_synced_at: string;
}
export const IntegrationsScimIdpIdGetResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: IntegrationsScimIdpIdGetResponseGroupPrefixesList,
		user_group_prefixes: IntegrationsScimIdpIdGetResponseUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		prefix: S.String,
		provider: S.String,
		auth_token: S.String,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "IntegrationsScimIdpIdGetResponse" }) as any as S.Schema<IntegrationsScimIdpIdGetResponse>;

export interface IntegrationsScimIdpIdLogsGetRequest {
	/** The unique identifier of the SCIM IDP integration. */
	id: number;
}
export const IntegrationsScimIdpIdLogsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/scim-idp/{id}/logs", code: 200 })),
).annotate({
	identifier: "IntegrationsScimIdpIdLogsGetRequest",
}) as any as S.Schema<IntegrationsScimIdpIdLogsGetRequest>;

/** Represents a synchronization log entry for an integration */
export interface IdpIntegrationSyncLog {
	/** The unique identifier for the sync log */
	id: number;
	/** The log level */
	level: string;
	/** Timestamp of when the log was created */
	timestamp: string;
	/** Log message */
	message: string;
}
export const IdpIntegrationSyncLog = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number,
		level: S.String,
		timestamp: S.String,
		message: S.String,
	}),
).annotate({ identifier: "IdpIntegrationSyncLog" }) as any as S.Schema<IdpIntegrationSyncLog>;

export type IntegrationsScimIdpIdLogsGetResponseBodyList = ReadonlyArray<IdpIntegrationSyncLog>;
export const IntegrationsScimIdpIdLogsGetResponseBodyList = /*@__PURE__*/ S.Array(
	IdpIntegrationSyncLog,
) as any as S.Schema<IntegrationsScimIdpIdLogsGetResponseBodyList>;

export type IntegrationsScimIdpIdLogsGetResponse = IntegrationsScimIdpIdLogsGetResponseBodyList;
export const IntegrationsScimIdpIdLogsGetResponse = /*@__PURE__*/ S.suspend(() =>
	IntegrationsScimIdpIdLogsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsScimIdpIdLogsGetResponse",
}) as any as S.Schema<IntegrationsScimIdpIdLogsGetResponse>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsScimIdpIdPutRequestGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpIdPutRequestGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpIdPutRequestGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsScimIdpIdPutRequestUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpIdPutRequestUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpIdPutRequestUserGroupPrefixesList>;

export interface IntegrationsScimIdpIdPutRequest {
	/** The unique identifier of the SCIM IDP integration. */
	id: number;
	/** Whether the integration is enabled */
	enabled?: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes?: IntegrationsScimIdpIdPutRequestGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes?: IntegrationsScimIdpIdPutRequestUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The connection prefix used for the SCIM provider */
	prefix?: string;
}
export const IntegrationsScimIdpIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
		enabled: S.optional(S.Boolean),
		group_prefixes: S.optional(IntegrationsScimIdpIdPutRequestGroupPrefixesList),
		user_group_prefixes: S.optional(IntegrationsScimIdpIdPutRequestUserGroupPrefixesList),
		connector_id: S.optional(S.String),
		prefix: S.optional(S.String),
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/scim-idp/{id}", code: 200 })),
).annotate({ identifier: "IntegrationsScimIdpIdPutRequest" }) as any as S.Schema<IntegrationsScimIdpIdPutRequest>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsScimIdpIdPutResponseGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpIdPutResponseGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpIdPutResponseGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsScimIdpIdPutResponseUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpIdPutResponseUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpIdPutResponseUserGroupPrefixesList>;

export interface IntegrationsScimIdpIdPutResponse {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: IntegrationsScimIdpIdPutResponseGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: IntegrationsScimIdpIdPutResponseUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** The connection prefix used for the SCIM provider */
	prefix: string;
	/** Name of the SCIM identity provider */
	provider: string;
	/** SCIM API token (full on creation, masked otherwise) */
	auth_token: string;
	/** Timestamp of when the integration was last synced */
	last_synced_at: string;
}
export const IntegrationsScimIdpIdPutResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: IntegrationsScimIdpIdPutResponseGroupPrefixesList,
		user_group_prefixes: IntegrationsScimIdpIdPutResponseUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		prefix: S.String,
		provider: S.String,
		auth_token: S.String,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "IntegrationsScimIdpIdPutResponse" }) as any as S.Schema<IntegrationsScimIdpIdPutResponse>;

export interface IntegrationsScimIdpIdTokenPostRequest {
	/** The unique identifier of the SCIM IDP integration. */
	id: number;
}
export const IntegrationsScimIdpIdTokenPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/scim-idp/{id}/token", code: 200 })),
).annotate({
	identifier: "IntegrationsScimIdpIdTokenPostRequest",
}) as any as S.Schema<IntegrationsScimIdpIdTokenPostRequest>;

/** Response containing the regenerated SCIM token */
export interface ScimTokenResponse {
	/** The newly generated SCIM API token */
	auth_token: string;
}
export const ScimTokenResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		auth_token: S.String,
	}),
).annotate({ identifier: "ScimTokenResponse" }) as any as S.Schema<ScimTokenResponse>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsScimIdpPostRequestGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpPostRequestGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpPostRequestGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsScimIdpPostRequestUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpPostRequestUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpPostRequestUserGroupPrefixesList>;

export interface IntegrationsScimIdpPostRequest {
	/** List of start_with string patterns for groups to sync */
	group_prefixes?: IntegrationsScimIdpPostRequestGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes?: IntegrationsScimIdpPostRequestUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The connection prefix used for the SCIM provider */
	prefix: string;
	/** Name of the SCIM identity provider */
	provider: string;
}
export const IntegrationsScimIdpPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		group_prefixes: S.optional(IntegrationsScimIdpPostRequestGroupPrefixesList),
		user_group_prefixes: S.optional(IntegrationsScimIdpPostRequestUserGroupPrefixesList),
		connector_id: S.optional(S.String),
		prefix: S.String,
		provider: S.String,
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/scim-idp", code: 200 })),
).annotate({ identifier: "IntegrationsScimIdpPostRequest" }) as any as S.Schema<IntegrationsScimIdpPostRequest>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsScimIdpPostResponseGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpPostResponseGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpPostResponseGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsScimIdpPostResponseUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsScimIdpPostResponseUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsScimIdpPostResponseUserGroupPrefixesList>;

export interface IntegrationsScimIdpPostResponse {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: IntegrationsScimIdpPostResponseGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: IntegrationsScimIdpPostResponseUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** The connection prefix used for the SCIM provider */
	prefix: string;
	/** Name of the SCIM identity provider */
	provider: string;
	/** SCIM API token (full on creation, masked otherwise) */
	auth_token: string;
	/** Timestamp of when the integration was last synced */
	last_synced_at: string;
}
export const IntegrationsScimIdpPostResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: IntegrationsScimIdpPostResponseGroupPrefixesList,
		user_group_prefixes: IntegrationsScimIdpPostResponseUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		prefix: S.String,
		provider: S.String,
		auth_token: S.String,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "IntegrationsScimIdpPostResponse" }) as any as S.Schema<IntegrationsScimIdpPostResponse>;

export type IntegrationsScimIdpGetError = NetbirdOpError;
/** Get All SCIM IDP Integrations Retrieves all SCIM IDP integrations for the authenticated account */
export const integrationsScimIdpGet: API.OperationMethod<
	IntegrationsScimIdpGetRequest,
	IntegrationsScimIdpGetResponse,
	IntegrationsScimIdpGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpGetRequest,
	output: IntegrationsScimIdpGetResponse,
	errors: [UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsScimIdpIdDeleteError = BadRequest | NotFound | NetbirdOpError;
/** Delete SCIM IDP Integration Deletes an SCIM IDP integration by ID. */
export const integrationsScimIdpIdDelete: API.OperationMethod<
	IntegrationsScimIdpIdDeleteRequest,
	IntegrationsScimIdpIdDeleteResponse,
	IntegrationsScimIdpIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpIdDeleteRequest,
	output: IntegrationsScimIdpIdDeleteResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsScimIdpIdGetError = BadRequest | NotFound | NetbirdOpError;
/** Get SCIM IDP Integration Retrieves an SCIM IDP integration by ID. */
export const integrationsScimIdpIdGet: API.OperationMethod<
	IntegrationsScimIdpIdGetRequest,
	IntegrationsScimIdpIdGetResponse,
	IntegrationsScimIdpIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpIdGetRequest,
	output: IntegrationsScimIdpIdGetResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsScimIdpIdLogsGetError = BadRequest | NotFound | NetbirdOpError;
/** Get SCIM Integration Sync Logs Retrieves synchronization logs for a SCIM IDP integration. */
export const integrationsScimIdpIdLogsGet: API.OperationMethod<
	IntegrationsScimIdpIdLogsGetRequest,
	IntegrationsScimIdpIdLogsGetResponse,
	IntegrationsScimIdpIdLogsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpIdLogsGetRequest,
	output: IntegrationsScimIdpIdLogsGetResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsScimIdpIdPutError = BadRequest | NotFound | NetbirdOpError;
/** Update SCIM IDP Integration Updates an existing SCIM IDP Integration. */
export const integrationsScimIdpIdPut: API.OperationMethod<
	IntegrationsScimIdpIdPutRequest,
	IntegrationsScimIdpIdPutResponse,
	IntegrationsScimIdpIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpIdPutRequest,
	output: IntegrationsScimIdpIdPutResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsScimIdpIdTokenPostError = BadRequest | NotFound | NetbirdOpError;
/** Regenerate SCIM Token Regenerates the SCIM API token for an SCIM IDP integration. */
export const integrationsScimIdpIdTokenPost: API.OperationMethod<
	IntegrationsScimIdpIdTokenPostRequest,
	ScimTokenResponse,
	IntegrationsScimIdpIdTokenPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpIdTokenPostRequest,
	output: ScimTokenResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsScimIdpPostError = BadRequest | NetbirdOpError;
/** Create SCIM IDP Integration Creates a new SCIM integration */
export const integrationsScimIdpPost: API.OperationMethod<
	IntegrationsScimIdpPostRequest,
	IntegrationsScimIdpPostResponse,
	IntegrationsScimIdpPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsScimIdpPostRequest,
	output: IntegrationsScimIdpPostResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
