import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class NotFound
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 404 }],
	) {}

export interface IntegrationsGoogleIdpGetRequest {}
export const IntegrationsGoogleIdpGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/google-idp", code: 200 })),
).annotate({ identifier: "IntegrationsGoogleIdpGetRequest" }) as any as S.Schema<IntegrationsGoogleIdpGetRequest>;

/** List of start_with string patterns for groups to sync */
export type GoogleIntegrationGroupPrefixesList = ReadonlyArray<string>;
export const GoogleIntegrationGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<GoogleIntegrationGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type GoogleIntegrationUserGroupPrefixesList = ReadonlyArray<string>;
export const GoogleIntegrationUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<GoogleIntegrationUserGroupPrefixesList>;

export interface GoogleIntegration {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: GoogleIntegrationGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: GoogleIntegrationUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** Customer ID from Google Workspace */
	customer_id: string;
	/** Sync interval in seconds */
	sync_interval: number;
	/** Timestamp of the last synchronization */
	last_synced_at: string;
}
export const GoogleIntegration = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: GoogleIntegrationGroupPrefixesList,
		user_group_prefixes: GoogleIntegrationUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		customer_id: S.String,
		sync_interval: S.Number,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "GoogleIntegration" }) as any as S.Schema<GoogleIntegration>;

export type IntegrationsGoogleIdpGetResponseBodyList = ReadonlyArray<GoogleIntegration>;
export const IntegrationsGoogleIdpGetResponseBodyList = /*@__PURE__*/ S.Array(
	GoogleIntegration,
) as any as S.Schema<IntegrationsGoogleIdpGetResponseBodyList>;

export type IntegrationsGoogleIdpGetResponse = IntegrationsGoogleIdpGetResponseBodyList;
export const IntegrationsGoogleIdpGetResponse = /*@__PURE__*/ S.suspend(() =>
	IntegrationsGoogleIdpGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "IntegrationsGoogleIdpGetResponse" }) as any as S.Schema<IntegrationsGoogleIdpGetResponse>;

export interface IntegrationsGoogleIdpIdDeleteRequest {
	/** The unique identifier of the Google IDP integration. */
	id: number;
}
export const IntegrationsGoogleIdpIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/integrations/google-idp/{id}", code: 200 })),
).annotate({
	identifier: "IntegrationsGoogleIdpIdDeleteRequest",
}) as any as S.Schema<IntegrationsGoogleIdpIdDeleteRequest>;

export type IntegrationsGoogleIdpIdDeleteResponse = unknown;
export const IntegrationsGoogleIdpIdDeleteResponse = /*@__PURE__*/ S.suspend(() =>
	S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsGoogleIdpIdDeleteResponse",
}) as any as S.Schema<IntegrationsGoogleIdpIdDeleteResponse>;

export interface IntegrationsGoogleIdpIdGetRequest {
	/** The unique identifier of the Google IDP integration. */
	id: number;
}
export const IntegrationsGoogleIdpIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/google-idp/{id}", code: 200 })),
).annotate({ identifier: "IntegrationsGoogleIdpIdGetRequest" }) as any as S.Schema<IntegrationsGoogleIdpIdGetRequest>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsGoogleIdpIdGetResponseGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpIdGetResponseGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpIdGetResponseGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsGoogleIdpIdGetResponseUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpIdGetResponseUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpIdGetResponseUserGroupPrefixesList>;

export interface IntegrationsGoogleIdpIdGetResponse {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: IntegrationsGoogleIdpIdGetResponseGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: IntegrationsGoogleIdpIdGetResponseUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** Customer ID from Google Workspace */
	customer_id: string;
	/** Sync interval in seconds */
	sync_interval: number;
	/** Timestamp of the last synchronization */
	last_synced_at: string;
}
export const IntegrationsGoogleIdpIdGetResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: IntegrationsGoogleIdpIdGetResponseGroupPrefixesList,
		user_group_prefixes: IntegrationsGoogleIdpIdGetResponseUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		customer_id: S.String,
		sync_interval: S.Number,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "IntegrationsGoogleIdpIdGetResponse" }) as any as S.Schema<IntegrationsGoogleIdpIdGetResponse>;

export interface IntegrationsGoogleIdpIdLogsGetRequest {
	/** The unique identifier of the Google IDP integration. */
	id: number;
}
export const IntegrationsGoogleIdpIdLogsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/google-idp/{id}/logs", code: 200 })),
).annotate({
	identifier: "IntegrationsGoogleIdpIdLogsGetRequest",
}) as any as S.Schema<IntegrationsGoogleIdpIdLogsGetRequest>;

/** Represents a synchronization log entry for an integration */
export interface IdpIntegrationSyncLog {
	/** The unique identifier for the sync log */
	id: number;
	/** The log level */
	level: string;
	/** Timestamp of when the log was created */
	timestamp: string;
	/** Log message */
	message: string;
}
export const IdpIntegrationSyncLog = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number,
		level: S.String,
		timestamp: S.String,
		message: S.String,
	}),
).annotate({ identifier: "IdpIntegrationSyncLog" }) as any as S.Schema<IdpIntegrationSyncLog>;

export type IntegrationsGoogleIdpIdLogsGetResponseBodyList = ReadonlyArray<IdpIntegrationSyncLog>;
export const IntegrationsGoogleIdpIdLogsGetResponseBodyList = /*@__PURE__*/ S.Array(
	IdpIntegrationSyncLog,
) as any as S.Schema<IntegrationsGoogleIdpIdLogsGetResponseBodyList>;

export type IntegrationsGoogleIdpIdLogsGetResponse = IntegrationsGoogleIdpIdLogsGetResponseBodyList;
export const IntegrationsGoogleIdpIdLogsGetResponse = /*@__PURE__*/ S.suspend(() =>
	IntegrationsGoogleIdpIdLogsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsGoogleIdpIdLogsGetResponse",
}) as any as S.Schema<IntegrationsGoogleIdpIdLogsGetResponse>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsGoogleIdpIdPutRequestGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpIdPutRequestGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpIdPutRequestGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsGoogleIdpIdPutRequestUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpIdPutRequestUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpIdPutRequestUserGroupPrefixesList>;

export interface IntegrationsGoogleIdpIdPutRequest {
	/** The unique identifier of the Google IDP integration. */
	id: number;
	/** Whether the integration is enabled */
	enabled?: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes?: IntegrationsGoogleIdpIdPutRequestGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes?: IntegrationsGoogleIdpIdPutRequestUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** Base64-encoded Google service account key */
	service_account_key?: string;
	/** Customer ID from Google Workspace Account Settings */
	customer_id?: string;
	/** Sync interval in seconds (minimum 300) */
	sync_interval?: number;
}
export const IntegrationsGoogleIdpIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
		enabled: S.optional(S.Boolean),
		group_prefixes: S.optional(IntegrationsGoogleIdpIdPutRequestGroupPrefixesList),
		user_group_prefixes: S.optional(IntegrationsGoogleIdpIdPutRequestUserGroupPrefixesList),
		connector_id: S.optional(S.String),
		service_account_key: S.optional(S.String),
		customer_id: S.optional(S.String),
		sync_interval: S.optional(S.Number),
	}).pipe(T.Http({ method: "PUT", uri: "/api/integrations/google-idp/{id}", code: 200 })),
).annotate({ identifier: "IntegrationsGoogleIdpIdPutRequest" }) as any as S.Schema<IntegrationsGoogleIdpIdPutRequest>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsGoogleIdpIdPutResponseGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpIdPutResponseGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpIdPutResponseGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsGoogleIdpIdPutResponseUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpIdPutResponseUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpIdPutResponseUserGroupPrefixesList>;

export interface IntegrationsGoogleIdpIdPutResponse {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: IntegrationsGoogleIdpIdPutResponseGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: IntegrationsGoogleIdpIdPutResponseUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** Customer ID from Google Workspace */
	customer_id: string;
	/** Sync interval in seconds */
	sync_interval: number;
	/** Timestamp of the last synchronization */
	last_synced_at: string;
}
export const IntegrationsGoogleIdpIdPutResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: IntegrationsGoogleIdpIdPutResponseGroupPrefixesList,
		user_group_prefixes: IntegrationsGoogleIdpIdPutResponseUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		customer_id: S.String,
		sync_interval: S.Number,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "IntegrationsGoogleIdpIdPutResponse" }) as any as S.Schema<IntegrationsGoogleIdpIdPutResponse>;

export interface IntegrationsGoogleIdpIdSyncPostRequest {
	/** The unique identifier of the Google IDP integration. */
	id: number;
}
export const IntegrationsGoogleIdpIdSyncPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.Number.pipe(T.Label()),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/google-idp/{id}/sync", code: 200 })),
).annotate({
	identifier: "IntegrationsGoogleIdpIdSyncPostRequest",
}) as any as S.Schema<IntegrationsGoogleIdpIdSyncPostRequest>;

/** Response for a manual sync trigger */
export interface SyncResult {
	result?: string;
}
export const SyncResult = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		result: S.optional(S.String),
	}),
).annotate({ identifier: "SyncResult" }) as any as S.Schema<SyncResult>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsGoogleIdpPostRequestGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpPostRequestGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpPostRequestGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsGoogleIdpPostRequestUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpPostRequestUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpPostRequestUserGroupPrefixesList>;

export interface IntegrationsGoogleIdpPostRequest {
	/** List of start_with string patterns for groups to sync */
	group_prefixes?: IntegrationsGoogleIdpPostRequestGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes?: IntegrationsGoogleIdpPostRequestUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** Base64-encoded Google service account key */
	service_account_key: string;
	/** Customer ID from Google Workspace Account Settings */
	customer_id: string;
	/** Sync interval in seconds (minimum 300). Defaults to 300 if not specified. */
	sync_interval?: number;
}
export const IntegrationsGoogleIdpPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		group_prefixes: S.optional(IntegrationsGoogleIdpPostRequestGroupPrefixesList),
		user_group_prefixes: S.optional(IntegrationsGoogleIdpPostRequestUserGroupPrefixesList),
		connector_id: S.optional(S.String),
		service_account_key: S.String,
		customer_id: S.String,
		sync_interval: S.optional(S.Number),
	}).pipe(T.Http({ method: "POST", uri: "/api/integrations/google-idp", code: 200 })),
).annotate({ identifier: "IntegrationsGoogleIdpPostRequest" }) as any as S.Schema<IntegrationsGoogleIdpPostRequest>;

/** List of start_with string patterns for groups to sync */
export type IntegrationsGoogleIdpPostResponseGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpPostResponseGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpPostResponseGroupPrefixesList>;

/** List of start_with string patterns for groups which users to sync */
export type IntegrationsGoogleIdpPostResponseUserGroupPrefixesList = ReadonlyArray<string>;
export const IntegrationsGoogleIdpPostResponseUserGroupPrefixesList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<IntegrationsGoogleIdpPostResponseUserGroupPrefixesList>;

export interface IntegrationsGoogleIdpPostResponse {
	/** Whether the integration is enabled */
	enabled: boolean;
	/** List of start_with string patterns for groups to sync */
	group_prefixes: IntegrationsGoogleIdpPostResponseGroupPrefixesList;
	/** List of start_with string patterns for groups which users to sync */
	user_group_prefixes: IntegrationsGoogleIdpPostResponseUserGroupPrefixesList;
	/** DEX connector ID for embedded IDP setups */
	connector_id?: string;
	/** The unique identifier for the integration */
	id: number;
	/** Customer ID from Google Workspace */
	customer_id: string;
	/** Sync interval in seconds */
	sync_interval: number;
	/** Timestamp of the last synchronization */
	last_synced_at: string;
}
export const IntegrationsGoogleIdpPostResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		enabled: S.Boolean,
		group_prefixes: IntegrationsGoogleIdpPostResponseGroupPrefixesList,
		user_group_prefixes: IntegrationsGoogleIdpPostResponseUserGroupPrefixesList,
		connector_id: S.optional(S.String),
		id: S.Number,
		customer_id: S.String,
		sync_interval: S.Number,
		last_synced_at: S.String,
	}),
).annotate({ identifier: "IntegrationsGoogleIdpPostResponse" }) as any as S.Schema<IntegrationsGoogleIdpPostResponse>;

export type IntegrationsGoogleIdpGetError = NetbirdOpError;
/** Get All Google IDP Integrations Retrieves all Google Workspace IDP integrations for the authenticated account */
export const integrationsGoogleIdpGet: API.OperationMethod<
	IntegrationsGoogleIdpGetRequest,
	IntegrationsGoogleIdpGetResponse,
	IntegrationsGoogleIdpGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpGetRequest,
	output: IntegrationsGoogleIdpGetResponse,
	errors: [UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsGoogleIdpIdDeleteError = BadRequest | NotFound | NetbirdOpError;
/** Delete Google IDP Integration Deletes a Google IDP integration by ID. */
export const integrationsGoogleIdpIdDelete: API.OperationMethod<
	IntegrationsGoogleIdpIdDeleteRequest,
	IntegrationsGoogleIdpIdDeleteResponse,
	IntegrationsGoogleIdpIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpIdDeleteRequest,
	output: IntegrationsGoogleIdpIdDeleteResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsGoogleIdpIdGetError = BadRequest | NotFound | NetbirdOpError;
/** Get Google IDP Integration Retrieves a Google IDP integration by ID. */
export const integrationsGoogleIdpIdGet: API.OperationMethod<
	IntegrationsGoogleIdpIdGetRequest,
	IntegrationsGoogleIdpIdGetResponse,
	IntegrationsGoogleIdpIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpIdGetRequest,
	output: IntegrationsGoogleIdpIdGetResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsGoogleIdpIdLogsGetError = BadRequest | NotFound | NetbirdOpError;
/** Get Google Integration Sync Logs Retrieves synchronization logs for a Google IDP integration. */
export const integrationsGoogleIdpIdLogsGet: API.OperationMethod<
	IntegrationsGoogleIdpIdLogsGetRequest,
	IntegrationsGoogleIdpIdLogsGetResponse,
	IntegrationsGoogleIdpIdLogsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpIdLogsGetRequest,
	output: IntegrationsGoogleIdpIdLogsGetResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsGoogleIdpIdPutError = BadRequest | NotFound | NetbirdOpError;
/** Update Google IDP Integration Updates an existing Google Workspace IDP integration. */
export const integrationsGoogleIdpIdPut: API.OperationMethod<
	IntegrationsGoogleIdpIdPutRequest,
	IntegrationsGoogleIdpIdPutResponse,
	IntegrationsGoogleIdpIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpIdPutRequest,
	output: IntegrationsGoogleIdpIdPutResponse,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsGoogleIdpIdSyncPostError = BadRequest | NotFound | NetbirdOpError;
/** Sync Google IDP Integration Triggers a manual synchronization for a Google IDP integration. */
export const integrationsGoogleIdpIdSyncPost: API.OperationMethod<
	IntegrationsGoogleIdpIdSyncPostRequest,
	SyncResult,
	IntegrationsGoogleIdpIdSyncPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpIdSyncPostRequest,
	output: SyncResult,
	errors: [BadRequest, NotFound, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsGoogleIdpPostError = BadRequest | NetbirdOpError;
/** Create Google IDP Integration Creates a new Google Workspace IDP integration */
export const integrationsGoogleIdpPost: API.OperationMethod<
	IntegrationsGoogleIdpPostRequest,
	IntegrationsGoogleIdpPostResponse,
	IntegrationsGoogleIdpPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsGoogleIdpPostRequest,
	output: IntegrationsGoogleIdpPostResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
