import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export interface IngressPeersGetRequest {}
export const IngressPeersGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/ingress/peers", code: 200 })),
).annotate({ identifier: "IngressPeersGetRequest" }) as any as S.Schema<IngressPeersGetRequest>;

export interface AvailablePorts {
	/** Number of available TCP ports left on the ingress peer */
	tcp: number;
	/** Number of available UDP ports left on the ingress peer */
	udp: number;
}
export const AvailablePorts = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		tcp: S.Number,
		udp: S.Number,
	}),
).annotate({ identifier: "AvailablePorts" }) as any as S.Schema<AvailablePorts>;

export interface IngressPeer {
	/** ID of the ingress peer */
	id: string;
	/** ID of the peer that is used as an ingress peer */
	peer_id: string;
	/** Ingress IP address of the ingress peer where the traffic arrives */
	ingress_ip: string;
	available_ports: AvailablePorts;
	/** Indicates if an ingress peer is enabled */
	enabled: boolean;
	/** Indicates if an ingress peer is connected to the management server */
	connected: boolean;
	/** Indicates if an ingress peer can be used as a fallback if no ingress peer can be found in the region of the forwarded peer */
	fallback: boolean;
	/** Region of the ingress peer */
	region: string;
}
export const IngressPeer = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		peer_id: S.String,
		ingress_ip: S.String,
		available_ports: AvailablePorts,
		enabled: S.Boolean,
		connected: S.Boolean,
		fallback: S.Boolean,
		region: S.String,
	}),
).annotate({ identifier: "IngressPeer" }) as any as S.Schema<IngressPeer>;

export type IngressPeersGetResponseBodyList = ReadonlyArray<IngressPeer>;
export const IngressPeersGetResponseBodyList = /*@__PURE__*/ S.Array(
	IngressPeer,
) as any as S.Schema<IngressPeersGetResponseBodyList>;

export type IngressPeersGetResponse = IngressPeersGetResponseBodyList;
export const IngressPeersGetResponse = /*@__PURE__*/ S.suspend(() =>
	IngressPeersGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "IngressPeersGetResponse" }) as any as S.Schema<IngressPeersGetResponse>;

export interface IngressPeersIngressPeerIdDeleteRequest {
	/** The unique identifier of an ingress peer */
	ingressPeerId: string;
}
export const IngressPeersIngressPeerIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ingressPeerId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/ingress/peers/{ingressPeerId}", code: 200 })),
).annotate({
	identifier: "IngressPeersIngressPeerIdDeleteRequest",
}) as any as S.Schema<IngressPeersIngressPeerIdDeleteRequest>;

export interface IngressPeersIngressPeerIdDeleteResponse {}
export const IngressPeersIngressPeerIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IngressPeersIngressPeerIdDeleteResponse",
}) as any as S.Schema<IngressPeersIngressPeerIdDeleteResponse>;

export interface IngressPeersIngressPeerIdGetRequest {
	/** The unique identifier of an ingress peer */
	ingressPeerId: string;
}
export const IngressPeersIngressPeerIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ingressPeerId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/ingress/peers/{ingressPeerId}", code: 200 })),
).annotate({
	identifier: "IngressPeersIngressPeerIdGetRequest",
}) as any as S.Schema<IngressPeersIngressPeerIdGetRequest>;

export interface IngressPeersIngressPeerIdPutRequest {
	/** The unique identifier of an ingress peer */
	ingressPeerId: string;
	/** Defines if an ingress peer is enabled */
	enabled: boolean;
	/** Defines if an ingress peer can be used as a fallback if no ingress peer can be found in the region of the forwarded peer */
	fallback: boolean;
}
export const IngressPeersIngressPeerIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		ingressPeerId: S.String.pipe(T.Label()),
		enabled: S.Boolean,
		fallback: S.Boolean,
	}).pipe(T.Http({ method: "PUT", uri: "/api/ingress/peers/{ingressPeerId}", code: 200 })),
).annotate({
	identifier: "IngressPeersIngressPeerIdPutRequest",
}) as any as S.Schema<IngressPeersIngressPeerIdPutRequest>;

export interface IngressPeersPostRequest {
	/** ID of the peer that is used as an ingress peer */
	peer_id: string;
	/** Defines if an ingress peer is enabled */
	enabled: boolean;
	/** Defines if an ingress peer can be used as a fallback if no ingress peer can be found in the region of the forwarded peer */
	fallback: boolean;
}
export const IngressPeersPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peer_id: S.String,
		enabled: S.Boolean,
		fallback: S.Boolean,
	}).pipe(T.Http({ method: "POST", uri: "/api/ingress/peers", code: 200 })),
).annotate({ identifier: "IngressPeersPostRequest" }) as any as S.Schema<IngressPeersPostRequest>;

export interface PeersPeerIdIngressPortsAllocationIdDeleteRequest {
	/** The unique identifier of a peer */
	peerId: string;
	/** The unique identifier of an ingress port allocation */
	allocationId: string;
}
export const PeersPeerIdIngressPortsAllocationIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		allocationId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/peers/{peerId}/ingress/ports/{allocationId}", code: 200 })),
).annotate({
	identifier: "PeersPeerIdIngressPortsAllocationIdDeleteRequest",
}) as any as S.Schema<PeersPeerIdIngressPortsAllocationIdDeleteRequest>;

export interface PeersPeerIdIngressPortsAllocationIdDeleteResponse {}
export const PeersPeerIdIngressPortsAllocationIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "PeersPeerIdIngressPortsAllocationIdDeleteResponse",
}) as any as S.Schema<PeersPeerIdIngressPortsAllocationIdDeleteResponse>;

export interface PeersPeerIdIngressPortsAllocationIdGetRequest {
	/** The unique identifier of a peer */
	peerId: string;
	/** The unique identifier of an ingress port allocation */
	allocationId: string;
}
export const PeersPeerIdIngressPortsAllocationIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		allocationId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/peers/{peerId}/ingress/ports/{allocationId}", code: 200 })),
).annotate({
	identifier: "PeersPeerIdIngressPortsAllocationIdGetRequest",
}) as any as S.Schema<PeersPeerIdIngressPortsAllocationIdGetRequest>;

/** Protocol accepted by the ports */
export type IngressPortAllocationPortMappingProtocol = "tcp" | "udp" | "tcp/udp";
export const IngressPortAllocationPortMappingProtocol = /*@__PURE__*/ S.String;

export interface IngressPortAllocationPortMapping {
	/** The starting port of the translated range of forwarded ports */
	translated_start: number;
	/** The ending port of the translated range of forwarded ports */
	translated_end: number;
	/** The starting port of the range of ingress ports mapped to the forwarded ports */
	ingress_start: number;
	/** The ending port of the range of ingress ports mapped to the forwarded ports */
	ingress_end: number;
	/** Protocol accepted by the ports */
	protocol: IngressPortAllocationPortMappingProtocol;
}
export const IngressPortAllocationPortMapping = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		translated_start: S.Number,
		translated_end: S.Number,
		ingress_start: S.Number,
		ingress_end: S.Number,
		protocol: IngressPortAllocationPortMappingProtocol,
	}),
).annotate({ identifier: "IngressPortAllocationPortMapping" }) as any as S.Schema<IngressPortAllocationPortMapping>;

/** List of port ranges that are allowed to be used by the ingress peer */
export type IngressPortAllocationPortRangeMappingsList = ReadonlyArray<IngressPortAllocationPortMapping>;
export const IngressPortAllocationPortRangeMappingsList = /*@__PURE__*/ S.Array(
	IngressPortAllocationPortMapping,
) as any as S.Schema<IngressPortAllocationPortRangeMappingsList>;

export interface IngressPortAllocation {
	/** ID of the ingress port allocation */
	id: string;
	/** Name of the ingress port allocation */
	name: string;
	/** ID of the ingress peer that forwards the ports */
	ingress_peer_id: string;
	/** Region of the ingress peer */
	region: string;
	/** Indicates if an ingress port allocation is enabled */
	enabled: boolean;
	/** Ingress IP address of the ingress peer where the traffic arrives */
	ingress_ip: string;
	/** List of port ranges that are allowed to be used by the ingress peer */
	port_range_mappings: IngressPortAllocationPortRangeMappingsList;
}
export const IngressPortAllocation = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		ingress_peer_id: S.String,
		region: S.String,
		enabled: S.Boolean,
		ingress_ip: S.String,
		port_range_mappings: IngressPortAllocationPortRangeMappingsList,
	}),
).annotate({ identifier: "IngressPortAllocation" }) as any as S.Schema<IngressPortAllocation>;

/** The protocol accepted by the port range */
export type IngressPortAllocationRequestPortRangeProtocol = "tcp" | "udp" | "tcp/udp";
export const IngressPortAllocationRequestPortRangeProtocol = /*@__PURE__*/ S.String;

export interface IngressPortAllocationRequestPortRange {
	/** The starting port of the range of forwarded ports */
	start: number;
	/** The ending port of the range of forwarded ports */
	end: number;
	/** The protocol accepted by the port range */
	protocol: IngressPortAllocationRequestPortRangeProtocol;
}
export const IngressPortAllocationRequestPortRange = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		start: S.Number,
		end: S.Number,
		protocol: IngressPortAllocationRequestPortRangeProtocol,
	}),
).annotate({
	identifier: "IngressPortAllocationRequestPortRange",
}) as any as S.Schema<IngressPortAllocationRequestPortRange>;

/** List of port ranges that are forwarded by the ingress peer */
export type PeersPeerIdIngressPortsAllocationIdPutRequestPortRangesList =
	ReadonlyArray<IngressPortAllocationRequestPortRange>;
export const PeersPeerIdIngressPortsAllocationIdPutRequestPortRangesList = /*@__PURE__*/ S.Array(
	IngressPortAllocationRequestPortRange,
) as any as S.Schema<PeersPeerIdIngressPortsAllocationIdPutRequestPortRangesList>;

/** The protocol accepted by the port */
export type IngressPortAllocationRequestDirectPortProtocol = "tcp" | "udp" | "tcp/udp";
export const IngressPortAllocationRequestDirectPortProtocol = /*@__PURE__*/ S.String;

export interface IngressPortAllocationRequestDirectPort {
	/** The number of ports to be forwarded */
	count: number;
	/** The protocol accepted by the port */
	protocol: IngressPortAllocationRequestDirectPortProtocol;
}
export const IngressPortAllocationRequestDirectPort = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		count: S.Number,
		protocol: IngressPortAllocationRequestDirectPortProtocol,
	}),
).annotate({
	identifier: "IngressPortAllocationRequestDirectPort",
}) as any as S.Schema<IngressPortAllocationRequestDirectPort>;

export interface PeersPeerIdIngressPortsAllocationIdPutRequest {
	/** The unique identifier of a peer */
	peerId: string;
	/** The unique identifier of an ingress port allocation */
	allocationId: string;
	/** Name of the ingress port allocation */
	name: string;
	/** Indicates if an ingress port allocation is enabled */
	enabled: boolean;
	/** List of port ranges that are forwarded by the ingress peer */
	port_ranges?: PeersPeerIdIngressPortsAllocationIdPutRequestPortRangesList;
	/** Direct port allocation */
	direct_port?: IngressPortAllocationRequestDirectPort;
}
export const PeersPeerIdIngressPortsAllocationIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		allocationId: S.String.pipe(T.Label()),
		name: S.String,
		enabled: S.Boolean,
		port_ranges: S.optional(PeersPeerIdIngressPortsAllocationIdPutRequestPortRangesList),
		direct_port: S.optional(IngressPortAllocationRequestDirectPort),
	}).pipe(T.Http({ method: "PUT", uri: "/api/peers/{peerId}/ingress/ports/{allocationId}", code: 200 })),
).annotate({
	identifier: "PeersPeerIdIngressPortsAllocationIdPutRequest",
}) as any as S.Schema<PeersPeerIdIngressPortsAllocationIdPutRequest>;

export interface PeersPeerIdIngressPortsGetRequest {
	/** The unique identifier of a peer */
	peerId: string;
	/** Filters ingress port allocations by name */
	name?: string;
}
export const PeersPeerIdIngressPortsGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		name: S.optional(S.String.pipe(T.Query())),
	}).pipe(T.Http({ method: "GET", uri: "/api/peers/{peerId}/ingress/ports", code: 200 })),
).annotate({ identifier: "PeersPeerIdIngressPortsGetRequest" }) as any as S.Schema<PeersPeerIdIngressPortsGetRequest>;

export type PeersPeerIdIngressPortsGetResponseBodyList = ReadonlyArray<IngressPortAllocation>;
export const PeersPeerIdIngressPortsGetResponseBodyList = /*@__PURE__*/ S.Array(
	IngressPortAllocation,
) as any as S.Schema<PeersPeerIdIngressPortsGetResponseBodyList>;

export type PeersPeerIdIngressPortsGetResponse = PeersPeerIdIngressPortsGetResponseBodyList;
export const PeersPeerIdIngressPortsGetResponse = /*@__PURE__*/ S.suspend(() =>
	PeersPeerIdIngressPortsGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "PeersPeerIdIngressPortsGetResponse" }) as any as S.Schema<PeersPeerIdIngressPortsGetResponse>;

/** List of port ranges that are forwarded by the ingress peer */
export type PeersPeerIdIngressPortsPostRequestPortRangesList = ReadonlyArray<IngressPortAllocationRequestPortRange>;
export const PeersPeerIdIngressPortsPostRequestPortRangesList = /*@__PURE__*/ S.Array(
	IngressPortAllocationRequestPortRange,
) as any as S.Schema<PeersPeerIdIngressPortsPostRequestPortRangesList>;

export interface PeersPeerIdIngressPortsPostRequest {
	/** The unique identifier of a peer */
	peerId: string;
	/** Name of the ingress port allocation */
	name: string;
	/** Indicates if an ingress port allocation is enabled */
	enabled: boolean;
	/** List of port ranges that are forwarded by the ingress peer */
	port_ranges?: PeersPeerIdIngressPortsPostRequestPortRangesList;
	/** Direct port allocation */
	direct_port?: IngressPortAllocationRequestDirectPort;
}
export const PeersPeerIdIngressPortsPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		peerId: S.String.pipe(T.Label()),
		name: S.String,
		enabled: S.Boolean,
		port_ranges: S.optional(PeersPeerIdIngressPortsPostRequestPortRangesList),
		direct_port: S.optional(IngressPortAllocationRequestDirectPort),
	}).pipe(T.Http({ method: "POST", uri: "/api/peers/{peerId}/ingress/ports", code: 200 })),
).annotate({ identifier: "PeersPeerIdIngressPortsPostRequest" }) as any as S.Schema<PeersPeerIdIngressPortsPostRequest>;

export type IngressPeersGetError = BadRequest | Forbidden | NetbirdOpError;
/** List all Ingress Peers Returns a list of all ingress peers */
export const ingressPeersGet: API.OperationMethod<
	IngressPeersGetRequest,
	IngressPeersGetResponse,
	IngressPeersGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IngressPeersGetRequest,
	output: IngressPeersGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IngressPeersIngressPeerIdDeleteError = BadRequest | Forbidden | NetbirdOpError;
/** Delete a Ingress Peer Delete an ingress peer */
export const ingressPeersIngressPeerIdDelete: API.OperationMethod<
	IngressPeersIngressPeerIdDeleteRequest,
	IngressPeersIngressPeerIdDeleteResponse,
	IngressPeersIngressPeerIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IngressPeersIngressPeerIdDeleteRequest,
	output: IngressPeersIngressPeerIdDeleteResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IngressPeersIngressPeerIdGetError = BadRequest | Forbidden | NetbirdOpError;
/** Retrieve a Ingress Peer Get information about an ingress peer */
export const ingressPeersIngressPeerIdGet: API.OperationMethod<
	IngressPeersIngressPeerIdGetRequest,
	IngressPeer,
	IngressPeersIngressPeerIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IngressPeersIngressPeerIdGetRequest,
	output: IngressPeer,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IngressPeersIngressPeerIdPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update a Ingress Peer Update information about an ingress peer */
export const ingressPeersIngressPeerIdPut: API.OperationMethod<
	IngressPeersIngressPeerIdPutRequest,
	IngressPeer,
	IngressPeersIngressPeerIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IngressPeersIngressPeerIdPutRequest,
	output: IngressPeer,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IngressPeersPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create a Ingress Peer Creates a new ingress peer */
export const ingressPeersPost: API.OperationMethod<
	IngressPeersPostRequest,
	IngressPeer,
	IngressPeersPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IngressPeersPostRequest,
	output: IngressPeer,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdIngressPortsAllocationIdDeleteError = BadRequest | Forbidden | NetbirdOpError;
/** Delete a Port Allocation Delete an ingress port allocation */
export const peersPeerIdIngressPortsAllocationIdDelete: API.OperationMethod<
	PeersPeerIdIngressPortsAllocationIdDeleteRequest,
	PeersPeerIdIngressPortsAllocationIdDeleteResponse,
	PeersPeerIdIngressPortsAllocationIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdIngressPortsAllocationIdDeleteRequest,
	output: PeersPeerIdIngressPortsAllocationIdDeleteResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdIngressPortsAllocationIdGetError = BadRequest | Forbidden | NetbirdOpError;
/** Retrieve a Port Allocation Get information about an ingress port allocation */
export const peersPeerIdIngressPortsAllocationIdGet: API.OperationMethod<
	PeersPeerIdIngressPortsAllocationIdGetRequest,
	IngressPortAllocation,
	PeersPeerIdIngressPortsAllocationIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdIngressPortsAllocationIdGetRequest,
	output: IngressPortAllocation,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdIngressPortsAllocationIdPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update a Port Allocation Update information about an ingress port allocation */
export const peersPeerIdIngressPortsAllocationIdPut: API.OperationMethod<
	PeersPeerIdIngressPortsAllocationIdPutRequest,
	IngressPortAllocation,
	PeersPeerIdIngressPortsAllocationIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdIngressPortsAllocationIdPutRequest,
	output: IngressPortAllocation,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdIngressPortsGetError = BadRequest | Forbidden | NetbirdOpError;
/** List all Port Allocations Returns a list of all ingress port allocations for a peer */
export const peersPeerIdIngressPortsGet: API.OperationMethod<
	PeersPeerIdIngressPortsGetRequest,
	PeersPeerIdIngressPortsGetResponse,
	PeersPeerIdIngressPortsGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdIngressPortsGetRequest,
	output: PeersPeerIdIngressPortsGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type PeersPeerIdIngressPortsPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create a Port Allocation Creates a new ingress port allocation for a peer */
export const peersPeerIdIngressPortsPost: API.OperationMethod<
	PeersPeerIdIngressPortsPostRequest,
	IngressPortAllocation,
	PeersPeerIdIngressPortsPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: PeersPeerIdIngressPortsPostRequest,
	output: IngressPortAllocation,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
