import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export interface IntegrationsBillingInvoicesGetRequest {}
export const IntegrationsBillingInvoicesGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/integrations/billing/invoices", code: 200 })),
).annotate({
	identifier: "IntegrationsBillingInvoicesGetRequest",
}) as any as S.Schema<IntegrationsBillingInvoicesGetRequest>;

/** The invoice type */
export type InvoiceResponseType = "account" | "tenants";
export const InvoiceResponseType = /*@__PURE__*/ S.String;

export interface InvoiceResponse {
	/** The Stripe invoice id */
	id: string;
	/** The invoice type */
	type: InvoiceResponseType;
	/** The start date of the invoice period. */
	period_start: string;
	/** The end date of the invoice period. */
	period_end: string;
}
export const InvoiceResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		type: InvoiceResponseType,
		period_start: S.String,
		period_end: S.String,
	}),
).annotate({ identifier: "InvoiceResponse" }) as any as S.Schema<InvoiceResponse>;

export type IntegrationsBillingInvoicesGetResponseBodyList = ReadonlyArray<InvoiceResponse>;
export const IntegrationsBillingInvoicesGetResponseBodyList = /*@__PURE__*/ S.Array(
	InvoiceResponse,
) as any as S.Schema<IntegrationsBillingInvoicesGetResponseBodyList>;

export type IntegrationsBillingInvoicesGetResponse = IntegrationsBillingInvoicesGetResponseBodyList;
export const IntegrationsBillingInvoicesGetResponse = /*@__PURE__*/ S.suspend(() =>
	IntegrationsBillingInvoicesGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
	identifier: "IntegrationsBillingInvoicesGetResponse",
}) as any as S.Schema<IntegrationsBillingInvoicesGetResponse>;

export interface IntegrationsBillingInvoicesIdCsvGetRequest {
	/** The unique identifier of the invoice */
	id: string;
}
export const IntegrationsBillingInvoicesIdCsvGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/billing/invoices/{id}/csv", code: 200 })),
).annotate({
	identifier: "IntegrationsBillingInvoicesIdCsvGetRequest",
}) as any as S.Schema<IntegrationsBillingInvoicesIdCsvGetRequest>;

export interface IntegrationsBillingInvoicesIdCsvGetResponse {}
export const IntegrationsBillingInvoicesIdCsvGetResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "IntegrationsBillingInvoicesIdCsvGetResponse",
}) as any as S.Schema<IntegrationsBillingInvoicesIdCsvGetResponse>;

export interface IntegrationsBillingInvoicesIdPdfGetRequest {
	/** The unique identifier of the invoice */
	id: string;
}
export const IntegrationsBillingInvoicesIdPdfGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/billing/invoices/{id}/pdf", code: 200 })),
).annotate({
	identifier: "IntegrationsBillingInvoicesIdPdfGetRequest",
}) as any as S.Schema<IntegrationsBillingInvoicesIdPdfGetRequest>;

export interface InvoicePDFResponse {
	/** URL to redirect the user to invoice. */
	url: string;
}
export const InvoicePDFResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		url: S.String,
	}),
).annotate({ identifier: "InvoicePDFResponse" }) as any as S.Schema<InvoicePDFResponse>;

export type IntegrationsBillingInvoicesGetError = BadRequest | NetbirdOpError;
/** Get account's paid invoices */
export const integrationsBillingInvoicesGet: API.OperationMethod<
	IntegrationsBillingInvoicesGetRequest,
	IntegrationsBillingInvoicesGetResponse,
	IntegrationsBillingInvoicesGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsBillingInvoicesGetRequest,
	output: IntegrationsBillingInvoicesGetResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsBillingInvoicesIdCsvGetError = BadRequest | NetbirdOpError;
/** Get account invoice CSV. */
export const integrationsBillingInvoicesIdCsvGet: API.OperationMethod<
	IntegrationsBillingInvoicesIdCsvGetRequest,
	IntegrationsBillingInvoicesIdCsvGetResponse,
	IntegrationsBillingInvoicesIdCsvGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsBillingInvoicesIdCsvGetRequest,
	output: IntegrationsBillingInvoicesIdCsvGetResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type IntegrationsBillingInvoicesIdPdfGetError = BadRequest | NetbirdOpError;
/** Get account invoice URL to Stripe. */
export const integrationsBillingInvoicesIdPdfGet: API.OperationMethod<
	IntegrationsBillingInvoicesIdPdfGetRequest,
	InvoicePDFResponse,
	IntegrationsBillingInvoicesIdPdfGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsBillingInvoicesIdPdfGetRequest,
	output: InvoicePDFResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
