import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export interface IntegrationsBillingPortalGetRequest {
	/** The base URL for the redirect after accessing the portal. */
	baseURL: string;
}
export const IntegrationsBillingPortalGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		baseURL: S.String.pipe(T.Query()),
	}).pipe(T.Http({ method: "GET", uri: "/api/integrations/billing/portal", code: 200 })),
).annotate({
	identifier: "IntegrationsBillingPortalGetRequest",
}) as any as S.Schema<IntegrationsBillingPortalGetRequest>;

export interface PortalResponse {
	/** The unique identifier for the customer portal session. */
	session_id: string;
	/** URL to redirect the user to the customer portal. */
	url: string;
}
export const PortalResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		session_id: S.String,
		url: S.String,
	}),
).annotate({ identifier: "PortalResponse" }) as any as S.Schema<PortalResponse>;

export type IntegrationsBillingPortalGetError = BadRequest | NetbirdOpError;
/** Get customer portal URL */
export const integrationsBillingPortalGet: API.OperationMethod<
	IntegrationsBillingPortalGetRequest,
	PortalResponse,
	IntegrationsBillingPortalGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: IntegrationsBillingPortalGetRequest,
	output: PortalResponse,
	errors: [BadRequest, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
