import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (spec/netbird.api.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownNetbirdError } from "../errors.ts";
import { NetbirdProtocol, type NetbirdOpError, type NetbirdOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { NetbirdOpError, NetbirdOpContext };

export class BadRequest
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withBadRequestError),
		[{ status: 400 }],
	) {}

export class Forbidden
	extends /*@__PURE__*/ T.applyErrorMatchers(
		/*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
			code: S.Number,
			message: S.String,
		}).pipe(C.withAuthError),
		[{ status: 403 }],
	) {}

export interface SetupKeysGetRequest {}
export const SetupKeysGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api/setup-keys", code: 200 })),
).annotate({ identifier: "SetupKeysGetRequest" }) as any as S.Schema<SetupKeysGetRequest>;

/** List of group IDs to auto-assign to peers registered with this key */
export type SetupKeyAutoGroupsList = ReadonlyArray<string>;
export const SetupKeyAutoGroupsList = /*@__PURE__*/ S.Array(S.String) as any as S.Schema<SetupKeyAutoGroupsList>;

export interface SetupKey {
	/** Setup Key ID */
	id: string;
	/** Setup key name identifier */
	name: string;
	/** Setup Key expiration date */
	expires: string;
	/** Setup key type, one-off for single time usage and reusable */
	type: string;
	/** Setup key validity status */
	valid: boolean;
	/** Setup key revocation status */
	revoked: boolean;
	/** Usage count of setup key */
	used_times: number;
	/** Setup key last usage date */
	last_used: string;
	/** Setup key status, "valid", "overused","expired" or "revoked" */
	state: string;
	/** List of group IDs to auto-assign to peers registered with this key */
	auto_groups: SetupKeyAutoGroupsList;
	/** Setup key last update date */
	updated_at: string;
	/** A number of times this key can be used. The value of 0 indicates the unlimited usage. */
	usage_limit: number;
	/** Indicate that the peer will be ephemeral or not */
	ephemeral: boolean;
	/** Allow extra DNS labels to be added to the peer */
	allow_extra_dns_labels: boolean;
	/** Setup Key as secret */
	key: string;
}
export const SetupKey = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		expires: S.String,
		type: S.String,
		valid: S.Boolean,
		revoked: S.Boolean,
		used_times: S.Number,
		last_used: S.String,
		state: S.String,
		auto_groups: SetupKeyAutoGroupsList,
		updated_at: S.String,
		usage_limit: S.Number,
		ephemeral: S.Boolean,
		allow_extra_dns_labels: S.Boolean,
		key: S.String,
	}),
).annotate({ identifier: "SetupKey" }) as any as S.Schema<SetupKey>;

export type SetupKeysGetResponseBodyList = ReadonlyArray<SetupKey>;
export const SetupKeysGetResponseBodyList = /*@__PURE__*/ S.Array(
	SetupKey,
) as any as S.Schema<SetupKeysGetResponseBodyList>;

export type SetupKeysGetResponse = SetupKeysGetResponseBodyList;
export const SetupKeysGetResponse = /*@__PURE__*/ S.suspend(() =>
	SetupKeysGetResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "SetupKeysGetResponse" }) as any as S.Schema<SetupKeysGetResponse>;

export interface SetupKeysKeyIdDeleteRequest {
	/** The unique identifier of a setup key */
	keyId: string;
}
export const SetupKeysKeyIdDeleteRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		keyId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "DELETE", uri: "/api/setup-keys/{keyId}", code: 200 })),
).annotate({ identifier: "SetupKeysKeyIdDeleteRequest" }) as any as S.Schema<SetupKeysKeyIdDeleteRequest>;

export interface SetupKeysKeyIdDeleteResponse {}
export const SetupKeysKeyIdDeleteResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
	identifier: "SetupKeysKeyIdDeleteResponse",
}) as any as S.Schema<SetupKeysKeyIdDeleteResponse>;

export interface SetupKeysKeyIdGetRequest {
	/** The unique identifier of a setup key */
	keyId: string;
}
export const SetupKeysKeyIdGetRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		keyId: S.String.pipe(T.Label()),
	}).pipe(T.Http({ method: "GET", uri: "/api/setup-keys/{keyId}", code: 200 })),
).annotate({ identifier: "SetupKeysKeyIdGetRequest" }) as any as S.Schema<SetupKeysKeyIdGetRequest>;

/** List of group IDs to auto-assign to peers registered with this key */
export type SetupKeysKeyIdGetResponseAutoGroupsList = ReadonlyArray<string>;
export const SetupKeysKeyIdGetResponseAutoGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<SetupKeysKeyIdGetResponseAutoGroupsList>;

export interface SetupKeysKeyIdGetResponse {
	/** Setup Key ID */
	id: string;
	/** Setup key name identifier */
	name: string;
	/** Setup Key expiration date */
	expires: string;
	/** Setup key type, one-off for single time usage and reusable */
	type: string;
	/** Setup key validity status */
	valid: boolean;
	/** Setup key revocation status */
	revoked: boolean;
	/** Usage count of setup key */
	used_times: number;
	/** Setup key last usage date */
	last_used: string;
	/** Setup key status, "valid", "overused","expired" or "revoked" */
	state: string;
	/** List of group IDs to auto-assign to peers registered with this key */
	auto_groups: SetupKeysKeyIdGetResponseAutoGroupsList;
	/** Setup key last update date */
	updated_at: string;
	/** A number of times this key can be used. The value of 0 indicates the unlimited usage. */
	usage_limit: number;
	/** Indicate that the peer will be ephemeral or not */
	ephemeral: boolean;
	/** Allow extra DNS labels to be added to the peer */
	allow_extra_dns_labels: boolean;
	/** Setup Key as secret */
	key: string;
}
export const SetupKeysKeyIdGetResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		expires: S.String,
		type: S.String,
		valid: S.Boolean,
		revoked: S.Boolean,
		used_times: S.Number,
		last_used: S.String,
		state: S.String,
		auto_groups: SetupKeysKeyIdGetResponseAutoGroupsList,
		updated_at: S.String,
		usage_limit: S.Number,
		ephemeral: S.Boolean,
		allow_extra_dns_labels: S.Boolean,
		key: S.String,
	}),
).annotate({ identifier: "SetupKeysKeyIdGetResponse" }) as any as S.Schema<SetupKeysKeyIdGetResponse>;

/** List of group IDs to auto-assign to peers registered with this key */
export type SetupKeysKeyIdPutRequestAutoGroupsList = ReadonlyArray<string>;
export const SetupKeysKeyIdPutRequestAutoGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<SetupKeysKeyIdPutRequestAutoGroupsList>;

export interface SetupKeysKeyIdPutRequest {
	/** The unique identifier of a setup key */
	keyId: string;
	/** Setup key revocation status */
	revoked: boolean;
	/** List of group IDs to auto-assign to peers registered with this key */
	auto_groups: SetupKeysKeyIdPutRequestAutoGroupsList;
}
export const SetupKeysKeyIdPutRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		keyId: S.String.pipe(T.Label()),
		revoked: S.Boolean,
		auto_groups: SetupKeysKeyIdPutRequestAutoGroupsList,
	}).pipe(T.Http({ method: "PUT", uri: "/api/setup-keys/{keyId}", code: 200 })),
).annotate({ identifier: "SetupKeysKeyIdPutRequest" }) as any as S.Schema<SetupKeysKeyIdPutRequest>;

/** List of group IDs to auto-assign to peers registered with this key */
export type SetupKeysKeyIdPutResponseAutoGroupsList = ReadonlyArray<string>;
export const SetupKeysKeyIdPutResponseAutoGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<SetupKeysKeyIdPutResponseAutoGroupsList>;

export interface SetupKeysKeyIdPutResponse {
	/** Setup Key ID */
	id: string;
	/** Setup key name identifier */
	name: string;
	/** Setup Key expiration date */
	expires: string;
	/** Setup key type, one-off for single time usage and reusable */
	type: string;
	/** Setup key validity status */
	valid: boolean;
	/** Setup key revocation status */
	revoked: boolean;
	/** Usage count of setup key */
	used_times: number;
	/** Setup key last usage date */
	last_used: string;
	/** Setup key status, "valid", "overused","expired" or "revoked" */
	state: string;
	/** List of group IDs to auto-assign to peers registered with this key */
	auto_groups: SetupKeysKeyIdPutResponseAutoGroupsList;
	/** Setup key last update date */
	updated_at: string;
	/** A number of times this key can be used. The value of 0 indicates the unlimited usage. */
	usage_limit: number;
	/** Indicate that the peer will be ephemeral or not */
	ephemeral: boolean;
	/** Allow extra DNS labels to be added to the peer */
	allow_extra_dns_labels: boolean;
	/** Setup Key as secret */
	key: string;
}
export const SetupKeysKeyIdPutResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		expires: S.String,
		type: S.String,
		valid: S.Boolean,
		revoked: S.Boolean,
		used_times: S.Number,
		last_used: S.String,
		state: S.String,
		auto_groups: SetupKeysKeyIdPutResponseAutoGroupsList,
		updated_at: S.String,
		usage_limit: S.Number,
		ephemeral: S.Boolean,
		allow_extra_dns_labels: S.Boolean,
		key: S.String,
	}),
).annotate({ identifier: "SetupKeysKeyIdPutResponse" }) as any as S.Schema<SetupKeysKeyIdPutResponse>;

/** List of group IDs to auto-assign to peers registered with this key */
export type SetupKeysPostRequestAutoGroupsList = ReadonlyArray<string>;
export const SetupKeysPostRequestAutoGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<SetupKeysPostRequestAutoGroupsList>;

export interface SetupKeysPostRequest {
	/** Setup Key name */
	name: string;
	/** Setup key type, one-off for single time usage and reusable */
	type: string;
	/** Expiration time in seconds */
	expires_in: number;
	/** List of group IDs to auto-assign to peers registered with this key */
	auto_groups: SetupKeysPostRequestAutoGroupsList;
	/** A number of times this key can be used. The value of 0 indicates the unlimited usage. */
	usage_limit: number;
	/** Indicate that the peer will be ephemeral or not */
	ephemeral?: boolean;
	/** Allow extra DNS labels to be added to the peer */
	allow_extra_dns_labels?: boolean;
}
export const SetupKeysPostRequest = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		name: S.String,
		type: S.String,
		expires_in: S.Number,
		auto_groups: SetupKeysPostRequestAutoGroupsList,
		usage_limit: S.Number,
		ephemeral: S.optional(S.Boolean),
		allow_extra_dns_labels: S.optional(S.Boolean),
	}).pipe(T.Http({ method: "POST", uri: "/api/setup-keys", code: 200 })),
).annotate({ identifier: "SetupKeysPostRequest" }) as any as S.Schema<SetupKeysPostRequest>;

/** List of group IDs to auto-assign to peers registered with this key */
export type SetupKeysPostResponseAutoGroupsList = ReadonlyArray<string>;
export const SetupKeysPostResponseAutoGroupsList = /*@__PURE__*/ S.Array(
	S.String,
) as any as S.Schema<SetupKeysPostResponseAutoGroupsList>;

export interface SetupKeysPostResponse {
	/** Setup Key ID */
	id: string;
	/** Setup key name identifier */
	name: string;
	/** Setup Key expiration date */
	expires: string;
	/** Setup key type, one-off for single time usage and reusable */
	type: string;
	/** Setup key validity status */
	valid: boolean;
	/** Setup key revocation status */
	revoked: boolean;
	/** Usage count of setup key */
	used_times: number;
	/** Setup key last usage date */
	last_used: string;
	/** Setup key status, "valid", "overused","expired" or "revoked" */
	state: string;
	/** List of group IDs to auto-assign to peers registered with this key */
	auto_groups: SetupKeysPostResponseAutoGroupsList;
	/** Setup key last update date */
	updated_at: string;
	/** A number of times this key can be used. The value of 0 indicates the unlimited usage. */
	usage_limit: number;
	/** Indicate that the peer will be ephemeral or not */
	ephemeral: boolean;
	/** Allow extra DNS labels to be added to the peer */
	allow_extra_dns_labels: boolean;
	/** Setup Key as plain text */
	key: string;
}
export const SetupKeysPostResponse = /*@__PURE__*/ S.suspend(() =>
	S.Struct({
		id: S.String,
		name: S.String,
		expires: S.String,
		type: S.String,
		valid: S.Boolean,
		revoked: S.Boolean,
		used_times: S.Number,
		last_used: S.String,
		state: S.String,
		auto_groups: SetupKeysPostResponseAutoGroupsList,
		updated_at: S.String,
		usage_limit: S.Number,
		ephemeral: S.Boolean,
		allow_extra_dns_labels: S.Boolean,
		key: S.String,
	}),
).annotate({ identifier: "SetupKeysPostResponse" }) as any as S.Schema<SetupKeysPostResponse>;

export type SetupKeysGetError = BadRequest | Forbidden | NetbirdOpError;
/** List all Setup Keys Returns a list of all Setup Keys */
export const setupKeysGet: API.OperationMethod<
	SetupKeysGetRequest,
	SetupKeysGetResponse,
	SetupKeysGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: SetupKeysGetRequest,
	output: SetupKeysGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type SetupKeysKeyIdDeleteError = BadRequest | Forbidden | NetbirdOpError;
/** Delete a Setup Key Delete a Setup Key */
export const setupKeysKeyIdDelete: API.OperationMethod<
	SetupKeysKeyIdDeleteRequest,
	SetupKeysKeyIdDeleteResponse,
	SetupKeysKeyIdDeleteError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: SetupKeysKeyIdDeleteRequest,
	output: SetupKeysKeyIdDeleteResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type SetupKeysKeyIdGetError = BadRequest | Forbidden | NetbirdOpError;
/** Retrieve a Setup Key Get information about a setup key */
export const setupKeysKeyIdGet: API.OperationMethod<
	SetupKeysKeyIdGetRequest,
	SetupKeysKeyIdGetResponse,
	SetupKeysKeyIdGetError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: SetupKeysKeyIdGetRequest,
	output: SetupKeysKeyIdGetResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type SetupKeysKeyIdPutError = BadRequest | Forbidden | NetbirdOpError;
/** Update a Setup Key Update information about a setup key */
export const setupKeysKeyIdPut: API.OperationMethod<
	SetupKeysKeyIdPutRequest,
	SetupKeysKeyIdPutResponse,
	SetupKeysKeyIdPutError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: SetupKeysKeyIdPutRequest,
	output: SetupKeysKeyIdPutResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));

export type SetupKeysPostError = BadRequest | Forbidden | NetbirdOpError;
/** Create a Setup Key Creates a setup key */
export const setupKeysPost: API.OperationMethod<
	SetupKeysPostRequest,
	SetupKeysPostResponse,
	SetupKeysPostError,
	NetbirdOpContext
> = /*@__PURE__*/ API.make(() => ({
	input: SetupKeysPostRequest,
	output: SetupKeysPostResponse,
	errors: [BadRequest, Forbidden, UnknownNetbirdError],
	protocol: NetbirdProtocol,
	retry: Retry.Retry,
}));
